"use client";
import type {BradyInput,BradyInterpretation} from "@/types/bradyarrhythmia";

export function BradyarrhythmiaModule({input,result,onChange}:{input:BradyInput;result:BradyInterpretation;onChange:(next:BradyInput)=>void}){
  const set=<K extends keyof BradyInput>(key:K,value:BradyInput[K])=>onChange({...input,[key]:value});
  const adverse=(key:keyof BradyInput["adverseSigns"],value:boolean)=>onChange({...input,adverseSigns:{...input.adverseSigns,[key]:value}});
  return <section className="card brady-shell" id="bradyarrhythmia">
    <div className="cardhead"><div><div className="eyebrow">Bradyarrhythmia workflow</div><h3>徐脈性不整脈モジュール</h3><p className="muted">循環動態を優先し、医師修正値で再計算します。</p></div><span className={`badge brady-status brady-status--${result.urgency}`}>{result.urgency==="emergency"?"Red Flag":result.urgency==="same_day"?"要注意":result.urgency==="uncertain"?"判定不能":"安定"}</span></div>
    <div className="brady-flow" aria-label="徐脈診断フロー">{["循環動態","P波","P-QRS関係","PRパターン","QRS脱落","補充調律","緊急度"].map((x,i)=><span key={x}>{i+1}. {x}</span>)}</div>
    {result.redFlags.length>0&&<div className="result stop" role="alert"><strong>Red Flag：{result.redFlags.join("／")}</strong><p>徐脈に伴う循環障害または高度伝導障害の可能性があります。初期対応を開始し専門チームへ連絡してください。</p></div>}
    <details className="brady-details" open><summary>【循環動態・医師確認】</summary><div className="brady-grid">
      <label>心室拍数<input aria-label="心室拍数" type="number" value={input.ventricularRateBpm??""} onChange={e=>set("ventricularRateBpm",number(e.target.value))}/></label><label>心房拍数<input aria-label="心房拍数" type="number" value={input.atrialRateBpm??""} onChange={e=>set("atrialRateBpm",number(e.target.value))}/></label><label>QRS幅<input aria-label="徐脈QRS幅" type="number" value={input.qrsWidthMs??""} onChange={e=>set("qrsWidthMs",number(e.target.value))}/></label>
      <label>規則性<select value={input.rateRegularity} onChange={e=>set("rateRegularity",e.target.value as BradyInput["rateRegularity"])}><option value="regular">規則的</option><option value="regularly_irregular">規則的不整</option><option value="irregular">不規則</option><option value="indeterminate">判定不能</option></select></label>
      <label>P波<select value={input.pWavePresence} onChange={e=>set("pWavePresence",e.target.value as BradyInput["pWavePresence"])}><option value="present">存在</option><option value="absent">消失</option><option value="intermittent">間欠的</option><option value="hidden">QRS/T内</option><option value="indeterminate">判定不能</option></select></label><label>洞性P波<select value={input.sinusMorphology} onChange={e=>set("sinusMorphology",e.target.value as BradyInput["sinusMorphology"])}><option value="sinus">洞性</option><option value="non_sinus">非洞性</option><option value="uncertain">不明</option></select></label>
      <label>P-QRS関係<select value={input.pToQrsRelationship} onChange={e=>set("pToQrsRelationship",e.target.value as BradyInput["pToQrsRelationship"])}><option value="one_to_one">1:1</option><option value="two_to_one">2:1</option><option value="three_to_one">3:1</option><option value="variable_conduction">可変</option><option value="av_dissociation">房室解離</option><option value="indeterminate">判定不能</option></select></label>
      <label>PRパターン<select value={input.prPattern} onChange={e=>set("prPattern",e.target.value as BradyInput["prPattern"])}><option value="normal">正常</option><option value="prolonged_constant">延長・一定</option><option value="progressive_prolongation">進行性延長</option><option value="constant_before_dropped_qrs">脱落前一定</option><option value="variable">可変</option><option value="not_measurable">測定不能</option><option value="indeterminate">判定不能</option></select></label>
      <label>補充調律<select value={input.escapeRhythm} onChange={e=>set("escapeRhythm",e.target.value as BradyInput["escapeRhythm"])}><option value="none">なし</option><option value="atrial_escape">心房性</option><option value="junctional_escape">接合部</option><option value="ventricular_escape">心室性</option><option value="paced_rhythm">ペーシング</option><option value="indeterminate">判定不能</option></select></label>
      <label>医師分類<select value={input.clinicianClassification} onChange={e=>set("clinicianClassification",e.target.value as BradyInput["clinicianClassification"])}>{["auto","no_bradycardia","physiologic_sinus_bradycardia_candidate","sinus_bradycardia_candidate","sinus_pause_candidate","sinoatrial_block_candidate","sinus_node_dysfunction_candidate","first_degree_av_block","mobitz_i_candidate","mobitz_ii_candidate","two_to_one_av_block","high_grade_av_block_candidate","complete_av_block_candidate","av_dissociation_uncertain","af_slow_ventricular_response","indeterminate"].map(x=><option key={x} value={x}>{x}</option>)}</select></label>
    </div><div className="checks brady-checks">{[["droppedQrs","QRS脱落"],["multipleNonconductedP","複数P非伝導"],["pausePresent","休止"],["expectedPWaveMissing","期待P波欠落"],["bundleBranchBlock","脚ブロック"],["atrialFibrillation","心房細動"],["atrialFlutter","心房粗動"],["artifactConcern","アーチファクト"],["athlete","アスリート"],["sleeping","睡眠中"],["betaBlocker","β遮断薬"],["highPotassium","高K"],["inferiorIschemia","下壁ST変化"],["qtMarkedProlongation","著明QT延長"],["rOnTCandidate","R on T"]].map(([k,l])=><label className="check" key={k}><input type="checkbox" checked={Boolean(input[k as keyof BradyInput])} onChange={e=>set(k as keyof BradyInput,e.target.checked as never)}/>{l}</label>)}</div>
    <div className="checks brady-checks">{[["alteredMentalStatus","意識障害"],["syncope","失神"],["presyncope","前失神"],["hypotension","低血圧"],["shockSigns","ショック"],["ischemicChestDiscomfort","虚血性胸痛"],["acuteHeartFailure","急性心不全"],["hypoxemia","低酸素"],["poorPerfusion","低灌流"]].map(([k,l])=><label className="check" key={k}><input type="checkbox" checked={input.adverseSigns[k as keyof BradyInput["adverseSigns"]]===true} onChange={e=>adverse(k as keyof BradyInput["adverseSigns"],e.target.checked)}/>{l}</label>)}</div></details>
    <div className="brady-results"><section><h4>診断理由</h4><ol className="list">{result.diagnosticReasoning.map(x=><li key={x}>{x}</li>)}</ol></section><section><h4>判定</h4><strong>{result.classification}</strong>{result.warnings.map(x=><p className="muted" key={x}>{x}</p>)}</section><section><h4>Clinical Pearl</h4><ul className="list">{result.clinicalPearls.map(x=><li key={x}>{x}</li>)}</ul></section><section><h4>ペーシング評価</h4>{result.pacingEvaluation.length?<ul className="list">{result.pacingEvaluation.map(x=><li key={x}>{x}</li>)}</ul>:<p className="muted">アプリ単独では適応を確定しません。</p>}</section></div>
  </section>;
}
function number(v:string){const n=Number(v);return v===""||!Number.isFinite(n)?null:n}
