"use client";

import {useEffect,useRef,useState} from "react";
import type React from "react";
import {enhanceContrast,rectifyQuad,rotateGray,toGrayscale,type GrayImage} from "@/lib/ecg-digitizer/digitizer-core.js";
import {buildConfirmedLeadLayout,createGridCandidate,createLayoutCandidate,createPaperRegionCandidate,evaluateLocalImageQuality,updateLeadRegion} from "@/lib/ecg-digitizer/phase-b.js";
import type {EcgLeadLayoutCandidate,EcgLeadLayoutType,EcgLeadRegionCandidate,EcgPaperRegionCandidate,LocalEcgImageQualityResult,LocalGridCandidate} from "@/types/local-image-layout";
import type {LeadName} from "@/types/ecg";

const leadOptions:Array<LeadName|"rhythm_strip"|"unknown">=["I","II","III","aVR","aVL","aVF","V1","V2","V3","V4","V5","V6","rhythm_strip","unknown"];
const layoutLabels:Record<EcgLeadLayoutType,string>={three_by_four:"標準3行×4列",six_by_two:"標準6行×2列",twelve_lead_with_long_ii:"12誘導＋長時間II誘導",twelve_lead_with_long_v1:"12誘導＋長時間V1誘導",unknown:"不明／非対応"};
const qualityLabels={adequate:"評価可能",limited:"制限あり",inadequate:"不十分",indeterminate:"判定困難"};
type PhaseBResult={quality:LocalEcgImageQualityResult;paper:EcgPaperRegionCandidate;grid:LocalGridCandidate};
type DragState={id:string;mode:"move"|"resize";startX:number;startY:number;initial:EcgLeadRegionCandidate["region"]};

function drawGray(canvas:HTMLCanvasElement,gray:GrayImage){canvas.width=gray.width;canvas.height=gray.height;const context=canvas.getContext("2d");if(!context)throw new Error("Canvasを初期化できませんでした。");const rgba=context.createImageData(gray.width,gray.height);for(let i=0,p=0;p<gray.data.length;i+=4,p++){const value=gray.data[p];rgba.data[i]=value;rgba.data[i+1]=value;rgba.data[i+2]=value;rgba.data[i+3]=255}context.putImageData(rgba,0,0)}
function paperBounds(paper:EcgPaperRegionCandidate,width:number,height:number){if(!paper.polygon.length)return {x:0,y:0,width,height};const xs=paper.polygon.map(p=>p.x),ys=paper.polygon.map(p=>p.y),x=Math.min(...xs),y=Math.min(...ys);return {x,y,width:Math.max(1,Math.max(...xs)-x),height:Math.max(1,Math.max(...ys)-y)}}

export function EcgImageDigitizerPrototype({file,onRequestCrop}:{file:File;onRequestCrop?:()=>void}){
  const canvasRef=useRef<HTMLCanvasElement|null>(null),abortRef=useRef<AbortController|null>(null),originalRef=useRef<GrayImage|null>(null),correctedRef=useRef<GrayImage|null>(null),dragRef=useRef<DragState|null>(null);
  const [result,setResult]=useState<PhaseBResult|null>(null),[layout,setLayout]=useState<EcgLeadLayoutCandidate|null>(null),[status,setStatus]=useState<"idle"|"running"|"complete"|"error">("idle"),[message,setMessage]=useState("画像品質と12誘導領域候補を端末内で評価します。"),[showCorrected,setShowCorrected]=useState(false),[paperAccepted,setPaperAccepted]=useState(false),[confirmed,setConfirmed]=useState(false),[imageDimensions,setImageDimensions]=useState({width:1,height:1});
  useEffect(()=>()=>abortRef.current?.abort(),[]);

  async function run(){abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setStatus("running");setMessage("画像品質を評価しています…");setConfirmed(false);try{const bitmap=await createImageBitmap(file,{imageOrientation:"from-image"});try{if(controller.signal.aborted)throw new DOMException("Aborted","AbortError");const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),width=Math.max(1,Math.round(bitmap.width*scale)),height=Math.max(1,Math.round(bitmap.height*scale));const work=document.createElement("canvas");work.width=width;work.height=height;const context=work.getContext("2d",{willReadFrequently:true});if(!context)throw new Error("画像処理Canvasを初期化できませんでした。");context.fillStyle="#fff";context.fillRect(0,0,width,height);context.drawImage(bitmap,0,0,width,height);const gray=enhanceContrast(toGrayscale(context.getImageData(0,0,width,height))),quality=evaluateLocalImageQuality(gray),paper=createPaperRegionCandidate(gray),grid=createGridCandidate(gray);originalRef.current=gray;correctedRef.current=paper.polygon.length?rectifyQuad(rotateGray(gray,-(quality.metrics.estimatedRotationDeg??0)),paper.polygon):gray;setResult({quality,paper,grid});setShowCorrected(false);setImageDimensions({width:gray.width,height:gray.height});setPaperAccepted(false);const initialLayout=quality.canProceedToLayoutDetection&&paper.polygon.length?"three_by_four":"unknown";setLayout(createLayoutCandidate(initialLayout,paperBounds(paper,gray.width,gray.height)));requestAnimationFrame(()=>{if(canvasRef.current)drawGray(canvasRef.current,gray)});setStatus(quality.canProceedToLayoutDetection?"complete":"error");setMessage(quality.canProceedToLayoutDetection?"品質・用紙・誘導領域の候補を生成しました。医師が確認してください。":"この画像ではローカル波形推定を開始できません。撮り直すか、医師入力で続けてください。")}finally{bitmap.close()}}catch(error){if(error instanceof DOMException&&error.name==="AbortError"){setStatus("idle");setMessage("画像評価を中断しました。");return}setStatus("error");setMessage(error instanceof Error?error.message:"画像品質評価に失敗しました。")}}
  function selectLayout(type:EcgLeadLayoutType){if(!result||!originalRef.current)return;const image=showCorrected?correctedRef.current:originalRef.current;if(!image)return;setLayout(createLayoutCandidate(type,paperBounds(result.paper,image.width,image.height)));setConfirmed(false)}
  function toggleCorrection(next:boolean){const image=next?correctedRef.current:originalRef.current;if(!image||!result)return;setShowCorrected(next);setImageDimensions({width:image.width,height:image.height});drawGray(canvasRef.current!,image);setLayout(createLayoutCandidate(layout?.layoutType??"unknown",next?{x:0,y:0,width:image.width,height:image.height}:paperBounds(result.paper,image.width,image.height)));setConfirmed(false)}
  function changeRegion(id:string,patch:Partial<EcgLeadRegionCandidate>){setLayout(current=>current?{...current,detectedRegions:updateLeadRegion(current.detectedRegions,id,patch),reviewStatus:"modified"}:current);setConfirmed(false)}
  function pointerMove(event:React.PointerEvent<HTMLDivElement>){const drag=dragRef.current,image=showCorrected?correctedRef.current:originalRef.current;if(!drag||!image)return;const bounds=event.currentTarget.getBoundingClientRect(),dx=(event.clientX-drag.startX)*image.width/bounds.width,dy=(event.clientY-drag.startY)*image.height/bounds.height;changeRegion(drag.id,{reviewStatus:"modified",region:drag.mode==="move"?{...drag.initial,x:drag.initial.x+dx,y:drag.initial.y+dy}:{...drag.initial,width:drag.initial.width+dx,height:drag.initial.height+dy}})}
  function confirmRegions(){if(!result||!layout)return;const output=buildConfirmedLeadLayout({layout,paperRegion:result.paper,grid:result.grid,imageQuality:result.quality});setConfirmed(Boolean(output));setMessage(output?"解析準備完了：承認・修正済み領域だけをPhase Cへ渡せます。":"領域を確定できません。用紙領域と少なくとも1つの誘導領域を確認してください。");setStatus(output?"complete":"error")}
  const paperRectangle=result?paperBounds(result.paper,imageDimensions.width,imageDimensions.height):null;
  return <section className="digitizer-prototype" aria-label="ローカル画像品質・12誘導領域候補">
    <div className="digitizer-prototype__head"><div><div className="eyebrow">Version 3 · Phase B</div><h4>画像品質・12誘導領域候補</h4><p>決定論的なブラウザ内処理です。OCR、波形所見、診断、mm・ms換算は行いません。</p></div><span className="badge">外部送信なし</span></div>
    <div className="upload-actions"><button className="btn secondary" type="button" disabled={status==="running"} onClick={run}>画像品質と領域を評価</button>{status==="running"&&<button className="btn" type="button" onClick={()=>abortRef.current?.abort()}>中断</button>}</div>
    <div className={`analysis-status analysis-status--${status}`} role="status" aria-live="polite">{status==="running"&&<span className="analysis-spinner" aria-hidden="true"/>}<strong>{message}</strong></div>
    {result&&<><section className={`phase-b-quality phase-b-quality--${result.quality.level}`}><h5>画像品質：{qualityLabels[result.quality.level]}</h5><dl><div><dt>画像寸法</dt><dd>{result.quality.width} × {result.quality.height}px</dd></div><div><dt>傾き候補</dt><dd>{result.quality.metrics.estimatedRotationDeg?.toFixed(1)??"判定困難"}°</dd></div><div><dt>グリッド</dt><dd>{result.grid.detected?`${result.grid.horizontalSpacingPx} × ${result.grid.verticalSpacingPx}px候補`:`未検出（mm換算しません）`}</dd></div></dl>{result.quality.issues.length?<ul className="list">{result.quality.issues.map((issue,index)=><li key={`${issue.type}-${index}`}><strong>{issue.explanationJa}</strong>（{issue.severity}）</li>)}</ul>:<p className="muted">決定論的品質指標で大きな制限候補はありません。</p>}{result.quality.suggestedActions.length?<ul className="list">{result.quality.suggestedActions.map(action=><li key={action}>{action}</li>)}</ul>:null}</section>
      <div className="phase-b-paper-actions"><strong>心電図用紙領域候補：{result.paper.confidence}</strong><div className="upload-actions"><button className="btn" type="button" disabled={!result.paper.polygon.length} onClick={()=>setPaperAccepted(true)}>この領域を使用</button><button className="btn" type="button" onClick={()=>{setPaperAccepted(false);onRequestCrop?.()}}>範囲を修正</button><button className="btn" type="button" onClick={()=>toggleCorrection(false)}>元画像を使用</button><button className="btn" type="button" disabled={!result.paper.polygon.length} onClick={()=>toggleCorrection(true)}>補正候補を適用</button></div><p className="muted">{paperAccepted?"用紙領域を確認済み":"用紙領域は未確認です"} ／ {showCorrected?"補正候補表示":"原画像表示"}</p></div>
      <label className="phase-b-layout-select">レイアウト候補<select value={layout?.layoutType??"unknown"} onChange={event=>selectLayout(event.target.value as EcgLeadLayoutType)}>{Object.entries(layoutLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
      <div className="phase-b-overlay" onPointerMove={pointerMove} onPointerUp={()=>{dragRef.current=null}} onPointerCancel={()=>{dragRef.current=null}}>
        <canvas ref={canvasRef} className="digitizer-overlay" aria-label={showCorrected?"補正候補画像と誘導推定領域":"原画像と誘導推定領域"}/>
        {paperRectangle&&result.paper.polygon.length>0&&<div className="paper-region-box" aria-label="心電図用紙推定領域" style={{left:`${paperRectangle.x/imageDimensions.width*100}%`,top:`${paperRectangle.y/imageDimensions.height*100}%`,width:`${paperRectangle.width/imageDimensions.width*100}%`,height:`${paperRectangle.height/imageDimensions.height*100}%`}}><span>用紙領域候補</span></div>}
        {layout?.detectedRegions.map(region=><button type="button" key={region.id} className={`lead-region-box lead-region-box--${region.reviewStatus}`} style={{left:`${region.region.x/imageDimensions.width*100}%`,top:`${region.region.y/imageDimensions.height*100}%`,width:`${region.region.width/imageDimensions.width*100}%`,height:`${region.region.height/imageDimensions.height*100}%`}} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);dragRef.current={id:region.id,mode:"move",startX:event.clientX,startY:event.clientY,initial:region.region}}}>
          <span>{region.lead}推定領域</span><i aria-label="領域をリサイズ" onPointerDown={event=>{event.stopPropagation();dragRef.current={id:region.id,mode:"resize",startX:event.clientX,startY:event.clientY,initial:region.region}}}/>
        </button>)}
      </div>
      {layout&&<div className="lead-region-editors">{layout.detectedRegions.map(region=><article key={region.id}><header><strong>{region.lead}推定領域</strong><span>{region.confidence}</span></header><label>誘導名<select value={region.lead} onChange={event=>changeRegion(region.id,{lead:event.target.value as EcgLeadRegionCandidate["lead"],reviewStatus:"modified"})}>{leadOptions.map(lead=><option key={lead} value={lead}>{lead}</option>)}</select></label><div className="region-number-grid">{(["x","y","width","height"] as const).map(key=><label key={key}>{key}<input type="number" min={key==="width"||key==="height"?1:0} value={Math.round(region.region[key])} onChange={event=>changeRegion(region.id,{reviewStatus:"modified",region:{...region.region,[key]:Number(event.target.value)}})}/></label>)}</div><div className="upload-actions"><button className="btn" type="button" onClick={()=>changeRegion(region.id,{reviewStatus:"accepted"})}>承認</button><button className="btn" type="button" onClick={()=>changeRegion(region.id,{reviewStatus:"rejected"})}>却下</button></div><p className="muted">{region.reviewStatus}</p></article>)}</div>}
      <div className="upload-actions"><button className="btn" type="button" onClick={()=>layout&&selectLayout(layout.layoutType)}>全領域をリセット</button><button className="btn" type="button" onClick={()=>{if(!layout)return;const next=createLayoutCandidate(layout.layoutType,{x:0,y:0,width:imageDimensions.width,height:imageDimensions.height});const added={id:`unknown-${Date.now()}`,lead:"unknown" as const,region:{x:imageDimensions.width*.1,y:imageDimensions.height*.1,width:imageDimensions.width*.2,height:imageDimensions.height*.2},confidence:"indeterminate" as const,reviewStatus:"pending" as const,limitations:["医師が追加した領域です"]};setLayout({...next,detectedRegions:[...layout.detectedRegions,added],reviewStatus:"modified"})}}>領域を追加</button><button className="btn primary-action" type="button" disabled={!paperAccepted} onClick={confirmRegions}>領域を確定</button></div>{confirmed&&<div className="result"><strong>解析準備完了</strong><br/>承認・修正済みの誘導領域だけが次Phaseの入力対象です。</div>}
    </>}
    <p className="muted">誘導名は選択レイアウトと位置関係から割り当てた候補です。画像からOCRで読み取ったものではありません。</p>
  </section>;
}
