"use client";

import { calculateQtc, QT_CLASSIFICATION_THRESHOLDS_MS } from "@/logic/qt-interpretation/interpret-qt.js";
import { WIDE_QRS_THRESHOLD_MS } from "@/logic/tachyarrhythmia/classify.js";
import { contiguousLeadGroups, elevationThresholdMm, reciprocalEducation } from "@/data/st-interpretation/criteria.js";
import type { BradyInput } from "@/types/bradyarrhythmia";
import type { ConductionInput } from "@/types/conduction-interpretation";
import type { QtInterpretationInput } from "@/types/qt-interpretation";

type Props={heartRate:string;brady:BradyInput;conduction:ConductionInput;qt:QtInterpretationInput};
type GuideProps={title:string;diagram:React.ReactNode;look:string;measure:string;guide:React.ReactNode;consider:string;prevent:string;targetId?:string};

export function FindingEducationGuide({heartRate,brady,conduction,qt}:Props){
  const hr=numberOrNull(heartRate); const qtc=calculateQtc(qt.qtMs,qt.rrMs,hr,qt.formula);
  const focus=(id?:string)=>{if(!id)return;const labels={"ecg-heart-rate-input":"心拍数","ecg-pr-input":"PR","ecg-qrs-input":"QRS幅・形態","ecg-qt-input":"QT（ms）","ecg-st-input":"ST変化"} as Record<string,string>;const element=document.getElementById(id)??Array.from(document.querySelectorAll<HTMLLabelElement>(".compact-clinical-review label")).find(label=>label.textContent?.startsWith(labels[id]))?.querySelector<HTMLElement>("input,select");element?.focus();element?.scrollIntoView({behavior:"smooth",block:"center"})};
  const items:GuideProps[]=[
    {title:"心電図の基本",diagram:<BasicWave/>,look:"P波、QRS、ST、T波、必要に応じてU波を順に確認します。",measure:"25 mm/sでは横1 mm＝40 ms、5 mm＝200 ms。10 mm/mVでは縦1 mm＝0.1 mV、10 mm＝1 mVです。",guide:<p>P波：心房興奮／PR：P開始からQRS開始／QRS：心室脱分極／ST：J点からT波開始前／T波：心室再分極／QT：QRS開始からT波終了。</p>,consider:"記録速度・感度が異なる場合は換算も変わります。",prevent:"速度、感度、基線、波形終末が確認できないときは測定を確定しません。"},
    {title:"PR間隔",diagram:<MeasureWave start={35} end={82} label="PR"/>,look:"P波の開始点とQRSの開始点を見ます。",measure:"P波開始からQRS開始までをmsで測ります。",guide:<p>一般的目安は120–200 msです。ただし現在のRule Engineは数値閾値ではなく、医師が入力した「正常・短縮・延長」を使用します。現在の入力：<b>{prLabel(brady.prPattern)}</b></p>,consider:"短縮時はΔ波・QRS幅・pre-excitation・頻拍歴、延長時は房室伝導障害や薬剤を確認します。",prevent:"一般的目安をRule Engineの独立した数値判定としては使用しません。",targetId:"ecg-pr-input"},
    {title:"QRS幅",diagram:<MeasureWave start={92} end={135} label="QRS"/>,look:"QRSが最初に基線から外れる点と、最後に基線へ戻る点を見ます。",measure:"QRS開始から終了までをmsで測ります。",guide:<p>このアプリでは <b>{WIDE_QRS_THRESHOLD_MS} ms以上をwide</b> と判定します。現在値：<b>{conduction.qrsDurationMs==null?"未入力":`${conduction.qrsDurationMs} ms → ${conduction.qrsDurationMs>=WIDE_QRS_THRESHOLD_MS?"wide":"narrow"}`}</b></p>,consider:"wideではRBBB、LBBB、心室起源、pre-excitation、高Kなど既存鑑別を確認します。",prevent:"幅だけで脚ブロックや心室起源を確定しません。",targetId:"ecg-qrs-input"},
    {title:"QT / QTc",diagram:<MeasureWave start={92} end={255} label="QT"/>,look:"QRS開始点とT波終末を見ます。U波との境界も確認します。",measure:"QRS開始からT波終末までを測り、心拍数補正したQTcで評価します。",guide:<p>既存基準：境界域 {QT_CLASSIFICATION_THRESHOLDS_MS.borderlineMin} ms以上、延長 {QT_CLASSIFICATION_THRESHOLDS_MS.prolongedMin} ms以上、著明延長 {QT_CLASSIFICATION_THRESHOLDS_MS.markedProlongationMin} ms以上。現在：<b>QT {qt.qtMs??"未入力"} ms／QTc {qtc??"判定困難"} ms</b></p>,consider:"著明延長にR on T、徐脈・pause、失神などが重なる場合はTdPリスクを確認します。",prevent:"QTだけで単純判定せず、T終末不明やU波混入時は測定制限とします。",targetId:"ecg-qt-input"},
    {title:"ST / J点",diagram:<StDiagram/>,look:"PR segment等の基線、QRS終末のJ点、J点付近のST偏位を見ます。",measure:"基線に対する縦方向の差を測ります。10 mm/mVなら1 mm＝0.1 mVです。",guide:<StCriteria/>,consider:"形態、誘導分布、症状、心拍数、脚ブロック、LVH、digitalisを合わせて評価します。",prevent:"V2–V3は年齢・性別で基準が異なります。判定できなければ判定困難を選びます。",targetId:"ecg-st-input"},
    {title:"Δ波",diagram:<ComparisonDiagram left="正常QRS" right="Δ波：slurred" kind="delta"/>,look:"QRS開始部が急峻か、なだらかに立ち上がるかを見ます。",measure:"PR短縮とQRS幅も同時に確認します。",guide:<p>Δ波候補ではPR短縮、QRS幅、頻拍歴、AFを確認します。</p>,consider:"pre-excitationを考慮します。",prevent:"Δ波単独でWPW syndromeとは確定しません。"},
    {title:"R on T",diagram:<RonTDiagram/>,look:"PVCが先行拍のT波上またはT波終末付近へ重なるかを見ます。",measure:"通常拍、T波終了後のPVC、T波へ重なるPVCを比較します。",guide:<p>重なりが確認できる場合だけR on T候補として入力します。</p>,consider:"QT/QTc、徐脈・pause、電解質、多形性VT/TdPリスクを確認します。",prevent:"PVCやT波の境界が不明なら判定困難とします。"},
    {title:"R波進行",diagram:<RProgressionDiagram/>,look:"V1からV6までR波とS波の相対的な変化を追います。",measure:"各胸部誘導のR/S比を順番に比較します。",guide:<p>normal progression、poor R-wave progression、V1–V3 high Rを比較します。</p>,consider:"poor progressionや後壁鏡像変化など既存Ruleの候補を確認します。",prevent:"transition zoneの新しい数値基準は追加していません。"},
    {title:"後壁鏡像変化",diagram:<PosteriorDiagram/>,look:"V1–V3の高いR波とST低下を見ます。",measure:"前胸部誘導と後壁側のST変化を鏡像として対応させます。",guide:<p>V1–V3の高いR波＋ST低下では後壁虚血・梗塞を考慮し、V7–V9を確認します。</p>,consider:"既存ECG-ST-003の評価へつなげます。",prevent:"鏡像所見だけで後壁梗塞を確定しません。"},
    {title:"LBBB",diagram:<ComparisonDiagram left="正常QRS / ST-T" right="LBBB / 二次性ST-T" kind="lbbb"/>,look:"wide QRSとQRSに対して逆方向になり得る二次性ST-T変化を見ます。",measure:"QRS幅とST-Tの方向関係を確認します。",guide:<p>LBBBでは通常のST上昇・低下だけによる急性虚血評価が困難です。</p>,consider:"急性虚血が疑われる場合はSgarbossa / modified Sgarbossa評価を確認します。",prevent:"通常ST基準を機械的に適用しません。"},
    {title:"reciprocal change",diagram:<ReciprocalDiagram/>,look:"ST上昇領域と反対側に対応するST低下があるかを見ます。",measure:"同一記録の誘導分布を比較します。",guide:<ReciprocalTable/>,consider:"急性虚血候補の支持所見として既存Ruleで評価します。",prevent:"対応は既存の誘導群定義だけを表示しています。"},
    {title:"Digitalis effect",diagram:<SimpleTrend label="ST低下・T波変化"/>,look:"digitalis使用中のST低下とT波変化を見ます。",measure:"誘導分布、症状、前回・連続ECGと合わせます。",guide:<p>digitalis使用中ではST-T変化を認めることがあり、虚血性ST変化との鑑別が必要です。</p>,consider:"既存ECG-ST-008の鑑別表示へつなげます。",prevent:"digitalis使用＝虚血なし、とは扱いません。"},
    {title:"頻脈関連ST変化",diagram:<SimpleTrend label="頻脈時 → ST低下"/>,look:"頻脈中のST変化と、心拍数改善後の持続・消失を見ます。",measure:"心拍数と同時にST変化を評価します。",guide:<p>rate-related ST changeの可能性がありますが、虚血を除外する所見ではありません。現在HR：<b>{hr==null?"未入力":`${hr} bpm`}</b></p>,consider:"既存ECG-ST-009の鑑別表示へつなげます。",prevent:"頻脈だけを理由にST低下を良性と確定しません。",targetId:"ecg-heart-rate-input"}
  ];
  return <details className="finding-education"><summary aria-label="心電図所見の見方を開閉">見方：測定と判定のミニリファレンス</summary><div className="finding-guide-list">{items.map(item=><Guide key={item.title} {...item} onFocus={focus}/>)}</div></details>;
}

function Guide({title,diagram,look,measure,guide,consider,prevent,targetId,onFocus}:GuideProps&{onFocus:(id?:string)=>void}){return <details className="finding-guide-item"><summary>{title}</summary><div className="finding-guide-body">{diagram}<GuideRow n="1" title="どこを見る？">{look}</GuideRow><GuideRow n="2" title="どう測る？">{measure}</GuideRow><GuideRow n="3" title="判定の目安">{guide}</GuideRow><GuideRow n="4" title="この所見なら何を考える？">{consider}</GuideRow><GuideRow n="5" title="見落とし防止">{prevent}<br/>判断に迷う場合は「判定困難」を選択してください。未入力・判定困難を正常所見として扱いません。</GuideRow><GuideRow n="6" title="アプリではどこへ入力する？"><button type="button" className="btn" onClick={()=>onFocus(targetId)} disabled={!targetId}>該当入力へ戻る</button></GuideRow></div></details>}
function GuideRow({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section><h5><span>{n}</span>{title}</h5><div>{children}</div></section>}
function Wave({children}:{children?:React.ReactNode}){return <svg viewBox="0 0 300 92" role="img" aria-label="オリジナル心電図模式図"><line x1="5" y1="55" x2="295" y2="55" className="guide-baseline"/><path d="M5 55 L32 55 Q43 28 55 55 L82 55 L94 68 L108 8 L121 72 L135 55 L205 55 Q230 20 255 55 L270 55 Q280 42 290 55 L295 55" className="guide-wave"/>{children}</svg>}
function BasicWave(){return <Wave><text x="40" y="24">P</text><text x="98" y="15">QRS</text><text x="158" y="49">ST</text><text x="225" y="19">T</text><text x="278" y="38">U</text></Wave>}
function MeasureWave({start,end,label}:{start:number;end:number;label:string}){return <Wave><line x1={start} y1="78" x2={end} y2="78" className="guide-measure"/><text x={(start+end)/2-10} y="90">{label}</text></Wave>}
function StDiagram(){return <Wave><circle cx="135" cy="55" r="4"/><text x="125" y="80">J点</text><line x1="135" y1="55" x2="135" y2="35" className="guide-measure"/><text x="140" y="44">1 mm</text><text x="8" y="51">基線</text></Wave>}
function ComparisonDiagram({left,right,kind}:{left:string;right:string;kind:string}){return <svg viewBox="0 0 300 100" role="img" aria-label={`${left}と${right}の比較`}><text x="12" y="14">{left}</text><text x="160" y="14">{right}</text><path d="M8 56 L45 56 L55 20 L65 72 L76 56 L135 56" className="guide-wave"/><path d={kind==="delta"?"M158 56 L185 56 Q205 53 220 20 L232 72 L245 56 L292 56":"M158 56 L185 56 L205 22 L230 72 L248 20 L266 60 Q280 78 294 60"} className="guide-wave"/><text x="184" y="88">ここを見る ↑</text></svg>}
function RonTDiagram(){return <svg viewBox="0 0 300 150" role="img" aria-label="通常拍、T波後PVC、R on Tの比較"><text x="4" y="20">A 通常</text><text x="4" y="70">B T波後PVC</text><text x="4" y="120">C R on T</text>{[20,70,120].map((y,i)=><path key={y} d={i===0?`M75 ${y} L105 ${y} L115 ${y-17} L123 ${y+16} L132 ${y} Q150 ${y-12} 168 ${y} L290 ${y}`:i===1?`M75 ${y} Q95 ${y-12} 115 ${y} L170 ${y} L180 ${y+14} L190 ${y-24} L200 ${y+15} L215 ${y} L290 ${y}`:`M75 ${y} Q100 ${y-15} 128 ${y} L133 ${y+14} L143 ${y-27} L153 ${y+16} L166 ${y} L290 ${y}`} className={i===2?"guide-wave guide-alert":"guide-wave"}/>)}</svg>}
function RProgressionDiagram(){return <svg viewBox="0 0 360 130" role="img" aria-label="V1からV6のR波進行"><text x="5" y="15">normal progression</text>{[1,2,3,4,5,6].map((v,i)=>{const x=12+i*58,r=15+i*6,s=44-i*6;return <g key={v}><text x={x+15} y="125">V{v}</text><line x1={x} y1="70" x2={x+48} y2="70" className="guide-baseline"/><path d={`M${x} 70 L${x+18} 70 L${x+23} ${70-r} L${x+28} ${70+s} L${x+34} 70 L${x+48} 70`} className="guide-wave"/></g>})}<text x="5" y="102">R↑　S↓　／ poor progression・V1–V3 high R</text></svg>}
function PosteriorDiagram(){return <svg viewBox="0 0 300 100" role="img" aria-label="後壁鏡像変化"><text x="15" y="15">V1–V3：高いR＋ST低下</text><text x="175" y="15">後壁側：ST上昇</text><path d="M8 55 L35 55 L48 15 L60 70 L72 55 L135 70" className="guide-wave"/><path d="M165 55 L200 55 L215 75 L228 20 L242 70 L255 40 L292 40" className="guide-wave"/><text x="137" y="92">↔ mirror</text></svg>}
function ReciprocalDiagram(){return <svg viewBox="0 0 300 85" role="img" aria-label="ST上昇とreciprocal change"><path d="M5 55 L65 55 L80 15 L95 70 L112 32 L145 32" className="guide-wave"/><path d="M155 55 L215 55 L230 90 L245 35 L260 70 L295 70" className="guide-wave"/><text x="20" y="15">ST上昇</text><text x="180" y="15">対応するST低下</text></svg>}
function SimpleTrend({label}:{label:string}){return <svg viewBox="0 0 300 75" role="img" aria-label={label}><text x="10" y="18">{label}</text><path d="M5 50 L70 50 L83 10 L96 65 L110 50 L155 50 L180 65 L295 65" className="guide-wave"/></svg>}
function StCriteria(){const regular=elevationThresholdMm("I",null,null),v23=elevationThresholdMm("V2",null,null);return <><p>既存基準：V2–V3以外はJ点で{regular.threshold?.toFixed(1)} mm以上。{v23.reason}。連続する2誘導以上を既存誘導群で評価します。</p><LeadGroups/></>}
function LeadGroups(){return <table><caption>既存Rule Engineの誘導群</caption><tbody>{Object.entries(contiguousLeadGroups).map(([name,ls])=><tr key={name}><th>{name}</th><td>{(ls as string[]).join(" / ")}</td></tr>)}</tbody></table>}
function ReciprocalTable(){return <table><caption>既存Ruleの確認対応</caption><tbody>{reciprocalEducation.map(row=><tr key={row.sourceGroup}><th>{row.sourceGroup}</th><td>{row.elevation.length?`${row.elevation.join(" / ")} ST上昇 → `:""}{row.checkDepression.join(" / ")}を確認</td></tr>)}</tbody></table>}
function numberOrNull(value:string){const n=Number(value);return value!==""&&Number.isFinite(n)?n:null}
function prLabel(value:BradyInput["prPattern"]){return ({normal:"正常",short:"短縮",prolonged_constant:"延長",indeterminate:"未入力／判定困難",not_measurable:"判定困難"} as Record<string,string>)[value]??value}
