"use client";

import { useState } from "react";
import { calculateQtc, QT_CLASSIFICATION_THRESHOLDS_MS } from "@/logic/qt-interpretation/interpret-qt.js";
import { WIDE_QRS_THRESHOLD_MS } from "@/logic/tachyarrhythmia/classify.js";
import type { BradyInput } from "@/types/bradyarrhythmia";
import type { ConductionInput } from "@/types/conduction-interpretation";
import type { QtInterpretationInput } from "@/types/qt-interpretation";

type Props={heartRate:string;brady:BradyInput;conduction:ConductionInput;qt:QtInterpretationInput};
type GuideProps={id:string;number:number;title:string;diagram:React.ReactNode;look:string;measure:string;guide:React.ReactNode;consider:string;prevent:string;target:string};
const navigation=[["rhythm","調律"],["heart-rate","HR"],["axis","軸"],["r-transition","R移行帯"],["p-wave","P"],["pr","PR"],["qrs","QRS"],["st","ST"],["t-wave","T"],["qt","QT"],["u-wave","U"]] as const;
const targetLabels:Record<string,string>={rhythm:"規則性","heart-rate":"心拍数",axis:"電気軸","r-transition":"R波進行","p-wave":"P波",pr:"PR",qrs:"QRS幅・形態",st:"ST変化","t-wave":"T波",qt:"QT測定","u-wave":"U波"};

export function FindingEducationGuide({heartRate,brady,conduction,qt}:Props){
 const [activeGuide,setActiveGuide]=useState<string|null>(null);
 const hr=numberOrNull(heartRate),qtc=calculateQtc(qt.qtMs,qt.rrMs,hr,qt.formula);
 const focusInput=(target:string)=>{const advanced=document.querySelector<HTMLDetailsElement>(".advanced-analysis");if(target==="axis")advanced?.setAttribute("open","");const label=Array.from(document.querySelectorAll<HTMLLabelElement>("label")).find(item=>item.textContent?.trim().startsWith(targetLabels[target]));const control=label?.querySelector<HTMLElement>("input,select");label?.closest<HTMLDetailsElement>("details")?.setAttribute("open","");control?.focus();(control??label)?.scrollIntoView({behavior:"smooth",block:"center"})};
 const openGuide=(id:string)=>{document.querySelectorAll<HTMLDetailsElement>(".finding-guide-item").forEach(item=>{item.open=item.id===`ecg-guide-${id}`});setActiveGuide(id);document.getElementById(`ecg-guide-${id}`)?.scrollIntoView({behavior:"smooth",block:"start"})};
 const items:GuideProps[]=[
  {id:"rhythm",number:1,title:"調律",diagram:<RhythmDiagram/>,look:"まずRR間隔がregularかirregularかを見て、次にP波の有無とP-QRS対応を確認します。",measure:"長めの記録でRRの外れ方と、P波が各QRSへ対応するかを追います。",guide:<p>Key message：<b>まずregular / irregular。そこから外れ方を見る。</b></p>,consider:"既存の洞調律、AF、AV block、AV dissociation入力へつなげます。",prevent:"P波が見えにくい場合はII・V1・V2、長いリズムストリップ、感度を確認します。",target:"rhythm"},
  {id:"heart-rate",number:2,title:"心拍数",diagram:<RhythmDiagram rate/>,look:"一定時間内のQRS数、またはRR間隔を見ます。",measure:`既存HR入力を使用します。現在の入力：${hr==null?"未入力":`${hr} bpm`}`,guide:<p>徐脈・頻脈の判定は既存RuleのSingle Source of Truthを使用し、新しい閾値を追加しません。</p>,consider:"心拍数と症状、調律、QRS幅を合わせて既存徐脈・頻脈経路を評価します。",prevent:"不規則調律では短い区間だけで代表心拍数を断定しません。",target:"heart-rate"},
  {id:"axis",number:3,title:"軸",diagram:<AxisDiagram/>,look:"IとaVFのQRS主方向が陽性か陰性かを見ます。",measure:"I／aVFの組合せを四象限で整理します。",guide:<p>正常軸、左軸偏位、右軸偏位、北西軸を視覚的に整理します。</p>,consider:"軸所見は既存の分枝ブロック・QRS評価と統合します。",prevent:"軸偏位だけで疾患を確定しません。電極装着も確認します。",target:"axis"},
  {id:"r-transition",number:4,title:"R波移行帯",diagram:<RProgressionDiagram/>,look:"V1からV6へR波が増え、S波が減る過程を追います。",measure:"R/Sが入れ替わる位置を比較します。教育上の通常目安はV3～V4付近です。",guide:<p>時計回転、反時計回転、poor R-wave progressionを区別して既存R波進行入力へ戻ります。</p>,consider:"装着位置、脚ブロック、心筋梗塞など既存鑑別を確認します。",prevent:"移行帯だけで病態を確定せず、新しいRule閾値にも使用しません。",target:"r-transition"},
  {id:"p-wave",number:5,title:"P波",diagram:<PWaveDiagram/>,look:"IIとV1を中心に、P波の有無・極性・形を見ます。",measure:"正常P、右房負荷を疑う形、左房負荷を疑う形を比較します。",guide:<p>数値を新しいRule閾値として重複実装せず、既存P波入力を使用します。</p>,consider:"洞調律、AF、房室伝導関係を既存入力で確認します。",prevent:"P波が不明瞭な場合を「なし」へ補完しません。",target:"p-wave"},
  {id:"pr",number:6,title:"PR / PQ間隔",diagram:<MeasureWave start={35} end={82} label="PR"/>,look:"P波開始点からQRS開始点までを見ます。",measure:"一般的目安は0.12～0.20秒。25 mm/sでは1 mm＝40 msです。",guide:<p>現在の入力：<b>{prLabel(brady.prPattern)}</b>。数値目安は教育表示で、既存Ruleの医師入力を置き換えません。</p>,consider:"短い場合はΔ波・pre-excitation、長い場合はAV conduction delay等を既存経路で確認します。",prevent:"Δ波単独でWPW syndromeを確定せず、判定困難を陰性扱いしません。",target:"pr"},
  {id:"qrs",number:7,title:"QRS",diagram:<QrsDiagram/>,look:"幅、形態、電位、R波進行、異常Q波をまとめて見ます。",measure:"QRS開始から終了までを測ります。",guide:<p>既存基準：<b>{WIDE_QRS_THRESHOLD_MS} ms以上をwide</b>。現在：<b>{conduction.qrsDurationMs==null?"未入力":`${conduction.qrsDurationMs} ms`}</b></p>,consider:"RBBB、LBBB、IVCD、低／高電位、pre-excitation、R波進行不良、異常Q波を既存入力・Advanced Modeで確認します。",prevent:"幅や電位だけで疾患を確定せず、wide頻拍は既存安全経路を維持します。",target:"qrs"},
  {id:"st",number:8,title:"ST",diagram:<StThinkingDiagram/>,look:"基線、J点、ST方向と形、誘導分布を見ます。",measure:"通常入力では未入力／変化なし／上昇／低下／両方／判定困難を選び、詳細mm計測はAdvanced Modeで行います。",guide:<p><b>Shape → 誘導分布 → reciprocal → 症状・QRS背景</b>の順で確認します。ST上昇時はconcave、straight、convex、判定困難のオリジナル模式図を使用します。</p>,consider:"急性冠閉塞、早期再分極、心膜炎は教育比較にとどめ、既存急性虚血Ruleだけを使用します。",prevent:"Shape単独で診断しません。concaveでもACSを除外せず、判定困難を正常扱いしません。",target:"st"},
  {id:"t-wave",number:9,title:"T波",diagram:<TWaveDiagram/>,look:"まず年齢・誘導による正常変異でないか確認し、その後に極性、振幅、形を見ます。",measure:"陰性T、高いT、巨大陰性Tなどを誘導分布と合わせて確認します。",guide:<p>正常変異を自動的に異常へ変換せず、既存T波入力と誘導選択を使用します。</p>,consider:"虚血、電解質、二次性ST-T変化、構造的背景を既存Ruleで評価します。",prevent:"T波形だけで疾患を確定せず、QRS背景と前回ECGを確認します。",target:"t-wave"},
  {id:"qt",number:10,title:"QT / QTc",diagram:<MeasureWave start={92} end={255} label="QT"/>,look:"QRS開始点からT波終末までを見て、U波との境界を確認します。",measure:"QTを測り、既存補正式でQTcを算出します。",guide:<p>既存基準：境界域 {QT_CLASSIFICATION_THRESHOLDS_MS.borderlineMin} ms以上、延長 {QT_CLASSIFICATION_THRESHOLDS_MS.prolongedMin} ms以上、著明延長 {QT_CLASSIFICATION_THRESHOLDS_MS.markedProlongationMin} ms以上。現在：<b>QT {qt.qtMs??"未入力"} ms／QTc {qtc??"判定困難"} ms</b></p>,consider:"QT延長時は既存TdP、徐脈・pause、R on T、電解質経路を確認します。",prevent:"T終末不明・U波混入時は測定制限とし、別の閾値を作りません。",target:"qt"},
  {id:"u-wave",number:11,title:"U波",diagram:<UWaveDiagram/>,look:"T波の後に続く小さな波を見ます。",measure:"T終末とU波を区別し、QTではなくQUとなっていないか確認します。",guide:<p>最後にU波を確認し、既存のU波入力を使用します。</p>,consider:"低K、薬剤等を既存electrolyte Ruleの鑑別として確認します。",prevent:"U波単独で診断を確定せず、T波と区別困難なら判定困難とします。",target:"u-wave"}
 ];
 return <details className="finding-education systematic-eleven-guide"><summary aria-label="心電図を順番に読むガイドを開閉">心電図を順番に読む：11項目Guide</summary><div className="systematic-eleven-body"><nav className="systematic-eleven-nav" aria-label="系統的心電図読影11項目">{navigation.map(([id,label],index)=><button type="button" key={id} className={activeGuide===id?"is-current":undefined} aria-current={activeGuide===id?"step":undefined} onClick={()=>openGuide(id)}><span>{index+1}</span>{label}</button>)}</nav><p className="muted">Guideは教育・見落とし防止用です。すべて完了しなくても、入力済み所見だけで59 Rulesを評価できます。</p><div className="finding-guide-list">{items.map(item=><Guide key={item.id} {...item} onFocus={focusInput} onActivate={setActiveGuide}/>)}</div></div></details>;
}

function Guide({id,number,title,diagram,look,measure,guide,consider,prevent,target,onFocus,onActivate}:GuideProps&{onFocus:(target:string)=>void;onActivate:(id:string)=>void}){return <details className="finding-guide-item" id={`ecg-guide-${id}`} onToggle={event=>{if(event.currentTarget.open)onActivate(id)}}><summary><span>{number}</span>{title}</summary><div className="finding-guide-body">{diagram}<GuideRow n="1" title="どこを見る">{look}</GuideRow><GuideRow n="2" title="どう見る / 測る">{measure}</GuideRow><GuideRow n="3" title="正常の目安">{guide}</GuideRow><GuideRow n="4" title="異常なら何を考える">{consider}</GuideRow><GuideRow n="5" title="見落とし防止">{prevent}<br/>迷う場合は判定困難を選び、未入力・判定困難を正常所見として扱いません。</GuideRow><GuideRow n="6" title="この所見を入力する"><button type="button" className="btn" onClick={()=>onFocus(target)}>該当入力へ戻る</button></GuideRow></div></details>}
function GuideRow({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section><h5><span>{n}</span>{title}</h5><div>{children}</div></section>}
function Wave({children}:{children?:React.ReactNode}){return <svg viewBox="0 0 300 92" role="img" aria-label="オリジナル心電図模式図"><line x1="5" y1="55" x2="295" y2="55" className="guide-baseline"/><path d="M5 55 L32 55 Q43 28 55 55 L82 55 L94 68 L108 8 L121 72 L135 55 L205 55 Q230 20 255 55 L270 55 Q280 42 290 55 L295 55" className="guide-wave"/>{children}</svg>}
function MeasureWave({start,end,label}:{start:number;end:number;label:string}){return <Wave><line x1={start} y1="78" x2={end} y2="78" className="guide-measure"/><text x={(start+end)/2-10} y="90">{label}</text></Wave>}
function RhythmDiagram({rate=false}:{rate?:boolean}){return <svg viewBox="0 0 300 92" role="img" aria-label={rate?"心拍数の模式図":"規則性とP-QRS対応の模式図"}><line x1="5" y1="55" x2="295" y2="55" className="guide-baseline"/>{[35,105,175,245].map(x=><path key={x} d={`M${x-18} 55 Q${x-12} 42 ${x-5} 55 L${x} 55 L${x+5} 18 L${x+12} 68 L${x+18} 55`} className="guide-wave"/>)}<text x="12" y="16" fontSize="12">{rate?"RRからHR":"regular → P-QRS対応"}</text></svg>}
function AxisDiagram(){return <svg viewBox="0 0 300 180" role="img" aria-label="IとaVFによる電気軸四象限模式図"><line x1="150" y1="20" x2="150" y2="160" className="guide-baseline"/><line x1="35" y1="90" x2="265" y2="90" className="guide-baseline"/><text x="225" y="84">I＋</text><text x="38" y="84">I−</text><text x="155" y="25">aVF−</text><text x="155" y="158">aVF＋</text><text x="178" y="126">正常軸</text><text x="72" y="126">右軸偏位</text><text x="178" y="55">左軸偏位</text><text x="68" y="55">北西軸</text></svg>}
function RProgressionDiagram(){return <svg viewBox="0 0 360 130" role="img" aria-label="V1からV6のR波移行帯"><text x="5" y="15">R↑ / S↓　transition V3–V4付近</text>{[1,2,3,4,5,6].map((v,i)=>{const x=12+i*58,r=15+i*6,s=44-i*6;return <g key={v}><text x={x+15} y="125">V{v}</text><line x1={x} y1="70" x2={x+48} y2="70" className="guide-baseline"/><path d={`M${x} 70 L${x+18} 70 L${x+23} ${70-r} L${x+28} ${70+s} L${x+34} 70 L${x+48} 70`} className="guide-wave"/></g>})}</svg>}
function PWaveDiagram(){return <svg viewBox="0 0 300 100" role="img" aria-label="IIとV1で確認するP波模式図"><text x="10" y="16">II</text><path d="M10 55 L45 55 Q70 20 95 55 L135 55" className="guide-wave"/><text x="165" y="16">V1</text><path d="M160 55 L190 55 Q210 32 225 55 Q242 75 258 55 L292 55" className="guide-wave"/></svg>}
function QrsDiagram(){return <svg viewBox="0 0 300 100" role="img" aria-label="QRS幅と形態の模式図"><text x="10" y="16">narrow</text><path d="M8 58 L50 58 L60 18 L68 74 L78 58 L130 58" className="guide-wave"/><text x="170" y="16">wide / morphology</text><path d="M160 58 L190 58 L205 20 L230 76 L252 28 L274 58 L295 58" className="guide-wave"/></svg>}
function StThinkingDiagram(){return <svg viewBox="0 0 300 105" role="img" aria-label="ST評価順序の模式図"><path d="M5 58 L62 58 L75 72 L88 12 L100 70 L115 42 Q160 25 205 42 L292 58" className="guide-wave"/><circle cx="115" cy="42" r="4"/><text x="8" y="92" fontSize="12">Shape → distribution → reciprocal → context</text></svg>}
function TWaveDiagram(){return <svg viewBox="0 0 300 100" role="img" aria-label="T波形態の模式図"><path d="M5 60 Q40 22 75 60 M110 60 Q145 92 180 60 M215 60 Q240 8 270 60" className="guide-wave"/><text x="15" y="90">normal variation</text><text x="115" y="90">negative</text><text x="225" y="90">tall</text></svg>}
function UWaveDiagram(){return <Wave><circle cx="280" cy="45" r="12" fill="none" className="guide-measure"/><text x="268" y="22">U</text></Wave>}
function numberOrNull(value:string){const n=Number(value);return value!==""&&Number.isFinite(n)?n:null}
function prLabel(value:BradyInput["prPattern"]){return ({normal:"正常",short:"短縮",prolonged_constant:"延長",indeterminate:"未入力／判定困難",not_measurable:"判定困難"} as Record<string,string>)[value]??value}
