"use client";
import {useRef,useState} from "react";
import {analyzeLocalEcgPoc,recalculateLocalPocRules} from "@/lib/ecg-features/local/local-poc.js";
import type {LocalAnalysisStatus,LocalPocCorrection,LocalPocResult,QrsWidthCandidate,RhythmRegularity,StDirection} from "@/types/local-ecg-poc";

type LayoutChoice="auto"|"three_by_four"|"six_by_two"|"unknown";
type UiStatus=LocalAnalysisStatus|"unsupported"|"failed";
const statusLabels:Record<UiStatus,string>={idle:"待機中",validating_image:"画像品質を確認中",detecting_layout:"心電図配置を確認中",extracting_waveforms:"12誘導の波形候補を抽出中",measuring:"客観的所見候補を計測中",evaluating_rules:"登録済みルールで再評価中",success:"解析完了",unsupported:"自動解析対象外",failed:"解析失敗",cancelled:"解析を中止しました"};

export function LocalEcgPoc({file}:{file:File}){
 const [status,setStatus]=useState<UiStatus>("idle"),[result,setResult]=useState<LocalPocResult|null>(null),[message,setMessage]=useState(""),[layoutType,setLayoutType]=useState<LayoutChoice>("auto");
 const [correction,setCorrection]=useState<LocalPocCorrection>({heartRateBpm:null,rhythmRegularity:"indeterminate",qrsWidthCandidate:"indeterminate",stDirections:[],source:"physician_corrected"});
 const controller=useRef<AbortController|null>(null),busy=!["idle","success","unsupported","failed","cancelled"].includes(status);
 async function run(){controller.current?.abort();controller.current=new AbortController();setResult(null);setMessage("");try{const next=await analyzeLocalEcgPoc(file,{signal:controller.current.signal,onStatus:setStatus,layoutType});setResult(next);setStatus("success");setCorrection({heartRateBpm:next.measurements.heartRateBpm,rhythmRegularity:next.measurements.rhythmRegularity,qrsWidthCandidate:next.measurements.qrsWidthCandidate,stDirections:next.measurements.stDirections,source:"physician_corrected"})}catch(error){if(controller.current.signal.aborted){setStatus("cancelled");return}setStatus(error instanceof Error&&error.name==="UnsupportedImageError"?"unsupported":"failed");setMessage(error instanceof Error?error.message:"ローカル解析に失敗しました。")}}
 function recalculate(){if(!result)return;setStatus("evaluating_rules");const updated=recalculateLocalPocRules(correction,result.imageQuality);setResult({...result,...updated});setStatus("success")}
 function changeLayout(value:LayoutChoice){setLayoutType(value);setResult(null);setMessage("");setStatus("idle")}
 return <section className="local-poc" aria-labelledby="local-poc-title"><header><div><div className="eyebrow">Version 3 PoC</div><h4 id="local-poc-title">最小ローカル自動解析</h4></div><span className="badge">ブラウザ内処理</span></header>
 <p>3行×4列または6行×2列の12誘導画像を対象に、画像品質、心拍数、RR規則性、QRS幅候補、誘導別ST方向候補を推定します。</p>
 <label className="phase-b-layout-select">心電図の配置<select value={layoutType} disabled={busy} onChange={event=>changeLayout(event.target.value as LayoutChoice)}><option value="auto">自動判定</option><option value="three_by_four">3行×4列</option><option value="six_by_two">6行×2列</option><option value="unknown">不明</option></select></label>
 {layoutType==="six_by_two"&&<div className="result"><strong>6行×2列として選択</strong><br/>左列 I・II・III・aVR・aVL・aVF、右列 V1〜V6の12誘導領域候補を生成します。誘導名をOCRで読み取る処理ではありません。</div>}
 <div className="upload-actions"><button className="btn primary-action" type="button" disabled={busy||layoutType==="unknown"} onClick={run}>ローカル解析を開始</button>{busy&&<button className="btn" type="button" onClick={()=>controller.current?.abort()}>解析を中止</button>}</div><div className="analysis-status" role="status" aria-live="polite">{busy&&<span className="analysis-spinner" aria-hidden="true"/>}<strong>{statusLabels[status]}</strong></div>{message&&<div className="result warn" role="alert">{message}</div>}
 {status==="unsupported"&&<div className="upload-actions"><button className="btn" type="button" onClick={()=>document.getElementById("quick-review")?.scrollIntoView({behavior:"smooth"})}>医師入力で続ける</button></div>}
 {status==="success"&&result&&<><div className="clinical-disclaimer"><strong>画像から推定した特徴候補と、登録済みルールに基づく診断支援結果です。</strong><p>自動診断ではありません。すべての候補を医師が原画像で確認し、承認または修正してください。緊急時は本結果を待たず標準診療を優先してください。</p></div><div className="poc-metrics"><Metric label="画像品質" value={result.imageQuality}/><Metric label="レイアウト" value={result.layout}/><Metric label="心拍数候補" value={result.measurements.heartRateBpm==null?"判定困難":`${result.measurements.heartRateBpm} /分`}/><Metric label="RR規則性" value={result.measurements.rhythmRegularity}/><Metric label="QRS候補" value={result.measurements.qrsWidthCandidate}/></div>
 <details><summary>抽出品質と誘導別候補</summary><p>波形抽出: {result.leads.filter(x=>x.quality!=="inadequate").length}/12誘導</p><ul className="list">{result.measurements.stDirections.map(x=><li key={x.lead}>{x.lead}: {x.direction}（品質 {x.quality}）</li>)}</ul></details>
 <fieldset className="poc-correction"><legend>医師確認・修正</legend><label>心拍数<input type="number" min="1" max="300" value={correction.heartRateBpm??""} onChange={e=>setCorrection(x=>({...x,heartRateBpm:e.target.value?Number(e.target.value):null}))}/></label><label>RR規則性<select value={correction.rhythmRegularity} onChange={e=>setCorrection(x=>({...x,rhythmRegularity:e.target.value as RhythmRegularity}))}><option value="regular">規則的</option><option value="regularly_irregular">規則的不整</option><option value="irregularly_irregular">絶対性不整候補</option><option value="indeterminate">判定困難</option></select></label><label>QRS分類<select value={correction.qrsWidthCandidate} onChange={e=>setCorrection(x=>({...x,qrsWidthCandidate:e.target.value as QrsWidthCandidate}))}><option value="narrow">Narrow</option><option value="wide">Wide</option><option value="indeterminate">判定困難</option></select></label><div className="poc-st-grid">{correction.stDirections.map(item=><label key={item.lead}>{item.lead}<select value={item.direction} onChange={e=>setCorrection(x=>({...x,stDirections:x.stDirections.map(y=>y.lead===item.lead?{...y,direction:e.target.value as StDirection}:y)}))}><option value="elevation">上昇候補</option><option value="depression">低下候補</option><option value="isoelectric">等電位候補</option><option value="indeterminate">判定困難</option></select></label>)}</div><button className="btn primary-action" type="button" onClick={recalculate}>修正所見でルールを再計算</button></fieldset><RuleResult result={result}/></>}
 </section>
}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function RuleResult({result}:{result:LocalPocResult}){const x=result.ruleResult;return <section className="poc-rule-results"><h4>57ルールによる結果</h4><p><strong>緊急度:</strong> {x.urgency}</p><h5>見逃してはいけない候補</h5><ul className="list">{x.criticalFindings.length?x.criticalFindings.map(c=><li key={c.id}>{c.label}（{c.ruleIds.join(", ")}）</li>):<li>抽出・承認済み所見から発火した候補なし</li>}</ul><h5>診断候補</h5><ul className="list">{x.diagnosticCandidates.length?x.diagnosticCandidates.map(c=><li key={c.id}><strong>{c.label}</strong> — {c.supportingFindings.map(y=>y.label).join("、")||"理由は詳細解析で確認"} <small>{c.ruleIds.join(", ")}</small></li>):<li>候補なし（未抽出項目は正常ではなく未評価です）</li>}</ul><h5>追加確認・不足情報</h5><ul className="list">{x.missingInformation.slice(0,8).map(i=><li key={i.id}>{i.label}</li>)}</ul><h5>追加検査・初期対応</h5><ul className="list">{x.todaysPlan.slice(0,10).map(i=><li key={i.id}>{i.label}</li>)}</ul>{result.indeterminateFields.length>0&&<p className="muted">未評価: {result.indeterminateFields.join("、")}</p>}</section>}
