"use client";

import { useState, type Dispatch, type SetStateAction } from "react";
import { LeadPlacementGuide } from "@/components/ecg/LeadPlacementGuide";
import { FindingEducationGuide } from "@/components/ecg/FindingEducationGuide";
import type { BradyInput } from "@/types/bradyarrhythmia";
import type { ConductionInput } from "@/types/conduction-interpretation";
import type { QtInterpretationInput } from "@/types/qt-interpretation";
import type { StInterpretationInput, StandardEcgLead } from "@/types/st-interpretation";
import type { TWaveInterpretationInput, TWaveMorphology } from "@/types/t-wave-interpretation";
import type { VentricularEctopyInput } from "@/types/ventricular-ectopy";

const leads:StandardEcgLead[]=["I","II","III","aVR","aVL","aVF","V1","V2","V3","V4","V5","V6"];
const n=(value:string)=>value===""?null:Number(value);
type StReviewChoice=NonNullable<StInterpretationInput["clinicalReviewStatus"]>;
export type ClinicalReviewField="heartRate"|"rhythm"|"pWave"|"pr"|"qrs"|"st"|"tWave"|"qt";
export type ReviewTernary="unentered"|"absent"|"present"|"indeterminate";
export type FindingGuidance={deltaWave:ReviewTernary;rWaveProgression:"unentered"|"normal"|"poor"|"early_tall"|"indeterminate";rOnT:ReviewTernary;digitalisUse:ReviewTernary};

export function SimplifiedClinicalReview({heartRate,setHeartRate,brady,setBrady,conduction,setConduction,st,setSt,tWave,setTWave,qt,setQt,pvc,setPvc,guidance:guidanceProp,setGuidance:setGuidanceProp,placementWarning,setPlacementWarning,onFieldReviewed,onRecalculate}:{
  heartRate:string;setHeartRate:(value:string)=>void;
  brady:BradyInput;setBrady:Dispatch<SetStateAction<BradyInput>>;
  conduction:ConductionInput;setConduction:Dispatch<SetStateAction<ConductionInput>>;
  st:StInterpretationInput;setSt:Dispatch<SetStateAction<StInterpretationInput>>;
  tWave:TWaveInterpretationInput;setTWave:Dispatch<SetStateAction<TWaveInterpretationInput>>;
  qt:QtInterpretationInput;setQt:Dispatch<SetStateAction<QtInterpretationInput>>;
  pvc:VentricularEctopyInput&{clinicianConfirmed?:boolean};setPvc:Dispatch<SetStateAction<VentricularEctopyInput&{clinicianConfirmed?:boolean}>>;
  guidance?:FindingGuidance;setGuidance?:Dispatch<SetStateAction<FindingGuidance>>;
  placementWarning:boolean;setPlacementWarning:(value:boolean)=>void;onFieldReviewed:(field:ClinicalReviewField)=>void;onRecalculate:()=>void;
}){
  const [localGuidance,setLocalGuidance]=useState<FindingGuidance>({deltaWave:"unentered",rWaveProgression:"unentered",rOnT:"unentered",digitalisUse:"unentered"});
  const guidance=guidanceProp??localGuidance;
  const setGuidance:Dispatch<SetStateAction<FindingGuidance>>=value=>{const next=typeof value==="function"?value(guidance):value;(setGuidanceProp??setLocalGuidance)(next);window.dispatchEvent(new CustomEvent("ecg-finding-guidance",{detail:next}))};
  const stChoice:StReviewChoice=st.clinicalReviewStatus??"unentered";
  const tMorph=tWave.leadMeasurements.find(x=>x.clinicianConfirmed&&x.morphology!=="normal")?.morphology??(tWave.leadMeasurements.some(x=>x.clinicianConfirmed&&x.morphology==="normal")?"normal":"indeterminate");
  const setStChoice=(choice:StReviewChoice)=>{onFieldReviewed("st");setSt(current=>({...current,clinicalReviewStatus:choice,leadMeasurements:current.leadMeasurements.map(x=>({...x,direction:choice==="none"?"isoelectric":"indeterminate",amplitudeMm:null,amplitudeMv:null,measurementPoint:"unknown",baselineReference:"uncertain",clinicianConfirmed:choice==="none"}))}))};
  const setLeadSt=(direction:"elevation"|"depression",lead:StandardEcgLead,checked:boolean)=>setSt(current=>({...current,leadMeasurements:current.leadMeasurements.map(x=>x.lead===lead?{...x,direction:checked?direction:"indeterminate",amplitudeMm:null,amplitudeMv:null,measurementPoint:"unknown",baselineReference:"uncertain",clinicianConfirmed:checked}:x)}));
  const setAllT=(morphology:TWaveMorphology)=>{onFieldReviewed("tWave");setTWave(current=>({...current,leadMeasurements:current.leadMeasurements.map(x=>({...x,morphology,clinicianConfirmed:morphology!=="indeterminate"}))}))};
  const setLeadT=(lead:StandardEcgLead,checked:boolean)=>setTWave(current=>({...current,leadMeasurements:current.leadMeasurements.map(x=>x.lead===lead?{...x,morphology:checked?tMorph:"indeterminate",clinicianConfirmed:checked}:x)}));
  const qrsChoice=conduction.clinicianClassification==="indeterminate"?"indeterminate":conduction.clinicianClassification==="rbbb_candidate"?"rbbb":conduction.clinicianClassification==="lbbb_candidate"?"lbbb":conduction.qrsDurationMs==null?"unknown":conduction.qrsDurationMs>=120?"wide":"narrow";
  const setQrs=(value:string)=>{onFieldReviewed("qrs");setConduction(current=>({...current,qrsDurationMs:value==="narrow"?100:value==="wide"||value==="rbbb"||value==="lbbb"?140:null,clinicianClassification:value==="rbbb"?"rbbb_candidate":value==="lbbb"?"lbbb_candidate":value==="indeterminate"?"indeterminate":"auto",clinicianConfirmed:value!=="unknown"}))};
  const setRonT=(value:ReviewTernary)=>{setGuidance(x=>({...x,rOnT:value}));setPvc(x=>({...x,finding:{...x.finding,timing:value==="present"?"r_on_t_candidate":value==="absent"?"mid_diastolic":"indeterminate",clinicianConfirmed:value==="present"||value==="absent"}}));setQt(x=>({...x,rOnT:value==="present"}))};
  return <div className="compact-clinical-review">
    <ReviewSection code="A" title="心拍数・リズム">
      <div className="compact-input-grid"><label>心拍数（bpm）<input type="number" value={heartRate} placeholder="未入力" onChange={e=>{onFieldReviewed("heartRate");setHeartRate(e.target.value)}}/></label><label>規則性<select value={brady.rateRegularity} onChange={e=>{onFieldReviewed("rhythm");setBrady(x=>({...x,rateRegularity:e.target.value as BradyInput["rateRegularity"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="regular">規則的</option><option value="regularly_irregular">規則的不整</option><option value="irregular">不規則</option></select></label><label>洞調律<select value={brady.sinusMorphology} onChange={e=>setBrady(x=>({...x,sinusMorphology:e.target.value as BradyInput["sinusMorphology"]}))}><option value="uncertain">未入力／不明</option><option value="sinus">洞調律</option><option value="non_sinus">非洞調律</option></select></label><label className="check"><input type="checkbox" checked={brady.atrialFibrillation} onChange={e=>setBrady(x=>({...x,atrialFibrillation:e.target.checked}))}/>AF疑い</label></div>
      {(n(heartRate)!==null&&n(heartRate)!<50)&&<details><summary>徐脈の詳細を確認</summary><div className="compact-input-grid"><label>P波とQRSの関係<select value={brady.pToQrsRelationship} onChange={e=>setBrady(x=>({...x,pToQrsRelationship:e.target.value as BradyInput["pToQrsRelationship"]}))}><option value="indeterminate">判定困難</option><option value="one_to_one">1:1</option><option value="two_to_one">2:1</option><option value="variable_conduction">変動</option><option value="av_dissociation">房室解離</option></select></label><label>補充調律<select value={brady.escapeRhythm} onChange={e=>setBrady(x=>({...x,escapeRhythm:e.target.value as BradyInput["escapeRhythm"]}))}><option value="indeterminate">判定困難</option><option value="none">なし</option><option value="junctional_escape">接合部</option><option value="ventricular_escape">心室性</option></select></label></div></details>}
    </ReviewSection>
    <ReviewSection code="B" title="P波・PR"><div className="compact-input-grid"><label>P波<select value={brady.pWavePresence} onChange={e=>{onFieldReviewed("pWave");setBrady(x=>({...x,pWavePresence:e.target.value as BradyInput["pWavePresence"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="present">あり</option><option value="absent">なし</option><option value="intermittent">間欠的</option><option value="hidden">QRS/T内</option></select></label><label>PR<select value={brady.prPattern} onChange={e=>{onFieldReviewed("pr");setBrady(x=>({...x,prPattern:e.target.value as BradyInput["prPattern"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="normal">正常</option><option value="prolonged_constant">延長</option><option value="short">短縮</option><option value="not_measurable">判定困難</option></select></label></div></ReviewSection>
    <ReviewSection code="C" title="QRS"><div className="compact-input-grid"><label>QRS幅・形態<select value={qrsChoice} onChange={e=>setQrs(e.target.value)}><option value="unknown">未入力</option><option value="narrow">narrow</option><option value="wide">wide</option><option value="rbbb">RBBB候補</option><option value="lbbb">LBBB候補</option><option value="indeterminate">判定困難</option></select></label>{["wide","rbbb","lbbb"].includes(qrsChoice)&&<label>QRS幅（ms）<input type="number" value={conduction.qrsDurationMs??""} onChange={e=>setConduction(x=>({...x,qrsDurationMs:n(e.target.value)}))}/></label>}</div></ReviewSection>
    <ReviewSection code="D" title="ST"><div className="compact-input-grid"><label>ST変化<select value={stChoice} onChange={e=>setStChoice(e.target.value as StReviewChoice)}><option value="unentered">未入力</option><option value="elevation">明らかなST上昇あり</option><option value="depression">明らかなST低下あり</option><option value="mixed">上昇と低下の両方あり</option><option value="none">明らかなST変化なし</option><option value="indeterminate">判定困難</option></select></label></div><p className="muted">ST判定が難しい場合は「判定困難」を選択してください。無理に正常／異常を決める必要はありません。</p><details className="inline-info"><summary>ST判定について</summary><p className="muted">ST上昇はJ点と基線の評価が必要で、誘導や年齢・性別によって基準が異なります。</p></details>{(stChoice==="elevation"||stChoice==="mixed")&&<LeadPicker label="ST上昇が明らかな誘導" selected={st.leadMeasurements.filter(x=>x.clinicianConfirmed&&x.direction==="elevation").map(x=>x.lead)} onChange={(lead,checked)=>setLeadSt("elevation",lead,checked)}/>} {(stChoice==="depression"||stChoice==="mixed")&&<LeadPicker label="ST低下が明らかな誘導" selected={st.leadMeasurements.filter(x=>x.clinicianConfirmed&&x.direction==="depression").map(x=>x.lead)} onChange={(lead,checked)=>setLeadSt("depression",lead,checked)}/>}</ReviewSection>
    <ReviewSection code="E" title="T波"><div className="compact-input-grid"><label>T波<select value={tMorph} onChange={e=>setAllT(e.target.value as TWaveMorphology)}><option value="indeterminate">未入力／判定困難</option><option value="normal">正常</option><option value="inverted">陰性T</option><option value="peaked">尖鋭T</option><option value="flattened">平低化</option><option value="biphasic">二相性</option><option value="giant_negative">巨大陰性T</option></select></label></div>{!['normal','indeterminate'].includes(tMorph)&&<LeadPicker label="該当誘導" selected={tWave.leadMeasurements.filter(x=>x.clinicianConfirmed&&x.morphology===tMorph).map(x=>x.lead)} onChange={setLeadT}/>}</ReviewSection>
    <ReviewSection code="F" title="QT / QTc"><div className="compact-input-grid"><label>QT測定<select value={qt.measurementStatus} onChange={e=>{onFieldReviewed("qt");setQt(x=>({...x,measurementStatus:e.target.value as QtInterpretationInput["measurementStatus"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="measurable">測定可能</option><option value="u_wave_overlap">U波との境界不明</option></select></label><label>QT（ms）<input type="number" value={qt.qtMs??""} placeholder="未入力" onChange={e=>{onFieldReviewed("qt");setQt(x=>({...x,qtMs:n(e.target.value)}))}}/></label><label>QTc実測値（ms）<input type="number" value={qt.clinicianQtcMs??""} placeholder="未入力" onChange={e=>{onFieldReviewed("qt");setQt(x=>({...x,clinicianQtcMs:n(e.target.value)}))}}/></label></div></ReviewSection>
    <ReviewSection code="G" title="その他の重要所見・臨床情報"><div className="compact-input-grid"><label>PVC<select value={pvc.clinicianClassification==="pvc"?"present":pvc.clinicianClassification==="none"?"absent":pvc.clinicianConfirmed?"indeterminate":"unentered"} onChange={e=>{const value=e.target.value;setPvc(x=>({...x,clinicianClassification:value==="present"?"pvc":value==="absent"?"none":"indeterminate",clinicianConfirmed:value!=="unentered"}))}}><option value="unentered">未入力</option><option value="absent">なし</option><option value="present">あり</option><option value="indeterminate">判定困難</option></select></label><label>失神／一過性意識消失<select value={brady.adverseSigns.syncope===true?"present":brady.adverseSigns.syncope===false?"absent":"unentered"} onChange={e=>{const value=e.target.value;setBrady(x=>({...x,adverseSigns:{...x.adverseSigns,syncope:value==="present"?true:value==="absent"?false:null}}));setQt(x=>({...x,syncope:value==="present"}))}}><option value="unentered">未入力</option><option value="absent">なし</option><option value="present">あり</option></select></label></div><div className="compact-check-grid"><label className="check"><input type="checkbox" checked={tWave.clinical.uWavePresent} onChange={e=>setTWave(x=>({...x,clinical:{...x.clinical,uWavePresent:e.target.checked}}))}/>U波</label><label className="check"><input type="checkbox" checked={tWave.clinical.pathologicQWaves} onChange={e=>setTWave(x=>({...x,clinical:{...x.clinical,pathologicQWaves:e.target.checked}}))}/>異常Q波</label><label className="check"><input type="checkbox" checked={brady.adverseSigns.ischemicChestDiscomfort===true} onChange={e=>setBrady(x=>({...x,adverseSigns:{...x.adverseSigns,ischemicChestDiscomfort:e.target.checked}}))}/>胸痛</label><label className="check"><input type="checkbox" checked={tWave.clinical.dyspnea} onChange={e=>setTWave(x=>({...x,clinical:{...x.clinical,dyspnea:e.target.checked}}))}/>呼吸困難</label></div><label>電極装着<select value={placementWarning?"concern":"unknown"} onChange={e=>setPlacementWarning(e.target.value==="concern")}><option value="unknown">未入力／不明</option><option value="normal">問題なし</option><option value="concern">装着異常・逆接続疑い</option></select></label>{placementWarning&&<details open><summary>電極装着の詳細確認</summary><LeadPlacementGuide onWarningChange={setPlacementWarning}/></details>}</ReviewSection>
    <div className="finding-guidance-grid" aria-label="追加の見落とし防止所見">
      <label>Δ波／心室早期興奮<select value={guidance.deltaWave} onChange={e=>setGuidance(x=>({...x,deltaWave:e.target.value as ReviewTernary}))}><option value="unentered">未入力</option><option value="absent">なし</option><option value="present">あり</option><option value="indeterminate">判定困難</option></select></label>
      <label>R波進行<select value={guidance.rWaveProgression} onChange={e=>setGuidance(x=>({...x,rWaveProgression:e.target.value as FindingGuidance["rWaveProgression"]}))}><option value="unentered">未入力</option><option value="normal">概ね正常</option><option value="poor">poor R-wave progression</option><option value="early_tall">V1～V3で早期から高いR波</option><option value="indeterminate">判定困難</option></select></label>
      <label>R on T<select value={guidance.rOnT} onChange={e=>setRonT(e.target.value as ReviewTernary)}><option value="unentered">未入力</option><option value="absent">なし</option><option value="present">あり</option><option value="indeterminate">判定困難</option></select></label>
      <label>digitalis使用<select value={guidance.digitalisUse} onChange={e=>setGuidance(x=>({...x,digitalisUse:e.target.value as ReviewTernary}))}><option value="unentered">未入力</option><option value="absent">なし</option><option value="present">あり</option><option value="indeterminate">不明</option></select></label>
    </div>
    <details className="finding-education legacy-finding-education"><summary aria-label="心電図所見の見方を開閉">見方 ?：心電図所見の模式図</summary><div className="education-diagram-grid">
      <MiniDiagram title="P-QRS-ST-T-U基本" path="M5 50 L35 50 Q45 25 55 50 L85 50 L95 65 L108 8 L120 70 L132 50 L175 50 Q195 20 215 50 L245 50 Q255 38 265 50 L295 50"/>
      <MiniDiagram title="PR・QRS・ST・QT" path="M5 50 L35 50 Q45 28 55 50 L82 50 L94 65 L108 8 L121 70 L135 50 L205 50 Q230 22 255 50 L295 50"/>
      <MiniDiagram title="Δ波" path="M5 55 L60 55 Q78 48 92 30 L105 8 L118 67 L135 55 L295 55"/>
      <MiniDiagram title="R on T" path="M5 55 L70 55 Q100 18 130 55 L145 55 L155 68 L168 5 L180 70 L195 55 L295 55"/>
      <MiniDiagram title="J点・基線・ST" path="M5 55 L80 55 L92 68 L105 8 L118 70 L135 55 L225 35 L295 35"/>
      <MiniDiagram title="R波進行" path="M5 60 L20 20 L35 60 L55 60 L75 15 L90 60 L110 60 L135 10 L150 60 L175 60 L205 5 L220 60 L245 60 L280 3 L295 60"/>
      <MiniDiagram title="後壁鏡像変化" path="M5 45 L55 45 L70 65 L85 10 L100 68 L118 45 L160 45 L175 25 L190 75 L205 25 L220 45 L295 45"/>
      <MiniDiagram title="LBBB二次性ST-T" path="M5 50 L55 50 L70 20 L95 70 L125 15 L150 55 L205 55 Q240 85 275 55 L295 55"/>
      <MiniDiagram title="reciprocal change" path="M5 50 L60 50 L75 10 L90 65 L110 30 L145 30 M155 50 L210 50 L225 90 L240 35 L260 70 L295 70"/>
    </div><p>R on TはPVCが先行拍のT波終末付近へ重なる所見です。誘導分布、装着位置、前回心電図も合わせて確認します。</p></details>
    <FindingEducationGuide heartRate={heartRate} brady={brady} conduction={conduction} qt={qt}/>
    {qrsChoice==="lbbb"&&<aside className="clinical-warning"><strong>LBBBでは通常のST評価が困難です。</strong><p>二次性ST-T変化を伴うため、虚血症状がある場合は詳細解析のSgarbossa／modified Sgarbossa評価も確認してください。</p></aside>}
    {pvc.clinicianClassification==="pvc"&&["unentered","indeterminate"].includes(guidance.rOnT)&&<p className="clinical-warning">PVCが先行するT波上またはT波終末付近へ重なっていないか確認してください。</p>}
    <button className="btn primary-action" type="button" onClick={onRecalculate}>解析する</button>
    <p className="muted">未入力項目はunknownとして扱い、正常所見へ補完しません。不足情報は結果画面で追加確認として表示します。</p>
  </div>;
}

function ReviewSection({code,title,children}:{code:string;title:string;children:React.ReactNode}){return <section className="compact-review-section"><header><span>{code}</span><h4>{title}</h4></header>{children}</section>}
function MiniDiagram({title,path}:{title:string;path:string}){return <figure><figcaption>{title}</figcaption><svg viewBox="0 0 300 80" role="img" aria-label={`${title}のオリジナル模式図`}><path d={path} fill="none" stroke="currentColor" strokeWidth="3"/><line x1="5" y1="50" x2="295" y2="50" stroke="#57e6ff" strokeWidth="1" strokeDasharray="4 4"/></svg></figure>}
function LeadPicker({label,selected,onChange}:{label:string;selected:string[];onChange:(lead:StandardEcgLead,checked:boolean)=>void}){return <fieldset className="compact-lead-picker"><legend>{label}</legend>{leads.map(lead=><label className="check" key={lead}><input type="checkbox" checked={selected.includes(lead)} onChange={e=>onChange(lead,e.target.checked)}/>{lead}</label>)}</fieldset>}
