"use client";

import type { Dispatch, SetStateAction } from "react";
import { LeadPlacementGuide } from "@/components/ecg/LeadPlacementGuide";
import type { BradyInput } from "@/types/bradyarrhythmia";
import type { ConductionInput } from "@/types/conduction-interpretation";
import type { QtInterpretationInput } from "@/types/qt-interpretation";
import type { StInterpretationInput, StandardEcgLead } from "@/types/st-interpretation";
import type { TWaveInterpretationInput, TWaveMorphology } from "@/types/t-wave-interpretation";
import type { VentricularEctopyInput } from "@/types/ventricular-ectopy";

const leads:StandardEcgLead[]=["I","II","III","aVR","aVL","aVF","V1","V2","V3","V4","V5","V6"];
const n=(value:string)=>value===""?null:Number(value);
type StReviewChoice=NonNullable<StInterpretationInput["clinicalReviewStatus"]>;
export type ClinicalReviewField="heartRate"|"rhythm"|"pWave"|"pr"|"qrs"|"st"|"tWave"|"qt";

export function SimplifiedClinicalReview({heartRate,setHeartRate,brady,setBrady,conduction,setConduction,st,setSt,tWave,setTWave,qt,setQt,pvc,setPvc,placementWarning,setPlacementWarning,onFieldReviewed,onRecalculate}:{
  heartRate:string;setHeartRate:(value:string)=>void;
  brady:BradyInput;setBrady:Dispatch<SetStateAction<BradyInput>>;
  conduction:ConductionInput;setConduction:Dispatch<SetStateAction<ConductionInput>>;
  st:StInterpretationInput;setSt:Dispatch<SetStateAction<StInterpretationInput>>;
  tWave:TWaveInterpretationInput;setTWave:Dispatch<SetStateAction<TWaveInterpretationInput>>;
  qt:QtInterpretationInput;setQt:Dispatch<SetStateAction<QtInterpretationInput>>;
  pvc:VentricularEctopyInput;setPvc:Dispatch<SetStateAction<VentricularEctopyInput>>;
  placementWarning:boolean;setPlacementWarning:(value:boolean)=>void;onFieldReviewed:(field:ClinicalReviewField)=>void;onRecalculate:()=>void;
}){
  const stChoice:StReviewChoice=st.clinicalReviewStatus??"unentered";
  const tMorph=tWave.leadMeasurements.find(x=>x.clinicianConfirmed&&x.morphology!=="normal")?.morphology??(tWave.leadMeasurements.some(x=>x.clinicianConfirmed&&x.morphology==="normal")?"normal":"indeterminate");
  const setStChoice=(choice:StReviewChoice)=>{onFieldReviewed("st");setSt(current=>({...current,clinicalReviewStatus:choice,leadMeasurements:current.leadMeasurements.map(x=>({...x,direction:choice==="none"?"isoelectric":"indeterminate",amplitudeMm:null,amplitudeMv:null,measurementPoint:"unknown",baselineReference:"uncertain",clinicianConfirmed:choice==="none"}))}))};
  const setLeadSt=(direction:"elevation"|"depression",lead:StandardEcgLead,checked:boolean)=>setSt(current=>({...current,leadMeasurements:current.leadMeasurements.map(x=>x.lead===lead?{...x,direction:checked?direction:"indeterminate",amplitudeMm:null,amplitudeMv:null,measurementPoint:"unknown",baselineReference:"uncertain",clinicianConfirmed:checked}:x)}));
  const setAllT=(morphology:TWaveMorphology)=>{onFieldReviewed("tWave");setTWave(current=>({...current,leadMeasurements:current.leadMeasurements.map(x=>({...x,morphology,clinicianConfirmed:morphology!=="indeterminate"}))}))};
  const setLeadT=(lead:StandardEcgLead,checked:boolean)=>setTWave(current=>({...current,leadMeasurements:current.leadMeasurements.map(x=>x.lead===lead?{...x,morphology:checked?tMorph:"indeterminate",clinicianConfirmed:checked}:x)}));
  const qrsChoice=conduction.clinicianClassification==="indeterminate"?"indeterminate":conduction.clinicianClassification==="rbbb_candidate"?"rbbb":conduction.clinicianClassification==="lbbb_candidate"?"lbbb":conduction.qrsDurationMs==null?"unknown":conduction.qrsDurationMs>=120?"wide":"narrow";
  const setQrs=(value:string)=>{onFieldReviewed("qrs");setConduction(current=>({...current,qrsDurationMs:value==="narrow"?100:value==="wide"||value==="rbbb"||value==="lbbb"?140:null,clinicianClassification:value==="rbbb"?"rbbb_candidate":value==="lbbb"?"lbbb_candidate":value==="indeterminate"?"indeterminate":"auto",clinicianConfirmed:value!=="unknown"}))};
  return <div className="compact-clinical-review">
    <ReviewSection code="A" title="心拍数・リズム">
      <div className="compact-input-grid"><label>心拍数（bpm）<input type="number" value={heartRate} placeholder="未入力" onChange={e=>{onFieldReviewed("heartRate");setHeartRate(e.target.value)}}/></label><label>規則性<select value={brady.rateRegularity} onChange={e=>{onFieldReviewed("rhythm");setBrady(x=>({...x,rateRegularity:e.target.value as BradyInput["rateRegularity"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="regular">規則的</option><option value="regularly_irregular">規則的不整</option><option value="irregular">不規則</option></select></label><label>洞調律<select value={brady.sinusMorphology} onChange={e=>setBrady(x=>({...x,sinusMorphology:e.target.value as BradyInput["sinusMorphology"]}))}><option value="uncertain">未入力／不明</option><option value="sinus">洞調律</option><option value="non_sinus">非洞調律</option></select></label><label className="check"><input type="checkbox" checked={brady.atrialFibrillation} onChange={e=>setBrady(x=>({...x,atrialFibrillation:e.target.checked}))}/>AF疑い</label></div>
      {(n(heartRate)!==null&&n(heartRate)!<50)&&<details><summary>徐脈の詳細を確認</summary><div className="compact-input-grid"><label>P波とQRSの関係<select value={brady.pToQrsRelationship} onChange={e=>setBrady(x=>({...x,pToQrsRelationship:e.target.value as BradyInput["pToQrsRelationship"]}))}><option value="indeterminate">判定困難</option><option value="one_to_one">1:1</option><option value="two_to_one">2:1</option><option value="variable_conduction">変動</option><option value="av_dissociation">房室解離</option></select></label><label>補充調律<select value={brady.escapeRhythm} onChange={e=>setBrady(x=>({...x,escapeRhythm:e.target.value as BradyInput["escapeRhythm"]}))}><option value="indeterminate">判定困難</option><option value="none">なし</option><option value="junctional_escape">接合部</option><option value="ventricular_escape">心室性</option></select></label></div></details>}
    </ReviewSection>
    <ReviewSection code="B" title="P波・PR"><div className="compact-input-grid"><label>P波<select value={brady.pWavePresence} onChange={e=>{onFieldReviewed("pWave");setBrady(x=>({...x,pWavePresence:e.target.value as BradyInput["pWavePresence"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="present">あり</option><option value="absent">なし</option><option value="intermittent">間欠的</option><option value="hidden">QRS/T内</option></select></label><label>PR<select value={brady.prPattern} onChange={e=>{onFieldReviewed("pr");setBrady(x=>({...x,prPattern:e.target.value as BradyInput["prPattern"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="normal">正常</option><option value="prolonged_constant">延長</option><option value="progressive_prolongation">進行性延長</option><option value="not_measurable">測定不能</option></select></label></div></ReviewSection>
    <ReviewSection code="C" title="QRS"><div className="compact-input-grid"><label>QRS幅・形態<select value={qrsChoice} onChange={e=>setQrs(e.target.value)}><option value="unknown">未入力</option><option value="narrow">narrow</option><option value="wide">wide</option><option value="rbbb">RBBB候補</option><option value="lbbb">LBBB候補</option><option value="indeterminate">判定困難</option></select></label>{["wide","rbbb","lbbb"].includes(qrsChoice)&&<label>QRS幅（ms）<input type="number" value={conduction.qrsDurationMs??""} onChange={e=>setConduction(x=>({...x,qrsDurationMs:n(e.target.value)}))}/></label>}</div></ReviewSection>
    <ReviewSection code="D" title="ST"><div className="compact-input-grid"><label>ST変化<select value={stChoice} onChange={e=>setStChoice(e.target.value as StReviewChoice)}><option value="unentered">未入力</option><option value="elevation">明らかなST上昇あり</option><option value="depression">明らかなST低下あり</option><option value="mixed">上昇と低下の両方あり</option><option value="none">明らかなST変化なし</option><option value="indeterminate">判定困難</option></select></label></div><p className="muted">ST判定が難しい場合は「判定困難」を選択してください。無理に正常／異常を決める必要はありません。</p><details className="inline-info"><summary>ST判定について</summary><p className="muted">ST上昇はJ点と基線の評価が必要で、誘導や年齢・性別によって基準が異なります。</p></details>{(stChoice==="elevation"||stChoice==="mixed")&&<LeadPicker label="ST上昇が明らかな誘導" selected={st.leadMeasurements.filter(x=>x.clinicianConfirmed&&x.direction==="elevation").map(x=>x.lead)} onChange={(lead,checked)=>setLeadSt("elevation",lead,checked)}/>} {(stChoice==="depression"||stChoice==="mixed")&&<LeadPicker label="ST低下が明らかな誘導" selected={st.leadMeasurements.filter(x=>x.clinicianConfirmed&&x.direction==="depression").map(x=>x.lead)} onChange={(lead,checked)=>setLeadSt("depression",lead,checked)}/>}</ReviewSection>
    <ReviewSection code="E" title="T波"><div className="compact-input-grid"><label>T波<select value={tMorph} onChange={e=>setAllT(e.target.value as TWaveMorphology)}><option value="indeterminate">未入力／判定困難</option><option value="normal">正常</option><option value="inverted">陰性T</option><option value="peaked">尖鋭T</option><option value="flattened">平低化</option><option value="biphasic">二相性</option><option value="giant_negative">巨大陰性T</option></select></label></div>{!['normal','indeterminate'].includes(tMorph)&&<LeadPicker label="該当誘導" selected={tWave.leadMeasurements.filter(x=>x.clinicianConfirmed&&x.morphology===tMorph).map(x=>x.lead)} onChange={setLeadT}/>}</ReviewSection>
    <ReviewSection code="F" title="QT / QTc"><div className="compact-input-grid"><label>QT測定<select value={qt.measurementStatus} onChange={e=>{onFieldReviewed("qt");setQt(x=>({...x,measurementStatus:e.target.value as QtInterpretationInput["measurementStatus"]}))}}><option value="indeterminate">未入力／判定困難</option><option value="measurable">測定可能</option><option value="u_wave_overlap">U波との境界不明</option></select></label><label>QT（ms）<input type="number" value={qt.qtMs??""} placeholder="未入力" onChange={e=>{onFieldReviewed("qt");setQt(x=>({...x,qtMs:n(e.target.value)}))}}/></label></div></ReviewSection>
    <ReviewSection code="G" title="その他の重要所見・臨床情報"><div className="compact-check-grid"><label className="check"><input type="checkbox" checked={pvc.clinicianClassification==="pvc"} onChange={e=>setPvc(x=>({...x,clinicianClassification:e.target.checked?"pvc":"indeterminate"}))}/>PVC</label><label className="check"><input type="checkbox" checked={pvc.finding.timing==="r_on_t_candidate"} onChange={e=>setPvc(x=>({...x,finding:{...x.finding,timing:e.target.checked?"r_on_t_candidate":"indeterminate"}}))}/>R on T</label><label className="check"><input type="checkbox" checked={tWave.clinical.uWavePresent} onChange={e=>setTWave(x=>({...x,clinical:{...x.clinical,uWavePresent:e.target.checked}}))}/>U波</label><label className="check"><input type="checkbox" checked={tWave.clinical.pathologicQWaves} onChange={e=>setTWave(x=>({...x,clinical:{...x.clinical,pathologicQWaves:e.target.checked}}))}/>異常Q波</label><label className="check"><input type="checkbox" checked={brady.adverseSigns.ischemicChestDiscomfort===true} onChange={e=>setBrady(x=>({...x,adverseSigns:{...x.adverseSigns,ischemicChestDiscomfort:e.target.checked}}))}/>胸痛</label><label className="check"><input type="checkbox" checked={tWave.clinical.dyspnea} onChange={e=>setTWave(x=>({...x,clinical:{...x.clinical,dyspnea:e.target.checked}}))}/>呼吸困難</label></div><label>電極装着<select value={placementWarning?"concern":"unknown"} onChange={e=>setPlacementWarning(e.target.value==="concern")}><option value="unknown">未入力／不明</option><option value="normal">問題なし</option><option value="concern">装着異常・逆接続疑い</option></select></label>{placementWarning&&<details open><summary>電極装着の詳細確認</summary><LeadPlacementGuide onWarningChange={setPlacementWarning}/></details>}</ReviewSection>
    <button className="btn primary-action" type="button" onClick={onRecalculate}>解析する</button>
    <p className="muted">未入力項目はunknownとして扱い、正常所見へ補完しません。不足情報は結果画面で追加確認として表示します。</p>
  </div>;
}

function ReviewSection({code,title,children}:{code:string;title:string;children:React.ReactNode}){return <section className="compact-review-section"><header><span>{code}</span><h4>{title}</h4></header>{children}</section>}
function LeadPicker({label,selected,onChange}:{label:string;selected:string[];onChange:(lead:StandardEcgLead,checked:boolean)=>void}){return <fieldset className="compact-lead-picker"><legend>{label}</legend>{leads.map(lead=><label className="check" key={lead}><input type="checkbox" checked={selected.includes(lead)} onChange={e=>onChange(lead,e.target.checked)}/>{lead}</label>)}</fieldset>}
