import {bradyEvidenceSources,bradySources} from "../../data/bradyarrhythmia/sources.js";

export function interpretBradyarrhythmia(input){
  const adverse=Object.entries(input.adverseSigns).filter(([,v])=>v===true).map(([k])=>k);const adverseUnknown=Object.values(input.adverseSigns).some(v=>v==null);
  const hemodynamicStatus=adverse.length?"unstable":adverseUnknown?"indeterminate":input.adverseSigns.presyncope?"potentially_unstable":"stable";
  const slow=valid(input.ventricularRateBpm)?input.ventricularRateBpm<60:null;const clinicallyRelevantBradycardia=slow==null?"indeterminate":!slow?"absent":adverse.length||input.symptomCorrelation==="recorded_during_symptoms"?"present":input.athlete||input.sleeping?"context_dependent":"present";
  let classification="no_bradycardia";if(input.artifactConcern||slow==null||input.pWavePresence==="indeterminate")classification="indeterminate";else if(input.atrialFibrillation&&slow)classification="af_slow_ventricular_response";else if(input.pToQrsRelationship==="av_dissociation"&&valid(input.atrialRateBpm)&&valid(input.ventricularRateBpm)&&input.atrialRateBpm>input.ventricularRateBpm&&slow)classification="complete_av_block_candidate";else if(input.pToQrsRelationship==="av_dissociation")classification="av_dissociation_uncertain";else if(input.multipleNonconductedP)classification="high_grade_av_block_candidate";else if(input.pToQrsRelationship==="two_to_one")classification="two_to_one_av_block";else if(input.droppedQrs&&input.prPattern==="progressive_prolongation")classification="mobitz_i_candidate";else if(input.droppedQrs&&input.prPattern==="constant_before_dropped_qrs"&&!input.pacBlockedByPrematureAtrialBeat)classification="mobitz_ii_candidate";else if(input.pToQrsRelationship==="one_to_one"&&input.prPattern==="prolonged_constant")classification="first_degree_av_block";else if(input.pausePresent&&input.expectedPWaveMissing&&input.pauseMultipleOfBaselinePp==="yes")classification="sinoatrial_block_candidate";else if(input.pausePresent&&input.expectedPWaveMissing)classification="sinus_pause_candidate";else if(slow&&input.sinusMorphology==="sinus"&&input.pToQrsRelationship==="one_to_one")classification=input.athlete||input.sleeping?"physiologic_sinus_bradycardia_candidate":"sinus_bradycardia_candidate";else if(slow)classification="sinus_node_dysfunction_candidate";
  if(input.clinicianClassification!=="auto")classification=input.clinicianClassification;
  const redFlags=[];if(slow&&adverse.length)redFlags.push("徐脈と循環動態不安定");if(slow&&input.adverseSigns.syncope)redFlags.push("徐脈と失神");if(["mobitz_ii_candidate","high_grade_av_block_candidate","complete_av_block_candidate"].includes(classification))redFlags.push(label(classification));if(input.escapeRhythm==="ventricular_escape")redFlags.push("wide ventricular escape rhythm");if(input.pausePresent&&input.symptomsDuringPause)redFlags.push("症候性の長い休止");if(slow&&input.qtMarkedProlongation)redFlags.push("徐脈と著明なQT延長");if(slow&&(input.rOnTCandidate||input.polymorphicPvc))redFlags.push("徐脈と心室性不整脈リスク");if(slow&&input.highPotassium&&wide(input))redFlags.push("高K疑い・徐脈・wide QRS");if(input.newConductionDisease&&(input.inferiorIschemia||input.anteriorIschemia))redFlags.push("新規伝導障害と急性虚血疑い");if(classification==="indeterminate"&&adverse.length)redFlags.push("判定不能だが重篤症状あり");
  const factors=[];if(input.betaBlocker||input.avNodalDrug)factors.push(factor("drug","薬剤関連徐脈候補","drug",false));if(input.inferiorIschemia||input.anteriorIschemia)factors.push(factor("ischemia","虚血に伴う伝導障害候補","ischemia",true));if(input.highPotassium||input.lowPotassium||input.lowMagnesium)factors.push(factor("electrolyte","電解質異常候補","electrolyte",input.highPotassium&&wide(input)));if(input.hypothyroidism||input.hypothermia)factors.push(factor("metabolic","代謝性・低体温の可逆的原因候補","other",false));if(input.athlete||input.sleeping)factors.push(factor("physiologic","生理的背景候補（症状確認が必要）","physiologic",false));if(redFlags.length)factors.push(factor("risk","重篤な徐脈・伝導障害候補","conduction",true));
  const stablePhysio=classification==="physiologic_sinus_bradycardia_candidate"&&hemodynamicStatus==="stable";const pacing=["mobitz_ii_candidate","high_grade_av_block_candidate","complete_av_block_candidate","sinus_node_dysfunction_candidate"].includes(classification)||input.adverseSigns.syncope&&input.bundleBranchBlock?["恒久的ペーシング適応についてガイドラインに基づく専門評価が必要です。"]:[];
  const additionalChecks=uniq(stablePhysio?["症状","睡眠・運動習慣","薬歴","経過観察候補"]:["症状と徐脈の時間的相関","連続モニター","血圧・SpO₂・意識","12誘導または再心電図","前回心電図","K・Ca・Mg","血糖","腎機能","甲状腺機能","薬剤・中毒","トロポニン／虚血評価","心エコー","長時間モニター／Holter"]);
  const nextActions=uniq(stablePhysio?["背景と症状を確認し経過観察を検討"]:[...(redFlags.length?["気道・呼吸・循環を確認し連続モニター下で初期対応","除細動／経皮ペーシングが可能な環境の確保を検討","循環器／救急チームへ連絡"]:[]),"可逆的原因を検索し対応","薬物治療または一時的ペーシングの適応を専門チームと評価"]);
  const reasoning=[`1 循環動態：${hemodynamicStatus}`,`2 心室拍数：${input.ventricularRateBpm??"判定不能"} bpm`,`3 P波：${input.pWavePresence}`,`4 洞性P波：${input.sinusMorphology}`,`5 P-QRS：${input.pToQrsRelationship}`,`6 PR：${input.prPattern}`,`7 QRS脱落：${text(input.droppedQrs)}`,`8 PP一定：${text(input.ppRegular)}`,`9 QRS幅：${wide(input)?"wide":"narrow/判定不能"}`,`10 補充調律：${input.escapeRhythm}`,`11 可逆的原因：${factors.length?"候補あり":"情報不足"}`,`12 症状相関：${input.symptomCorrelation}`];
  const warnings=[];if(input.pWavePresence==="hidden"||input.hiddenInQrs||input.hiddenInTWave)warnings.push("P波が見えないことだけで洞停止・接合部調律と確定しません。");if(classification==="two_to_one_av_block")warnings.push("2:1房室ブロックは単一記録からMobitz I/IIを自動確定しません。");if(classification==="av_dissociation_uncertain")warnings.push("房室解離のみで完全房室ブロックと確定しません。");if(input.atrialFibrillation)warnings.push("心房細動中はP波・PRを通常どおり評価しません。");
  return {classification,hemodynamicStatus,clinicallyRelevantBradycardia,urgency:redFlags.length?"emergency":classification==="indeterminate"?"uncertain":stablePhysio||classification==="no_bradycardia"?"routine":"same_day",redFlags,diagnosticReasoning:reasoning,possibleFactors:factors,mustNotMiss:factors.filter(x=>x.isRedFlag),additionalChecks,nextActions,pacingEvaluation:pacing,clinicalPearls:["P波なしと判断する前にII・V1・V2、長いリズムストリップ、感度、QRS/T波内、基線ノイズを確認します。","補充調律は上位ペースメーカー停止または伝導途絶に対する救済機序である場合があります。"],warnings,limitations:["短い12誘導だけで最低心拍数、洞機能不全、恒久的ペーシング適応を確定しません。","薬剤用量やペーシング実施を自動決定しません。"],sources:bradyEvidenceSources};
}
function factor(id,label,category,isRedFlag){return {id:`brady-${id}`,label,category,priority:"high",supportingInputs:[label],contradictingInputs:[],requiredInputs:["症状","前回心電図","可逆的原因"],isRedFlag,sources:[bradySources.jcs2022,bradySources.esc2021]}}function valid(v){return typeof v==="number"&&Number.isFinite(v)&&v>=0}function wide(i){return valid(i.qrsWidthMs)&&i.qrsWidthMs>=120}function uniq(a){return [...new Set(a)]}function text(v){return v==null?"判定不能":v?"あり":"なし"}function label(c){return ({mobitz_ii_candidate:"Mobitz II候補",high_grade_av_block_candidate:"高度房室ブロック候補",complete_av_block_candidate:"完全房室ブロック候補"})[c]??c}
