import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { ANALYSIS_COOLDOWN_SECONDS, ECG_SESSION_COOKIE, SESSION_MAX_AGE_SECONDS, createAnalysisGateToken, createSessionToken, getAuthConfiguration, parseCookie, readAnalysisGateToken, safePinEqual, serializeHttpOnlyCookie, verifySessionToken } from "../lib/auth/ecg-auth.ts";

const secret="s".repeat(48);
const pinRoute=fs.readFileSync(new URL("../app/api/auth/pin/route.ts",import.meta.url),"utf8");
const logoutRoute=fs.readFileSync(new URL("../app/api/auth/logout/route.ts",import.meta.url),"utf8");
const sessionRoute=fs.readFileSync(new URL("../app/api/auth/session/route.ts",import.meta.url),"utf8");
const analyzeRoute=fs.readFileSync(new URL("../app/api/ecg/analyze/route.ts",import.meta.url),"utf8");
const rateLimits=fs.readFileSync(new URL("../lib/auth/rate-limits.ts",import.meta.url),"utf8");
const authGate=fs.readFileSync(new URL("../components/auth/EcgAuthGate.tsx",import.meta.url),"utf8");
const workspace=fs.readFileSync(new URL("../components/ecg/EcgWorkspace.tsx",import.meta.url),"utf8");
const proxySource=fs.readFileSync(new URL("../proxy.ts",import.meta.url),"utf8");

test("correct PIN comparison succeeds",()=>assert.equal(safePinEqual("12345678","12345678"),true));
test("incorrect PIN comparison fails",()=>assert.equal(safePinEqual("12345679","12345678"),false));
test("PIN missing is not configured",()=>assert.equal(getAuthConfiguration({ECG_AUTH_SECRET:secret}).configured,false));
test("AUTH secret missing is not configured",()=>assert.equal(getAuthConfiguration({ECG_APP_PIN:"12345678"}).configured,false));
test("session cookie never contains PIN",()=>assert.equal(createSessionToken(secret,0,"sid").includes("12345678"),false));
test("session cookie is HttpOnly",()=>assert.match(serializeHttpOnlyCookie(ECG_SESSION_COOKIE,"token",1800),/HttpOnly/));
test("production cookie is Secure",()=>{const before=process.env.NODE_ENV;process.env.NODE_ENV="production";assert.match(serializeHttpOnlyCookie(ECG_SESSION_COOKIE,"token",1800),/Secure/);process.env.NODE_ENV=before});
test("session cookie is SameSite Strict",()=>assert.match(serializeHttpOnlyCookie(ECG_SESSION_COOKIE,"token",1800),/SameSite=Strict/));
test("session max age is 1800",()=>assert.equal(SESSION_MAX_AGE_SECONDS,1800));
test("unauthenticated retired analysis route is rejected before 410",()=>{const verification=analyzeRoute.indexOf("const session=verifySessionToken");assert.ok(verification<analyzeRoute.indexOf("errorResponse(410"));assert.doesNotMatch(analyzeRoute,/request\.formData|createECGImageAnalysisService/)});
test("expired cookie reports expired",()=>{const token=createSessionToken(secret,0,"sid");assert.equal(verifySessionToken(token,secret,1801_000).status,"expired")});
test("tampered cookie is rejected",()=>{const token=createSessionToken(secret,0,"sid");assert.equal(verifySessionToken(`${token}x`,secret,1).status,"invalid")});
test("valid cookie permits a session",()=>assert.equal(verifySessionToken(createSessionToken(secret,0,"sid"),secret,1).status,"valid"));
test("logout deletes the session cookie",()=>{assert.match(logoutRoute,/ECG_SESSION_COOKIE/);assert.match(logoutRoute,/cookieOptions\(0\)/)});
test("fifth PIN failure activates lock",()=>{assert.match(rateLimits,/count>=5/);assert.match(pinRoute,/PIN_LOCKED/)});
test("successful PIN resets failure state",()=>assert.match(pinRoute,/resetPinFailures\(key\)/));
test("analysis cooldown is ten seconds",()=>assert.equal(ANALYSIS_COOLDOWN_SECONDS,10));
test("retired analysis route cannot construct a provider",()=>{assert.match(analyzeRoute,/errorResponse\(410/);assert.doesNotMatch(analyzeRoute,/service\.analyze|OpenAI/)});
test("unauthenticated screen does not render ECG workspace",()=>assert.match(authGate,/if\(authenticated\).*EcgWorkspace/s));
test("authenticated screen renders ECG workspace",()=>assert.match(authGate,/<EcgWorkspace onAuthRequired/));
test("PIN value is not written to auth logs",()=>{assert.match(pinRoute,/console\.warn\("\[ECG Auth\] failed",\{requestId,locked:/);assert.match(pinRoute,/console\.info\("\[ECG Auth\] success",\{requestId,locked:false\}/);assert.doesNotMatch(pinRoute,/console\.(?:info|warn|error)\([^\n]*\{[^\n]*(?:config\.pin|\bpin\b|\bbody\b)/)});
test("browser storage is not used for credentials",()=>{assert.doesNotMatch(authGate,/localStorage|sessionStorage/);assert.doesNotMatch(workspace,/localStorage|sessionStorage/)});
test("auth responses disable caching and sniffing",()=>{for(const source of [pinRoute,logoutRoute,sessionRoute]){assert.match(source,/Cache-Control.*no-store/);assert.match(source,/X-Content-Type-Options.*nosniff/)}});
test("analysis gate is bound to the authenticated session",()=>{const token=createAnalysisGateToken(secret,"sid",1234,0);assert.equal(readAnalysisGateToken(token,secret,"sid",1),1234);assert.equal(readAnalysisGateToken(token,secret,"other",1),null)});
test("cookie parser extracts only the named cookie",()=>{const request=new Request("https://example.test",{headers:{cookie:"other=x; ecg_app_session=abc.def"}});assert.equal(parseCookie(request,ECG_SESSION_COOKIE),"abc.def")});
test("future ECG APIs are covered by proxy and routes still revalidate",()=>{assert.match(proxySource,/matcher:"\/api\/ecg\/:path\*"/);assert.match(proxySource,/verifySessionToken/);assert.match(analyzeRoute,/verifySessionToken/)});
