import test from "node:test";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {canonicalMeasurementsEnabled} from "../logic/integration/canonical-measurement-feature.js";
import {buildProductionCanonicalMeasurementShadow} from "../logic/integration/build-production-canonical-measurements.js";
import {createDefaultIntegratedInput} from "../data/integration/defaults.js";
import {buildIntegratedInterpretation} from "../logic/integration/build-integrated-interpretation.js";
import {ecgRuleRegistry} from "../data/rule-engine/rule-registry.js";

const sources={heartRateBpm:"legacy_default",prMs:"legacy_default",qrsMs:"legacy_default",qtcMs:"legacy_default",rateClass:"legacy_default",prClass:"legacy_default",qrsClass:"legacy_default",qtcClass:"legacy_default"};
const base=patch=>({enabled:false,heartRate:{value:null,assessment:"not_assessed"},pr:{value:null,assessment:"not_assessed",category:null,categoryAssessment:"not_assessed"},qrs:{value:null,measurementAssessment:"not_assessed",category:null,categoryAssessment:"not_assessed"},qtc:{value:null,assessment:"not_assessed"},legacy:{heartRateBpm:72,prMs:164,qrsMs:92,qtcMs:438,rateClass:"normal",prClass:"normal",qrsClass:"narrow",qtcClass:"normal"},legacySources:{...sources},...patch});
const shadow=patch=>buildProductionCanonicalMeasurementShadow(base(patch));
const value=x=>x.status==="present"?x.value:x.status;

test("B1-1 HR 45 is physician measurement and derives bradycardia",()=>{const x=shadow({heartRate:{value:45,assessment:"present"},legacy:{...base({}).legacy,heartRateBpm:45,rateClass:"bradycardia"},legacySources:{...sources,heartRateBpm:"physician_measurement",rateClass:"derived"}});assert.equal(value(x.canonical.measurements.heartRateBpm),45);assert.equal(value(x.effectiveClasses.rateClass),"bradycardia");assert.deepEqual(x.provenance.heartRateBpm,{source:"physician_measurement",assessmentStatus:"entered"})});
test("B1-2 missing HR ignores legacy 72",()=>{const x=shadow({});assert.equal(x.canonical.measurements.heartRateBpm.status,"not_assessed");assert.equal(x.effectiveClasses.rateClass.status,"not_assessed");assert.equal(x.comparisons.find(v=>v.field==="heartRateBpm").classification,"REVIEW")});
test("B1-3 PR 240 derives prolonged",()=>{const x=shadow({pr:{value:240,assessment:"present",category:null,categoryAssessment:"not_assessed"},legacy:{...base({}).legacy,prMs:240,prClass:"prolonged"},legacySources:{...sources,prMs:"physician_measurement",prClass:"derived"}});assert.equal(value(x.canonical.measurements.prMs),240);assert.equal(value(x.effectiveClasses.prClass),"prolonged")});
test("B1-4 missing PR is not normal",()=>{const x=shadow({});assert.equal(x.canonical.measurements.prMs.status,"not_assessed");assert.equal(x.effectiveClasses.prClass.status,"not_assessed")});
test("B1-5 measured QRS 160 derives wide",()=>{const x=shadow({qrs:{value:160,measurementAssessment:"present",category:"wide",categoryAssessment:"present"},legacy:{...base({}).legacy,qrsMs:160,qrsClass:"wide"},legacySources:{...sources,qrsMs:"physician_measurement",qrsClass:"derived"}});assert.equal(value(x.canonical.measurements.qrsMs),160);assert.equal(value(x.effectiveClasses.qrsClass),"wide")});
test("B1-6 wide category keeps milliseconds unassessed",()=>{const x=shadow({qrs:{value:null,measurementAssessment:"not_assessed",category:"wide",categoryAssessment:"present"},legacy:{...base({}).legacy,qrsMs:140,qrsClass:"wide"},legacySources:{...sources,qrsMs:"legacy_pseudo_value",qrsClass:"physician_category"}});assert.equal(x.canonical.measurements.qrsMs.status,"not_assessed");assert.equal(value(x.canonical.categorical.qrsWidth),"wide");assert.equal(value(x.effectiveClasses.qrsClass),"wide");assert.equal(x.provenance.qrsWidthCategory.assessmentStatus,"inferred_category_only")});
test("B1-7 narrow category keeps milliseconds unassessed",()=>{const x=shadow({qrs:{value:null,measurementAssessment:"not_assessed",category:"narrow",categoryAssessment:"present"},legacy:{...base({}).legacy,qrsMs:100,qrsClass:"narrow"},legacySources:{...sources,qrsMs:"legacy_pseudo_value",qrsClass:"physician_category"}});assert.equal(x.canonical.measurements.qrsMs.status,"not_assessed");assert.equal(value(x.effectiveClasses.qrsClass),"narrow")});
test("B1-8 entered QTc derives its existing class",()=>{const x=shadow({qtc:{value:510,assessment:"present"},legacy:{...base({}).legacy,qtcMs:510,qtcClass:"prolonged"},legacySources:{...sources,qtcMs:"physician_measurement",qtcClass:"derived"}});assert.equal(value(x.canonical.measurements.qtcMs),510);assert.equal(value(x.effectiveClasses.qtcClass),"prolonged")});
test("B1-9 missing QTc does not inherit calculated default",()=>{const x=shadow({});assert.equal(x.canonical.measurements.qtcMs.status,"not_assessed");assert.equal(x.effectiveClasses.qtcClass.status,"not_assessed")});
test("B1-10 all entered measurements and classes match",()=>{const x=shadow({heartRate:{value:45,assessment:"present"},pr:{value:240,assessment:"present",category:"prolonged",categoryAssessment:"present"},qrs:{value:160,measurementAssessment:"present",category:"wide",categoryAssessment:"present"},qtc:{value:510,assessment:"present"},legacy:{heartRateBpm:45,prMs:240,qrsMs:160,qtcMs:510,rateClass:"bradycardia",prClass:"prolonged",qrsClass:"wide",qtcClass:"prolonged"},legacySources:Object.fromEntries(Object.keys(sources).map(k=>[k,k.endsWith("Class")?"derived":"physician_measurement"]))});assert.equal(x.summary.majorFail,0);assert.equal(x.summary.match,8)});
test("B1-11 unknown observations remain unknown",()=>{const x=shadow({heartRate:{value:null,assessment:"unknown"},pr:{value:null,assessment:"unknown",category:"indeterminate",categoryAssessment:"unknown"},qrs:{value:null,measurementAssessment:"unknown",category:"indeterminate",categoryAssessment:"unknown"},qtc:{value:null,assessment:"unknown"}});for(const field of Object.values(x.canonical.measurements))assert.equal(field.status,"unknown");assert.equal(x.canonical.categorical.qrsWidth.status,"unknown")});
test("B1-12 legacy-only defaults create no canonical evidence",()=>{const x=shadow({});for(const field of Object.values(x.canonical.measurements))assert.equal(field.status,"not_assessed");assert.equal(Object.values(x.provenance).filter(v=>v.source==="legacy_default").length,0)});
test("B1-13 pseudo QRS 140 is REVIEW rather than evidence or MAJOR_FAIL",()=>{const x=shadow({qrs:{value:null,measurementAssessment:"not_assessed",category:"wide",categoryAssessment:"present"},legacy:{...base({}).legacy,qrsMs:140,qrsClass:"wide"},legacySources:{...sources,qrsMs:"legacy_pseudo_value",qrsClass:"physician_category"}});assert.equal(x.comparisons.find(v=>v.field==="qrsMs").classification,"REVIEW");assert.equal(x.summary.majorFail,0)});

test("feature flag parser defaults OFF and accepts explicit ON values",()=>{assert.equal(canonicalMeasurementsEnabled(undefined),false);assert.equal(canonicalMeasurementsEnabled("false"),false);assert.equal(canonicalMeasurementsEnabled("true"),true);assert.equal(canonicalMeasurementsEnabled("1"),true)});
test("flag OFF and ON generate identical canonical evidence",()=>{const input=base({heartRate:{value:45,assessment:"present"}}),off=buildProductionCanonicalMeasurementShadow(input),on=buildProductionCanonicalMeasurementShadow({...input,enabled:true});assert.deepEqual(on.canonical,off.canonical);assert.deepEqual(on.comparisons,off.comparisons);assert.equal(off.enabled,false);assert.equal(on.enabled,true)});
test("flag rollback ON to OFF does not mutate input or canonical state",()=>{const input=base({qrs:{value:null,measurementAssessment:"not_assessed",category:"wide",categoryAssessment:"present"}}),snapshot=structuredClone(input);buildProductionCanonicalMeasurementShadow({...input,enabled:true});buildProductionCanonicalMeasurementShadow({...input,enabled:false});assert.deepEqual(input,snapshot)});
test("unknown absent normal and undefined false coercions are zero",()=>{const x=shadow({heartRate:{value:null,assessment:"unknown"},pr:{value:null,assessment:"unknown",category:"indeterminate",categoryAssessment:"unknown"},qrs:{value:null,measurementAssessment:"unknown",category:"indeterminate",categoryAssessment:"unknown"},qtc:{value:null,assessment:"unknown"}});assert.equal(Object.values(x.canonical.measurements).filter(v=>v.status==="absent"||value(v)==="normal"||value(v)===false).length,0)});
test("pseudo and normal default measurement leaks are zero",()=>{const x=shadow({});assert.deepEqual(Object.values(x.canonical.measurements).map(value),["not_assessed","not_assessed","not_assessed","not_assessed"])});

test("five emergency fixtures are identical before and after B-1 shadow execution",()=>{const fixtures=[{ecg:{wideTachycardia:true}},{ecg:{completeBlock:true}},{clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true,reciprocalChange:true}},{clinical:{syncope:true},ecg:{qtMarked:true,qtProlonged:true,rOnT:true,pvc:true}},{ecg:{peakedT:true,pWaveAbsent:true,wideQrs:true,qrsProlonged:true}}];for(const patch of fixtures){const input=createDefaultIntegratedInput();for(const [group,values] of Object.entries(patch))Object.assign(input[group],values);const before=buildIntegratedInterpretation(input);shadow({});const after=buildIntegratedInterpretation(input);assert.deepEqual(after,before);assert.ok(["emergency","resuscitation"].includes(after.urgency))}});
test("ten representative candidate snapshots retain IDs priority urgency and Red Flags",()=>{const patches=[{ecg:{wideTachycardia:true}},{ecg:{completeBlock:true}},{ecg:{mobitzII:true}},{ecg:{highGradeBlock:true}},{clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true}},{ecg:{qtProlonged:true}},{ecg:{peakedT:true,pWaveAbsent:true,wideQrs:true}},{ecg:{rbbb:true,wideQrs:true}},{ecg:{lbbb:true,wideQrs:true}},{ecg:{deltaWave:true,shortPr:true,wideQrs:true,preexcitation:true}}];for(const patch of patches){const input=createDefaultIntegratedInput();for(const [group,values] of Object.entries(patch))Object.assign(input[group],values);const before=buildIntegratedInterpretation(input);shadow({});const after=buildIntegratedInterpretation(input);assert.deepEqual({ids:after.diagnosticCandidates.map(x=>x.id),priorities:after.diagnosticCandidates.map(x=>x.priority),urgency:after.urgency,redFlags:after.redFlags},{ids:before.diagnosticCandidates.map(x=>x.id),priorities:before.diagnosticCandidates.map(x=>x.priority),urgency:before.urgency,redFlags:before.redFlags})}});
test("Production imports measurement shadow but never routes canonical candidates",()=>{const source=readFileSync(new URL("../components/ecg/EcgWorkspace.tsx",import.meta.url),"utf8");assert.match(source,/buildProductionCanonicalMeasurementShadow/);assert.doesNotMatch(source,/canonicalMeasurementShadow\.(diagnosticCandidates|urgency|redFlags)/)});
test("Rule Registry count IDs priorities conditions and required inputs keep A-Final hash",()=>{assert.equal(ecgRuleRegistry.length,59);const snapshot=ecgRuleRegistry.map(rule=>({id:rule.id,priority:rule.priority,requiredInputs:rule.requiredInputs}));assert.equal(createHash("sha256").update(JSON.stringify(snapshot)).digest("hex"),"afc64fa3dfe62d554ca3e636c7f9257ba282b07f6cf8839589871f9e733ea23e")});
