import test from "node:test";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {canonicalBasicRhythmCandidatesEnabled} from "../logic/integration/canonical-basic-rhythm-candidates-feature.js";
import {migrateCanonicalBasicRhythmCandidates} from "../logic/integration/migrate-canonical-basic-rhythm-candidates.js";
import {buildIntegratedInterpretation} from "../logic/integration/build-integrated-interpretation.js";
import {createDefaultIntegratedInput} from "../data/integration/defaults.js";
import {ecgRuleRegistry} from "../data/rule-engine/rule-registry.js";
import {absentObservation,notAssessed,presentObservation,unknownObservation} from "../types/clinical-observation-runtime.js";

const na=()=>notAssessed(),p=value=>typeof value==="boolean"?(value?presentObservation(true):absentObservation()):presentObservation(value);
function legacy(patch={}){const input=createDefaultIntegratedInput();for(const [group,values] of Object.entries(patch))Object.assign(input[group],values);return buildIntegratedInterpretation(input)}
function shadow(patch={}){return {rateClass:patch.rateClass??na(),qrsWidth:patch.qrsWidth??na(),rhythm:{regularity:na(),pWavesPresent:na(),pBeforeEveryQrs:na(),qrsAfterEveryP:na(),variableRr:na(),flutterActivity:na(),multiplePMorphologies:na(),avDissociation:na(),captureBeat:na(),fusionBeat:na(),preExcitation:na(),afSuspicion:na(),pQrsRelationship:na(),...patch.rhythm},clinical:{hypotensionOrShock:na(),syncope:na(),cardiacArrest:na(),electrolyteAbnormality:na()},vf:na()}}
function migrate(input,base=legacy(),enabled=true){return migrateCanonicalBasicRhythmCandidates({enabled,legacyResult:base,shadowInput:input})}
const ids=result=>result.diagnosticCandidates.map(item=>item.id);

test("B2b-1 classic AF is migrated as supported",()=>assert.ok(ids(migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular"),variableRr:p(true),pWavesPresent:p(false)}})).result).includes("atrial-fibrillation-pattern")));
test("B2b-2 incomplete AF does not erase legacy visibility",()=>{const base=legacy();base.diagnosticCandidates.push({...legacy({confirmedModules:["simplified-af"]}).diagnosticCandidates[0]});const out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular")}}),base);assert.ok(ids(out.result).includes("atrial-fibrillation-pattern"))});
test("B2b-3 flutter support adds flutter and retains AF alternative in evaluation",()=>{const out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("regular"),flutterActivity:p(true)}}));assert.ok(ids(out.result).includes("atrial-flutter-pattern"));assert.ok(out.evaluation.candidates.some(x=>x.candidateId==="atrial_fibrillation"))});
test("B2b-4 unassessed flutter does not create a Production candidate",()=>assert.ok(!ids(migrate(shadow({rateClass:p("tachycardia")})).result).includes("atrial-flutter-pattern")));
test("B2b-5 narrow regular tachycardia supports SVT",()=>assert.ok(ids(migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("narrow"),rhythm:{regularity:p("regular")}})).result).includes("supraventricular-tachycardia-pattern")));
test("B2b-6 wide regular tachycardia does not hard-exclude SVT in evaluation",()=>assert.ok(migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("wide"),rhythm:{regularity:p("regular")}})).evaluation.candidates.some(x=>x.candidateId==="supraventricular_tachycardia"&&x.status==="possible")));
test("B2b-7 MAT support adds MAT and keeps AF evaluation",()=>{const out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular"),multiplePMorphologies:p(true)}}));assert.ok(ids(out.result).includes("multifocal-atrial-tachycardia-pattern"));assert.ok(out.evaluation.candidates.some(x=>x.candidateId==="atrial_fibrillation"))});
test("B2b-8 incomplete MAT does not suppress AF",()=>{const out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular")}}));assert.ok(out.evaluation.candidates.some(x=>x.candidateId==="multifocal_atrial_tachycardia"&&x.status==="insufficient_data"));assert.ok(out.evaluation.candidates.some(x=>x.candidateId==="atrial_fibrillation"))});
test("B2b-9 junctional-compatible evidence supports junctional rhythm",()=>assert.ok(ids(migrate(shadow({rateClass:p("bradycardia"),qrsWidth:p("narrow"),rhythm:{pWavesPresent:p(false),pQrsRelationship:p("junctional_compatible")}})).result).includes("junctional-rhythm-pattern")));
test("B2b-10 incomplete junctional evidence remains non-Production",()=>{const out=migrate(shadow({rateClass:p("bradycardia")}));assert.ok(!ids(out.result).includes("junctional-rhythm-pattern"))});
test("B2b-11 AF merge preserves legacy urgency Red Flags and Rule IDs",()=>{const base=legacy({confirmedModules:["simplified-af"]}),out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular"),variableRr:p(true),pWavesPresent:p(false)}}),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings);assert.deepEqual(out.diagnosticCandidates.find(x=>x.id==="atrial-fibrillation-pattern").ruleIds,base.diagnosticCandidates[0].ruleIds)});
test("B2b-12 flutter candidate is non-emergency and has no invented Rule",()=>{const c=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("regular"),flutterActivity:p(true)}})).result.diagnosticCandidates[0];assert.equal(c.urgency,"same_day");assert.deepEqual(c.ruleIds,[])});
test("B2b-13 SVT migration does not change legacy result fields except candidates",()=>{const base=legacy(),out=migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("narrow"),rhythm:{regularity:p("regular")}}),base).result;assert.deepEqual({...out,diagnosticCandidates:base.diagnosticCandidates},base)});
test("B2b-14 WCT emergency candidate remains unchanged",()=>{const base=legacy({ecg:{wideTachycardia:true}}),out=migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("wide"),rhythm:{regularity:p("regular")}}),base).result;assert.equal(out.urgency,"emergency");assert.deepEqual(out.criticalFindings,base.criticalFindings);assert.ok(ids(out).includes("wide-qrs-tachycardia"))});
test("B2b-15 pre-excited AF remains unchanged",()=>{const base=legacy({ecg:{wideTachycardia:true,irregularTachycardia:true,preexcitation:true}}),out=migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("wide"),rhythm:{regularity:p("irregular"),preExcitation:p(true)}}),base).result;assert.equal(out.urgency,"emergency");assert.ok(ids(out).includes("preexcited-af"));assert.deepEqual(out.criticalFindings,base.criticalFindings)});
test("B2b-16 severe brady urgency is never lowered by junctional migration",()=>{const base=legacy({clinical:{syncope:true},ecg:{bradycardia:true}}),out=migrate(shadow({rateClass:p("bradycardia"),qrsWidth:p("narrow"),rhythm:{pWavesPresent:p(false),pQrsRelationship:p("junctional_compatible")}}),base).result;assert.equal(out.urgency,base.urgency)});
test("B2b flag defaults OFF and recognizes explicit ON values",()=>{assert.equal(canonicalBasicRhythmCandidatesEnabled(undefined),false);assert.equal(canonicalBasicRhythmCandidatesEnabled("true"),true)});
test("flag OFF returns the exact legacy result reference",()=>{const base=legacy(),out=migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("narrow"),rhythm:{regularity:p("regular")}}),base,false);assert.equal(out.result,base);assert.equal(out.evaluation,null)});
test("rollback ON then OFF has no state corruption",()=>{const base=legacy(),input=shadow({rateClass:p("tachycardia"),qrsWidth:p("narrow"),rhythm:{regularity:p("regular")}}),snapshot=structuredClone(input);migrate(input,base,true);assert.equal(migrate(input,base,false).result,base);assert.deepEqual(input,snapshot)});
test("supported canonical and legacy candidate IDs are deduplicated",()=>{const base=legacy({confirmedModules:["simplified-af"]}),out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular"),variableRr:p(true),pWavesPresent:p(false)}}),base).result;assert.equal(ids(out).length,new Set(ids(out)).size)});
test("supported canonical and legacy labels are deduplicated",()=>{const base=legacy({confirmedModules:["simplified-af"]}),out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular"),variableRr:p(true),pWavesPresent:p(false)}}),base).result,labels=out.diagnosticCandidates.map(x=>x.label);assert.equal(labels.length,new Set(labels).size)});
test("unknown P is not converted to absent",()=>{const out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{regularity:p("irregular"),variableRr:p(true),pWavesPresent:unknownObservation()}}));assert.equal(out.evaluation.candidates.find(x=>x.candidateId==="atrial_fibrillation").status,"possible")});
test("not-assessed RR is not converted to regular",()=>{const out=migrate(shadow({rateClass:p("tachycardia"),rhythm:{pWavesPresent:p(false)}}));assert.ok(!ids(out.result).includes("atrial-fibrillation-pattern"))});
test("dangerous shadow candidates are never migrated",()=>{const out=migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("wide"),rhythm:{regularity:p("irregular"),preExcitation:p(true)}}));for(const id of ["ventricular-tachycardia","wide-qrs-tachycardia","preexcited-af"])assert.ok(!ids(out.result).includes(id))});
test("candidate migration cannot alter acute coronary emergency output",()=>{const base=legacy({clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true}}),out=migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("narrow"),rhythm:{regularity:p("regular")}}),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)});
test("candidate migration cannot alter TdP emergency output",()=>{const base=legacy({clinical:{syncope:true},ecg:{qtProlonged:true,qtMarked:true,pvc:true,rOnT:true}}),out=migrate(shadow(),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)});
test("five-flag dependency matrix keeps B2b independently switchable",()=>{for(const [b1,b2,b2b] of [[false,false,false],[true,false,false],[true,true,false],[true,true,true],[false,true,true]]){const base=legacy(),out=migrate(shadow({rateClass:p("tachycardia"),qrsWidth:p("narrow"),rhythm:{regularity:p("regular")}}),base,b2b);assert.equal(ids(out.result).includes("supraventricular-tachycardia-pattern"),b2b);assert.equal(typeof b1,"boolean");assert.equal(typeof b2,"boolean")}});
test("twenty-case parity has zero major safety failures",()=>{const cases=[{}, {ecg:{wideTachycardia:true}}, {ecg:{wideTachycardia:true,irregularTachycardia:true,preexcitation:true}}, {ecg:{completeBlock:true}}, {clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true}}, {ecg:{qtProlonged:true,rOnT:true}}, {ecg:{vf:true}}, {ecg:{vt:true}}, {ecg:{rbbb:true,wideQrs:true}}, {ecg:{lbbb:true,wideQrs:true}}, {ecg:{peakedT:true,pWaveAbsent:true,wideQrs:true}}, {ecg:{mobitzII:true}}, {ecg:{highGradeBlock:true}}, {ecg:{wellensMorphology:true},clinical:{chestPainHistory:true}}, {ecg:{diffuseStDepression:true,avrElevation:true}}, {quality:{limbReversal:true}}, {ecg:{preexcitation:true}}, {ecg:{pvc:true,rOnT:true}}, {ecg:{giantNegativeT:true}}, {ecg:{bradycardia:true}}];for(const patch of cases){const base=legacy(patch),out=migrate(shadow(),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)}});
test("B2b retains 59 Rule Registry and its A-Final hash",()=>{assert.equal(ecgRuleRegistry.length,59);const snapshot=ecgRuleRegistry.map(rule=>({id:rule.id,priority:rule.priority,requiredInputs:rule.requiredInputs}));assert.equal(createHash("sha256").update(JSON.stringify(snapshot)).digest("hex"),"afc64fa3dfe62d554ca3e636c7f9257ba282b07f6cf8839589871f9e733ea23e")});
test("Production wires B2b without changing result UI structure",()=>{const source=readFileSync(new URL("../components/ecg/EcgWorkspace.tsx",import.meta.url),"utf8");assert.match(source,/migrateCanonicalBasicRhythmCandidates/);assert.match(source,/legacyIntegratedResult/)});
