import test from "node:test";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {canonicalConductionCandidatesEnabled} from "../logic/integration/canonical-conduction-candidates-feature.js";
import {migrateCanonicalConductionCandidates} from "../logic/integration/migrate-canonical-conduction-candidates.js";
import {createDefaultIntegratedInput} from "../data/integration/defaults.js";
import {buildIntegratedInterpretation} from "../logic/integration/build-integrated-interpretation.js";
import {ecgRuleRegistry} from "../data/rule-engine/rule-registry.js";
import {absentObservation,notAssessed,presentObservation,unknownObservation} from "../types/clinical-observation-runtime.js";

const n=()=>notAssessed(),p=value=>typeof value==="boolean"?(value?presentObservation(true):absentObservation()):presentObservation(value),u=()=>unknownObservation();
function shadow(patch={}){return {rateClass:n(),prMs:n(),prClass:n(),qrsWidth:n(),axis:n(),pBeforeEveryQrs:n(),qrsAfterEveryP:n(),droppedQrs:n(),progressivePr:n(),fixedPrBeforeDrop:n(),twoToOne:n(),multipleNonConductedP:n(),avDissociation:n(),independentAvActivity:n(),atrialRateBpm:n(),ventricularRateBpm:n(),pQrsRelationship:n(),rbbbMorphology:n(),lbbbMorphology:n(),lafbMorphology:n(),lpfbMorphology:n(),escapeRhythm:n(),syncope:n(),presyncope:n(),hypotensionOrShock:n(),...patch}}
function legacy(patch={}){const input=createDefaultIntegratedInput();for(const [group,values] of Object.entries(patch))Object.assign(input[group],values);return buildIntegratedInterpretation(input)}
const run=(input,base=legacy(),enabled=true)=>migrateCanonicalConductionCandidates({enabled,legacyResult:base,shadowInput:input});const ids=r=>r.diagnosticCandidates.map(x=>x.id);

test("B3a-1 first-degree AV block is supported",()=>assert.ok(ids(run(shadow({prClass:p("prolonged"),pBeforeEveryQrs:p(true),qrsAfterEveryP:p(true),droppedQrs:p(false)})).result).includes("first-degree-av-block-pattern")));
test("B3a-2 unassessed PR generates no first-degree Production candidate",()=>assert.ok(!ids(run(shadow()).result).includes("first-degree-av-block-pattern")));
test("B3a-3 Mobitz I is supported",()=>assert.ok(ids(run(shadow({progressivePr:p(true),droppedQrs:p(true)})).result).includes("mobitz-i-pattern")));
test("B3a-4 Mobitz II is supported without changing legacy emergency",()=>{const base=legacy({ecg:{mobitzII:true}}),out=run(shadow({fixedPrBeforeDrop:p(true),progressivePr:p(false),droppedQrs:p(true)}),base).result;assert.ok(ids(out).includes("advanced-av-block"));assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)});
test("B3a-5 incomplete dropped beat remains possible in evaluation",()=>{const out=run(shadow({droppedQrs:p(true),progressivePr:u(),fixedPrBeforeDrop:u()}));assert.equal(out.evaluation.candidates.find(x=>x.candidateId==="mobitz_ii").status,"possible");assert.equal(out.evaluation.candidates.find(x=>x.candidateId==="mobitz_i").status,"possible")});
test("B3a-6 high-grade AV block is supported",()=>assert.ok(ids(run(shadow({multipleNonConductedP:p(true)})).result).includes("advanced-av-block")));
test("B3a-7 complete AV block is supported",()=>assert.ok(ids(run(shadow({avDissociation:p(true),independentAvActivity:p(true)})).result).includes("advanced-av-block")));
test("B3a-8 unknown AV dissociation does not over-support complete block",()=>{const out=run(shadow({rateClass:p("bradycardia"),avDissociation:u(),pQrsRelationship:u()}));assert.notEqual(out.evaluation.candidates.find(x=>x.candidateId==="complete_av_block").status,"supported")});
test("B3a-9 RBBB wide morphology is supported",()=>assert.ok(ids(run(shadow({qrsWidth:p("wide"),rbbbMorphology:p(true)})).result).includes("rbbb-pattern")));
test("B3a-10 LBBB wide morphology is supported",()=>assert.ok(ids(run(shadow({qrsWidth:p("wide"),lbbbMorphology:p(true)})).result).includes("lbbb-pattern")));
test("B3a-11 LAFB needs left axis and compatible morphology",()=>assert.ok(ids(run(shadow({axis:p("left"),lafbMorphology:p(true)})).result).includes("lafb-pattern")));
test("B3a-12 LPFB needs right axis and compatible morphology",()=>{const out=run(shadow({axis:p("right"),lpfbMorphology:p(true)}));assert.ok(out.evaluation.candidates.some(x=>x.candidateId==="lpfb"&&x.status==="possible"));assert.ok(ids(out.result).includes("lpfb-pattern"))});
test("axis alone cannot support LAFB or LPFB",()=>{const out=run(shadow({axis:p("left")}));assert.ok(!ids(out.result).includes("lafb-pattern"));assert.notEqual(out.evaluation.candidates.find(x=>x.candidateId==="lafb").status,"supported")});
test("B3a-13 RBBB plus LAFB supports bifascicular block",()=>assert.ok(ids(run(shadow({qrsWidth:p("wide"),axis:p("left"),rbbbMorphology:p(true),lafbMorphology:p(true)})).result).includes("bifascicular-block-pattern")));
test("B3a-14 bifascicular plus syncope changes no Production emergency",()=>{const base=legacy(),out=run(shadow({qrsWidth:p("wide"),axis:p("left"),rbbbMorphology:p(true),lafbMorphology:p(true),syncope:p(true)}),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)});
test("B3a-15 wide Mobitz II retains legacy emergency",()=>{const base=legacy({ecg:{mobitzII:true,wideQrs:true}}),out=run(shadow({qrsWidth:p("wide"),fixedPrBeforeDrop:p(true),progressivePr:p(false),droppedQrs:p(true)}),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)});
test("feature flag defaults OFF",()=>{assert.equal(canonicalConductionCandidatesEnabled(undefined),false);assert.equal(canonicalConductionCandidatesEnabled("on"),true)});
test("flag OFF returns exact legacy result",()=>{const base=legacy(),out=run(shadow({qrsWidth:p("wide"),rbbbMorphology:p(true)}),base,false);assert.equal(out.result,base);assert.equal(out.evaluation,null)});
test("flag matrix keeps B3a independent of earlier flags",()=>{for(const flags of [[false,false,false,false],[true,false,false,true],[true,true,true,true]]){const base=legacy(),out=run(shadow({qrsWidth:p("wide"),rbbbMorphology:p(true)}),base,flags[3]);assert.equal(ids(out.result).includes("rbbb-pattern"),flags[3])}});
test("rollback does not mutate input or legacy result",()=>{const input=shadow({qrsWidth:p("wide"),rbbbMorphology:p(true)}),base=legacy(),a=structuredClone(input),b=structuredClone(base);run(input,base,true);assert.equal(run(input,base,false).result,base);assert.deepEqual(input,a);assert.deepEqual(base,b)});
test("duplicate candidate IDs are merged",()=>{const base=legacy({ecg:{rbbb:true,wideQrs:true}}),out=run(shadow({qrsWidth:p("wide"),rbbbMorphology:p(true)}),base).result;assert.equal(ids(out).length,new Set(ids(out)).size)});
test("duplicate candidate labels are absent",()=>{const base=legacy({ecg:{lbbb:true,wideQrs:true}}),out=run(shadow({qrsWidth:p("wide"),lbbbMorphology:p(true)}),base).result,labels=out.diagnosticCandidates.map(x=>x.label);assert.equal(labels.length,new Set(labels).size)});
test("canonical merge preserves legacy Rule IDs",()=>{const base=legacy({ecg:{rbbb:true,wideQrs:true}}),out=run(shadow({qrsWidth:p("wide"),rbbbMorphology:p(true)}),base).result;assert.deepEqual(out.diagnosticCandidates.find(x=>x.id==="rbbb-pattern").ruleIds,base.diagnosticCandidates.find(x=>x.id==="rbbb-pattern").ruleIds)});
test("new canonical candidates invent no Explainable Rule IDs",()=>assert.deepEqual(run(shadow({axis:p("left"),lafbMorphology:p(true)})).result.diagnosticCandidates.find(x=>x.id==="lafb-pattern").ruleIds,[]));
test("unknown and not-assessed remain unresolved",()=>{const out=run(shadow({avDissociation:u(),droppedQrs:u(),axis:u()}));assert.ok(!ids(out.result).some(id=>["advanced-av-block","lafb-pattern","lpfb-pattern"].includes(id)))});
test("emergency parity across eight danger fixtures",()=>{const cases=[{ecg:{mobitzII:true}},{ecg:{highGradeBlock:true}},{ecg:{completeBlock:true}},{clinical:{syncope:true},ecg:{bradycardia:true}},{ecg:{wideTachycardia:true}},{ecg:{wideTachycardia:true,irregularTachycardia:true,preexcitation:true}},{clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true}},{clinical:{syncope:true},ecg:{qtMarked:true,qtProlonged:true,rOnT:true}}];for(const patch of cases){const base=legacy(patch),out=run(shadow(),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)}});
test("twenty representative fixtures have zero major safety divergence",()=>{const cases=[{}, {ecg:{mobitzI:true}}, {ecg:{mobitzII:true}}, {ecg:{highGradeBlock:true}}, {ecg:{completeBlock:true}}, {ecg:{rbbb:true,wideQrs:true}}, {ecg:{lbbb:true,wideQrs:true}}, {ecg:{wideTachycardia:true}}, {ecg:{vt:true}}, {ecg:{vf:true}}, {ecg:{preexcitation:true}}, {ecg:{qtProlonged:true,rOnT:true}}, {ecg:{peakedT:true,pWaveAbsent:true,wideQrs:true}}, {clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true}}, {ecg:{wellensMorphology:true},clinical:{chestPainHistory:true}}, {quality:{limbReversal:true}}, {ecg:{bradycardia:true}}, {ecg:{pvc:true}}, {ecg:{giantNegativeT:true}}, {ecg:{diffuseStDepression:true,avrElevation:true}}];for(const patch of cases){const base=legacy(patch),out=run(shadow(),base).result;assert.equal(out.urgency,base.urgency);assert.deepEqual(out.criticalFindings,base.criticalFindings)}});
test("B3a retains the 59 Rule Registry A-Final hash",()=>{assert.equal(ecgRuleRegistry.length,59);const snapshot=ecgRuleRegistry.map(rule=>({id:rule.id,priority:rule.priority,requiredInputs:rule.requiredInputs}));assert.equal(createHash("sha256").update(JSON.stringify(snapshot)).digest("hex"),"afc64fa3dfe62d554ca3e636c7f9257ba282b07f6cf8839589871f9e733ea23e")});
