import test from "node:test";
import assert from "node:assert/strict";
import {createHash} from "node:crypto";
import {readFileSync} from "node:fs";
import {canonicalRateRhythmEnabled} from "../logic/integration/canonical-rate-rhythm-feature.js";
import {buildProductionCanonicalMeasurementShadow} from "../logic/integration/build-production-canonical-measurements.js";
import {buildProductionCanonicalRateRhythm} from "../logic/integration/build-production-canonical-rate-rhythm.js";
import {createDefaultIntegratedInput} from "../data/integration/defaults.js";
import {buildIntegratedInterpretation} from "../logic/integration/build-integrated-interpretation.js";
import {ecgRuleRegistry} from "../data/rule-engine/rule-registry.js";
import {createDefaultBradyInput} from "../data/bradyarrhythmia/defaults.js";
import {interpretBradyarrhythmia} from "../logic/bradyarrhythmia/interpret-brady.js";

const measurementSources={heartRateBpm:"legacy_default",prMs:"legacy_default",qrsMs:"legacy_default",qtcMs:"legacy_default",rateClass:"legacy_default",prClass:"legacy_default",qrsClass:"legacy_default",qtcClass:"legacy_default"};
function measurements(hr=null,assessment="not_assessed",enabled=false){return buildProductionCanonicalMeasurementShadow({enabled,heartRate:{value:hr,assessment},pr:{value:null,assessment:"not_assessed",category:null,categoryAssessment:"not_assessed"},qrs:{value:null,measurementAssessment:"not_assessed",category:null,categoryAssessment:"not_assessed"},qtc:{value:null,assessment:"not_assessed"},legacy:{heartRateBpm:hr??72,prMs:164,qrsMs:92,qtcMs:438,rateClass:hr==null?"normal":hr<60?"bradycardia":hr>=100?"tachycardia":"normal",prClass:"normal",qrsClass:"narrow",qtcClass:"normal"},legacySources:{...measurementSources,heartRateBpm:assessment==="present"?"physician_measurement":"legacy_default",rateClass:assessment==="present"?"derived":"legacy_default"}})}
const na=()=>({value:null,assessment:"not_assessed"});const entered=value=>({value,assessment:"present"});const unknown=()=>({value:null,assessment:"unknown"});
function input(patch={}){return {enabled:false,measurements:measurements(),regularity:na(),variableRr:na(),pWavesPresent:na(),pBeforeEveryQrs:na(),qrsAfterEveryP:na(),legacy:{rateClass:"normal",regularity:"regular",variableRr:false,pWavesPresent:true,pBeforeEveryQrs:true,qrsAfterEveryP:true,sinusPattern:"sinus_pattern_supported"},legacySources:{rateClass:"legacy_default",regularity:"legacy_default",variableRr:"legacy_default",pWavesPresent:"legacy_default",pBeforeEveryQrs:"legacy_default",qrsAfterEveryP:"legacy_default"},...patch}}
const build=patch=>buildProductionCanonicalRateRhythm(input(patch));const value=x=>x.status==="present"?x.value:x.status;

test("B2-1 normal sinus-like state is supported",()=>{const x=build({measurements:measurements(75,"present"),regularity:entered("regular"),variableRr:entered(false),pWavesPresent:entered(true),pBeforeEveryQrs:entered(true),qrsAfterEveryP:entered(true)});assert.equal(value(x.canonical.rateClass),"normal");assert.equal(x.canonical.sinusPattern,"sinus_pattern_supported")});
test("B2-2 sinus tachy-like state stays descriptive",()=>{const x=build({measurements:measurements(120,"present"),regularity:entered("regular"),variableRr:entered(false),pWavesPresent:entered(true),pBeforeEveryQrs:entered(true),qrsAfterEveryP:entered(true)});assert.equal(value(x.canonical.rateClass),"tachycardia");assert.equal(x.canonical.sinusPattern,"sinus_pattern_supported");assert.equal("candidates" in x.canonical,false)});
test("B2-3 incomplete brady state keeps sinus uncertain",()=>{const x=build({measurements:measurements(50,"present")});assert.equal(value(x.canonical.rateClass),"bradycardia");assert.equal(x.canonical.sinusPattern,"sinus_pattern_uncertain")});
test("B2-4 irregular variable RR retains unassessed P waves",()=>{const x=build({measurements:measurements(110,"present"),regularity:entered("irregular"),variableRr:entered(true)});assert.equal(value(x.canonical.rateClass),"tachycardia");assert.equal(value(x.canonical.rhythm.regularity),"irregular");assert.equal(value(x.canonical.rhythm.variableRr),true);assert.equal(x.canonical.rhythm.pWavesPresent.status,"not_assessed")});
test("B2-5 explicitly absent P waves remain absent without AF output",()=>{const x=build({regularity:entered("irregular"),variableRr:entered(true),pWavesPresent:entered(false)});assert.equal(x.canonical.rhythm.pWavesPresent.status,"absent");assert.equal("candidates" in x.canonical,false)});
test("B2-6 unknown rhythm is never regular",()=>{const x=build({measurements:measurements(100,"present"),regularity:unknown(),variableRr:unknown()});assert.equal(value(x.canonical.rateClass),"tachycardia");assert.equal(x.canonical.rhythm.regularity.status,"unknown")});
test("B2-7 regularity can be entered while rate stays not assessed",()=>{const x=build({regularity:entered("regular"),variableRr:entered(false)});assert.equal(x.canonical.rateClass.status,"not_assessed");assert.equal(value(x.canonical.rhythm.regularity),"regular")});
test("B2-8 legacy false defaults do not become canonical absence",()=>{const x=build({});for(const field of [x.canonical.rhythm.variableRr,x.canonical.rhythm.pWavesPresent,x.canonical.rhythm.pBeforeEveryQrs,x.canonical.rhythm.qrsAfterEveryP])assert.equal(field.status,"not_assessed")});
test("B2-9 completely entered rhythm creates matching canonical state",()=>{const legacy={rateClass:"normal",regularity:"regular",variableRr:false,pWavesPresent:true,pBeforeEveryQrs:true,qrsAfterEveryP:true,sinusPattern:"sinus_pattern_supported"},x=build({measurements:measurements(75,"present"),regularity:entered("regular"),variableRr:entered(false),pWavesPresent:entered(true),pBeforeEveryQrs:entered(true),qrsAfterEveryP:entered(true),legacy,legacySources:{rateClass:"derived",regularity:"physician_category",variableRr:"derived",pWavesPresent:"physician_category",pBeforeEveryQrs:"physician_category",qrsAfterEveryP:"physician_category"}});assert.equal(x.summary.match,6);assert.equal(x.summary.majorFail,0)});
test("B2-10 conflicting regular rhythm and variable RR are retained for REVIEW",()=>{const x=build({regularity:entered("regular"),variableRr:entered(true)});assert.equal(value(x.canonical.rhythm.regularity),"regular");assert.equal(value(x.canonical.rhythm.variableRr),true);assert.equal(x.comparisons.find(v=>v.field==="regularityVariableRrConsistency").classification,"REVIEW")});

const production=patch=>{const x=createDefaultIntegratedInput();for(const [group,values] of Object.entries(patch))Object.assign(x[group],values);return buildIntegratedInterpretation(x)};
test("B2-11 AF fixture output is independent of B2 flag",()=>{const before=production({ecg:{atrialFibrillation:true,irregularTachycardia:true},clinical:{heartRate:130}});build({enabled:true,measurements:measurements(130,"present",true),regularity:entered("irregular"),variableRr:entered(true),pWavesPresent:entered(false)});assert.deepEqual(production({ecg:{atrialFibrillation:true,irregularTachycardia:true},clinical:{heartRate:130}}),before)});
test("B2-12 WCT and VT emergency output is independent of B2 flag",()=>{const patch={ecg:{wideTachycardia:true,avDissociation:true}},before=production(patch);build({enabled:true,measurements:measurements(160,"present",true),regularity:entered("regular")});assert.deepEqual(production(patch),before);assert.equal(before.urgency,"emergency")});
test("B2-13 severe brady emergency output is independent of B2 flag",()=>{const source=createDefaultBradyInput();Object.assign(source,{ventricularRateBpm:35,clinicianClassification:"sinus_bradycardia_candidate",adverseSigns:{...source.adverseSigns,syncope:true}});const before=interpretBradyarrhythmia(source);build({enabled:true,measurements:measurements(35,"present",true)});assert.deepEqual(interpretBradyarrhythmia(source),before);assert.equal(before.urgency,"emergency")});

test("B1 and B2 feature flags are parsed independently",()=>{assert.equal(canonicalRateRhythmEnabled(undefined),false);assert.equal(canonicalRateRhythmEnabled("true"),true)});
test("all four B1 B2 flag combinations preserve canonical B2 semantics",()=>{for(const [b1,b2] of [[false,false],[true,false],[true,true],[false,true]]){const x=buildProductionCanonicalRateRhythm({...input({measurements:measurements(75,"present",b1),regularity:entered("regular")}),enabled:b2});assert.equal(value(x.canonical.rateClass),"normal");assert.equal(x.dependency,"independent_canonical_builder")}});
test("B2 ON uses canonical unresolved state without legacy normal fallback",()=>{const x=buildProductionCanonicalRateRhythm({...input(),enabled:true});assert.equal(x.selected.rateClass.status,"not_assessed");assert.equal(x.selected.regularity.status,"not_assessed")});
test("B2 rollback restores legacy selection without corrupting canonical input",()=>{const source=input({measurements:measurements(50,"present"),regularity:unknown()}),snapshot=structuredClone(source),on=buildProductionCanonicalRateRhythm({...source,enabled:true}),off=buildProductionCanonicalRateRhythm({...source,enabled:false});assert.equal(on.selected.rateClass.value,"bradycardia");assert.equal(off.selected.rateClass,"normal");assert.deepEqual(source,snapshot)});
test("unknown and not assessed never coerce to absent normal or false",()=>{const x=build({regularity:unknown(),variableRr:unknown(),pWavesPresent:unknown(),pBeforeEveryQrs:unknown(),qrsAfterEveryP:unknown()});for(const field of Object.values(x.canonical.rhythm))assert.equal(field.status,"unknown");assert.equal(x.canonical.sinusPattern,"sinus_pattern_uncertain")});
test("P-QRS observations distinguish one-to-one from missing data",()=>{const complete=build({pBeforeEveryQrs:entered(true),qrsAfterEveryP:entered(true)}),missing=build({});assert.equal(value(complete.canonical.rhythm.pBeforeEveryQrs),true);assert.equal(value(complete.canonical.rhythm.qrsAfterEveryP),true);assert.equal(missing.canonical.rhythm.pBeforeEveryQrs.status,"not_assessed")});
test("Production source imports descriptive B2 state without candidate routing",()=>{const source=readFileSync(new URL("../components/ecg/EcgWorkspace.tsx",import.meta.url),"utf8");assert.match(source,/buildProductionCanonicalRateRhythm/);assert.doesNotMatch(source,/canonicalRateRhythmState\.(diagnosticCandidates|candidates|urgency|redFlags)/)});
test("B2 retains the 59 Rule Registry A-Final hash",()=>{assert.equal(ecgRuleRegistry.length,59);const snapshot=ecgRuleRegistry.map(rule=>({id:rule.id,priority:rule.priority,requiredInputs:rule.requiredInputs}));assert.equal(createHash("sha256").update(JSON.stringify(snapshot)).digest("hex"),"afc64fa3dfe62d554ca3e636c7f9257ba282b07f6cf8839589871f9e733ea23e")});
