import test from "node:test";import assert from "node:assert/strict";import {createHash} from "node:crypto";import {readFileSync} from "node:fs";
import {migrateCanonicalBasicRhythmCandidates} from "../logic/integration/migrate-canonical-basic-rhythm-candidates.js";import {migrateCanonicalConductionCandidates} from "../logic/integration/migrate-canonical-conduction-candidates.js";import {migrateCanonicalConductionEmergency} from "../logic/integration/migrate-canonical-conduction-emergency.js";import {migrateCanonicalStructural} from "../logic/integration/migrate-canonical-structural.js";import {migrateCanonicalQtElectrolyte} from "../logic/integration/migrate-canonical-qt-electrolyte.js";import {migrateCanonicalStTIschemia} from "../logic/integration/migrate-canonical-st-t-ischemia.js";
import {adaptRateRhythmToCanonical} from "../logic/shadow/adapt-rate-rhythm.js";import {adaptConductionToCanonical} from "../logic/shadow/adapt-conduction.js";import {adaptStructuralToCanonical} from "../logic/shadow/adapt-structural.js";import {adaptQtElectrolyteToCanonical} from "../logic/shadow/adapt-qt-electrolyte.js";import {adaptStTToCanonical} from "../logic/shadow/adapt-st-t.js";import {adaptClinicalReviewToCanonical} from "../logic/integration/adapt-clinical-review.js";import {createDefaultIntegratedInput} from "../data/integration/defaults.js";import {buildIntegratedInterpretation} from "../logic/integration/build-integrated-interpretation.js";import {ecgRuleRegistry} from "../data/rule-engine/rule-registry.js";
const a=value=>({assessed:true,value}),u=()=>({assessed:true,unknown:true}),rank={uncertain:0,routine:1,same_day:2,emergency:3,resuscitation:4};
function legacy(patch={}){const input=createDefaultIntegratedInput();for(const [group,values] of Object.entries(patch))Object.assign(input[group],values);return buildIntegratedInterpretation(input)}
const empty=()=>({rate:adaptRateRhythmToCanonical(),conduction:adaptConductionToCanonical(),structural:adaptStructuralToCanonical(),qt:adaptQtElectrolyteToCanonical(),st:adaptStTToCanonical()});
function all(base,shadows=empty(),flags={basic:true,conduction:true,emergency:true,structural:true,qt:true,st:true}){let result=base;result=migrateCanonicalBasicRhythmCandidates({enabled:flags.basic,legacyResult:result,shadowInput:shadows.rate}).result;result=migrateCanonicalConductionCandidates({enabled:flags.conduction,legacyResult:result,shadowInput:shadows.conduction}).result;result=migrateCanonicalConductionEmergency({enabled:flags.emergency,legacyResult:result,shadowInput:shadows.conduction}).result;result=migrateCanonicalStructural({enabled:flags.structural,legacyResult:result,shadowInput:shadows.structural}).result;result=migrateCanonicalQtElectrolyte({enabled:flags.qt,legacyResult:result,shadowInput:shadows.qt}).result;return migrateCanonicalStTIschemia({enabled:flags.st,legacyResult:result,shadowInput:shadows.st}).result}
const ids=r=>r.diagnosticCandidates.map(x=>x.id),noLoss=(base,out)=>base.diagnosticCandidates.every(x=>ids(out).includes(x.id))&&rank[out.urgency]>=rank[base.urgency]&&base.criticalFindings.every(x=>out.criticalFindings.some(y=>y.id===x.id));
const cases=[
 ["FINT-1 AF",{confirmedModules:["simplified-af"]}], ["FINT-2 Flutter",{}], ["FINT-3 SVT",{}], ["FINT-4 MAT",{}], ["FINT-5 Junctional",{}],
 ["FINT-6 Mobitz I",{ecg:{mobitzI:true}}], ["FINT-7 Mobitz II",{ecg:{mobitzII:true}}], ["FINT-8 High-grade",{ecg:{highGradeBlock:true}}], ["FINT-9 Complete AV block",{ecg:{completeBlock:true}}], ["FINT-10 Bifascicular",{ecg:{rbbb:true,rightAxis:true}}],
 ["FINT-11 VT WCT",{ecg:{wideTachycardia:true}}], ["FINT-12 Pre-excited AF",{ecg:{wideTachycardia:true,irregularTachycardia:true,preexcitation:true}}], ["FINT-13 Severe brady",{clinical:{hypotension:true},ecg:{bradycardia:true}}],
 ["FINT-14 Inferior ACS",{clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true,inferiorStElevation:true,reciprocalChange:true}}], ["FINT-15 Posterior",{clinical:{ischemicChestPain:true},ecg:{stDepressionV1toV3:true}}], ["FINT-16 Wellens",{clinical:{chestPainHistory:true},ecg:{wellensMorphology:true}}], ["FINT-17 Pericarditis",{}], ["FINT-18 Brugada",{clinical:{syncope:true},ecg:{v1Elevation:true}}],
 ["FINT-19 LBBB Sgarbossa",{clinical:{ischemicChestPain:true},ecg:{lbbb:true}}], ["FINT-20 Paced Sgarbossa",{clinical:{ischemicChestPain:true}}], ["FINT-21 Long QT",{ecg:{qtProlonged:true}}], ["FINT-22 TdP",{ecg:{qtProlonged:true,rOnT:true}}], ["FINT-23 Severe hyperK",{ecg:{peakedT:true,pWaveAbsent:true,wideQrs:true}}], ["FINT-24 Hypokalemia",{ecg:{flattenedT:true,prominentU:true,pvc:true}}],
 ["FINT-25 LV strain",{ecg:{wideQrs:true,anyStDepression:true}}], ["FINT-26 RV strain",{ecg:{rbbb:true,rightAxis:true,rvStrain:true}}], ["FINT-27 Acute right heart",{clinical:{severeHypoxia:true,dyspnea:true},ecg:{rbbb:true,rightAxis:true,rvStrain:true}}], ["FINT-28 Giant negative T",{ecg:{giantNegativeT:true}}], ["FINT-29 incomplete",{indeterminateFindingIds:["st-change"]}], ["FINT-30 normal noise",{}]
];
for(const [name,patch] of cases)test(`${name} full ON preserves legacy safety`,()=>{const base=legacy(patch),out=all(base);assert.ok(noLoss(base,out))});
test("cross A WCT and hyperK coexist",()=>{const base=legacy({ecg:{wideTachycardia:true}}),s=empty();s.qt=adaptQtElectrolyteToCanonical({qrsMs:150,qrsAssessment:"present",context:{wideTachycardia:a(true),peakedT:a(true),potassiumHigh:a(true)}});const out=all(base,s);assert.ok(ids(out).includes("wide-qrs-tachycardia"));assert.ok(ids(out).includes("hyperkalemia-pattern"))});
test("cross C Mobitz II canonical emergency coexists",()=>{const base=legacy({clinical:{syncope:true},ecg:{mobitzII:true,wideQrs:true}}),s=empty();s.conduction=adaptConductionToCanonical({qrsMs:140,qrsAssessment:"present",conduction:{droppedQrs:a(true),fixedPrBeforeDrop:a(true),progressivePr:a(false),syncope:a(true)}});assert.ok(noLoss(base,all(base,s)))});
test("cross F TdP and severe brady coexist",()=>{const base=legacy({clinical:{hypotension:true,syncope:true},ecg:{bradycardia:true,qtProlonged:true,rOnT:true}}),s=empty();s.qt=adaptQtElectrolyteToCanonical({heartRateBpm:35,heartRateAssessment:"present",qtcMs:540,qtcAssessment:"present",context:{rOnT:a(true),syncope:a(true)}});assert.ok(noLoss(base,all(base,s)))});
test("cross H RV structural candidates coexist",()=>{const base=legacy({clinical:{severeHypoxia:true,dyspnea:true},ecg:{rbbb:true,rightAxis:true,rvStrain:true}}),s=empty();s.structural=adaptStructuralToCanonical({heartRateBpm:120,heartRateAssessment:"present",qrsMs:140,qrsAssessment:"present",clinical:{dyspnea:a(true)},conduction:{axis:a("right"),rbbbMorphology:a(true)},context:{rightPrecordialTInversion:a(true)}});assert.ok(noLoss(base,all(base,s)))});
test("cross J afebrile Brugada remains visible",()=>{const s=empty();s.st=adaptStTToCanonical({stMeasurements:[{lead:"V1",direction:"elevation",clinicianConfirmed:true},{lead:"V2",direction:"elevation",clinicianConfirmed:true}],context:{stMorphology:a("coved"),fever:a(false)}});assert.ok(ids(all(legacy(),s)).includes("brugada-pattern"))});
test("N-F1 normal-ish input creates no dangerous canonical candidate",()=>{const out=all(legacy(),empty());assert.equal(out.criticalFindings.length,0)});
test("N-F2 single peaked T does not create severe candidate",()=>{const s=empty();s.qt=adaptQtElectrolyteToCanonical({context:{peakedT:a(true)}});assert.equal(all(legacy(),s).criticalFindings.length,0)});
test("N-F3 single left axis creates no LAFB LVH",()=>{const s=empty();s.structural=adaptStructuralToCanonical({conduction:{axis:a("left")}});assert.ok(!ids(all(legacy(),s)).some(x=>["lafb-pattern","lvh-pattern"].includes(x)))});
test("N-F4 single ST lead does not strongly create ACS",()=>{const s=empty();s.st=adaptStTToCanonical({stMeasurements:[{lead:"V2",direction:"elevation",clinicianConfirmed:true}]});assert.ok(!all(legacy(),s).criticalFindings.some(x=>x.id==="acute-coronary-occlusion"))});
test("N-F5 QT prolonged alone is not TdP Emergency",()=>{const s=empty();s.qt=adaptQtElectrolyteToCanonical({qtcMs:520,qtcAssessment:"present"});const out=all(legacy(),s);assert.ok(ids(out).includes("long-qt"));assert.ok(!out.criticalFindings.some(x=>x.id==="tdp-risk"))});
test("I-F1 categorical wide without ms leaks no pseudo measurement",()=>{const s=adaptClinicalReviewToCanonical({qrsCategory:"wide",qrsCategoryAssessment:"present",qrsAssessment:"not_assessed"});assert.equal(s.measurements.qrsMs.status,"not_assessed");assert.equal(s.categorical.qrsWidth.value,"wide")});
test("I-F2 incomplete ST retains non-normal reciprocal and unknown symptom",()=>{const s=adaptStTToCanonical({stMeasurements:[{lead:"V2",direction:"elevation",clinicianConfirmed:true},{lead:"V3",direction:"elevation",clinicianConfirmed:true}],context:{ischemicChestPain:u()}});assert.ok(["unknown","not_assessed"].includes(s.derived.reciprocalPattern.status));assert.equal(s.ischemicChestPain.status,"unknown")});
test("I-F3 unknown AV dissociation does not confirm block",()=>{const s=empty();s.conduction=adaptConductionToCanonical({heartRateBpm:35,heartRateAssessment:"present",conduction:{avDissociation:u()}});assert.ok(!all(legacy({ecg:{bradycardia:true}}),s).criticalFindings.some(x=>x.id==="advanced-av-block"))});
test("I-F4 unknown QT plus PVC is not normal QT",()=>{const s=adaptQtElectrolyteToCanonical({qtcAssessment:"indeterminate",context:{pvc:a(true)}});assert.ok(["unknown","not_assessed"].includes(s.qtcClass.status));assert.notEqual(s.qtcClass.value,"normal")});
test("I-F5 unknown axis and pacing are not defaults",()=>{const s=adaptStructuralToCanonical({conduction:{axis:u()},clinical:{pacemaker:u()}});assert.equal(s.axis.status,"unknown");assert.equal(s.pacemaker.status,"unknown")});
test("all OFF returns exact legacy reference",()=>{const base=legacy({ecg:{qtProlonged:true}}),off={basic:false,conduction:false,emergency:false,structural:false,qt:false,st:false};assert.equal(all(base,empty(),off),base)});
for(const key of ["basic","conduction","emergency","structural","qt","st"])test(`only ${key} flag has no dependency crash`,()=>{const flags={basic:false,conduction:false,emergency:false,structural:false,qt:false,st:false,[key]:true};assert.ok(all(legacy(),empty(),flags))});
test("all ON then OFF restores exact legacy without mutation",()=>{const base=legacy({ecg:{qtProlonged:true,rOnT:true}}),copy=structuredClone(base);all(base);assert.equal(all(base,empty(),{basic:false,conduction:false,emergency:false,structural:false,qt:false,st:false}),base);assert.deepEqual(base,copy)});
test("partial B6 rollback keeps earlier canonical domains",()=>{const s=empty();s.qt=adaptQtElectrolyteToCanonical({qtcMs:520,qtcAssessment:"present"});s.st=adaptStTToCanonical({stMeasurements:[{lead:"V2",direction:"elevation",clinicianConfirmed:true},{lead:"V3",direction:"elevation",clinicianConfirmed:true}],context:{ischemicChestPain:a(true)}});const on=all(legacy(),s),off=all(legacy(),s,{basic:true,conduction:true,emergency:true,structural:true,qt:true,st:false});assert.ok(ids(on).includes("long-qt"));assert.ok(ids(off).includes("long-qt"));assert.ok(!ids(off).includes("acute-coronary-occlusion"))});
test("global duplicate and Rule ID audit",()=>{const out=all(legacy({clinical:{ischemicChestPain:true},ecg:{contiguousStElevation:true,qtProlonged:true,rOnT:true}}));for(const xs of [out.diagnosticCandidates,out.criticalFindings])for(const key of ["id","label"]){const values=xs.map(x=>x[key]);assert.equal(values.length,new Set(values).size)}for(const c of out.diagnosticCandidates)assert.equal(c.ruleIds.length,new Set(c.ruleIds).size)});
test("no pseudo defaults leak from empty adapters",()=>{const s=empty();for(const x of [s.rate.rateClass,s.rate.qrsWidth,s.conduction.prMs,s.conduction.qrsWidth,s.qt.qtcMs,s.structural.axis])assert.equal(x.status,"not_assessed")});
test("Rule Registry remains 59 and A-Final hash matches",()=>{assert.equal(ecgRuleRegistry.length,59);const snapshot=ecgRuleRegistry.map(rule=>({id:rule.id,priority:rule.priority,requiredInputs:rule.requiredInputs}));assert.equal(createHash("sha256").update(JSON.stringify(snapshot)).digest("hex"),"afc64fa3dfe62d554ca3e636c7f9257ba282b07f6cf8839589871f9e733ea23e")});
test("Production UI surface remains unchanged and all eight flags are server wired",()=>{const page=readFileSync("app/page.tsx","utf8"),workspace=readFileSync("components/ecg/EcgWorkspace.tsx","utf8");for(const name of ["MEASUREMENTS","RATE_RHYTHM","BASIC_RHYTHM_CANDIDATES","CONDUCTION_CANDIDATES","CONDUCTION_EMERGENCY","STRUCTURAL","QT_ELECTROLYTE","ST_T_ISCHEMIA"])assert.match(page,new RegExp(`ECG_CANONICAL_${name}_ENABLED`));assert.match(workspace,/SimplifiedClinicalReview/);assert.match(workspace,/advanced-analysis/)});
