import test from "node:test";
import assert from "node:assert/strict";
import {evaluateQuality} from "../logic/quality/quality.js";
import {placementWarnings} from "../logic/lead-placement/placement.js";
import {createDefaultIntegratedInput} from "../data/integration/defaults.js";
import {buildIntegratedInterpretation} from "../logic/integration/build-integrated-interpretation.js";
import {createDefaultStInput} from "../data/st-interpretation/defaults.js";
import {interpretStChanges} from "../logic/st-interpretation/interpret-st.js";
import {createDefaultTWaveInput} from "../data/t-wave-interpretation/defaults.js";
import {interpretTWave} from "../logic/t-wave-interpretation/interpret-t-wave.js";
import {createDefaultConductionInput} from "../data/conduction-interpretation/defaults.js";
import {interpretConduction} from "../logic/conduction-interpretation/interpret-conduction.js";
import {createDefaultElectrolyteInput} from "../data/electrolyte-interpretation/defaults.js";
import {interpretElectrolytes} from "../logic/electrolyte-interpretation/interpret-electrolytes.js";
import {classifyTachyarrhythmia} from "../logic/tachyarrhythmia/classify.js";
import {createDefaultBradyInput} from "../data/bradyarrhythmia/defaults.js";
import {interpretBradyarrhythmia} from "../logic/bradyarrhythmia/interpret-brady.js";

const quality={allLeads:true,leadLabels:true,waveformsComplete:true,speedVisible:true,gainVisible:true,gridVisible:true,inFocus:true,lowBlur:true,noGlare:true,noShadow:true,lowTilt:true,lowPerspective:true,multipleBeats:true,privacyChecked:true};
const tachyBase={heartRate:150,qrsMs:90,regularity:"regular",pWave:"unknown",avRelationship:"unknown",deltaWave:false,shortPr:false,fibrillatoryWaves:false,flutterWaves:false,flutterConduction:"unknown",pulsePresent:true,systolicBp:120,hypotension:false,alteredMentalStatus:false,shockSigns:false,ischemicChestPain:false,acuteHeartFailure:false,pulmonaryEdema:false,severeRespiratoryFailure:false,syncope:false,markedPresyncope:false,organHypoperfusion:false,wpwHistory:false,qrsMorphologyVariable:false,priorMi:false,structuralHeartDisease:false,sinusFeatures:false,qtcMs:null,potassium:null,calcium:null,magnesium:null};
function prechecks(){assert.equal(evaluateQuality(quality).grade,"A");assert.deepEqual(placementWarnings({raLaReversal:false,v1v2High:false}),[])}
function integrated(patch={}){const x=createDefaultIntegratedInput();for(const [group,values] of Object.entries(patch))Object.assign(x[group],values);return x}
function ids(result){return result.diagnosticCandidates.map(x=>x.id)}
function setSt(input,leads,direction,amplitude=2){for(const lead of leads){const m=input.leadMeasurements.find(x=>x.lead===lead);Object.assign(m,{direction,amplitudeMm:amplitude,measurementPoint:"j_point",clinicianConfirmed:true})}}
function confirmRemainingSt(input){for(const m of input.leadMeasurements)if(!m.clinicianConfirmed)Object.assign(m,{direction:"isoelectric",amplitudeMm:0,measurementPoint:"j_point",baselineReference:"tp_segment",clinicianConfirmed:true})}

test("clinical case 01 normal sinus rhythm",()=>{prechecks();const ai=buildIntegratedInterpretation(integrated());assert.equal(ai.criticalFindings.length,0);const physician={...ai};assert.equal(physician.urgency,"routine");assert.deepEqual(physician.todaysPlan.map(x=>x.id),["observation"]);assert.equal(physician.conflictingFindings.length,0);assert.match(physician.summaryText.join(" "),/緊急性の高い所見は抽出されていません/)});

test("clinical case 02 anterior STEMI pattern recalculates after physician-confirmed V1-V4 changes",()=>{prechecks();const st=createDefaultStInput();assert.equal(interpretStChanges(st).urgency,"routine");setSt(st,["V1","V2","V3","V4"],"elevation",3);st.reciprocalFinding={status:"present",leads:["II","III","aVF"],amplitudeMm:1,dynamicChange:true};st.clinical.ischemicSymptoms=true;const confirmed=interpretStChanges(st);assert.equal(confirmed.urgency,"emergency");const result=buildIntegratedInterpretation(integrated({clinical:{ischemicChestPain:true,dynamicChange:true},ecg:{contiguousStElevation:true,reciprocalChange:true,hyperacuteT:true}}));assert.equal(result.diagnosticCandidates[0].id,"acute-coronary-occlusion");assert.equal(result.urgency,"emergency");assert.ok(result.todaysPlan.some(x=>x.id==="urgent-ischemia"));assert.match(result.diagnosticCandidates[0].limitations.join(" "),/PCI適応を自動確定しません/)});

test("clinical case 03 inferior STEMI with suspected RV involvement and bradycardia",()=>{prechecks();const before=buildIntegratedInterpretation(integrated());assert.equal(ids(before).includes("inferior-rv-conduction"),false);const result=buildIntegratedInterpretation(integrated({clinical:{hypotension:true},ecg:{inferiorStElevation:true,bradycardia:true,mobitzI:true}}));assert.equal(result.urgency,"emergency");assert.equal(result.diagnosticCandidates[0].id,"inferior-rv-conduction");assert.ok(result.todaysPlan.some(x=>x.id==="right-leads"&&x.label.includes("V4R")));assert.ok(result.missingInformation.some(x=>x.id==="v4r"))});

test("clinical case 04 Wellens warning persists with negative troponin after physician correction",()=>{prechecks();const t=createDefaultTWaveInput();t.clinical.chestPainHistory=true;t.clinical.currentlyPainFree=true;t.clinical.troponinNegative=true;for(const lead of ["V2","V3"]){const m=t.leadMeasurements.find(x=>x.lead===lead);Object.assign(m,{morphology:"biphasic",polarity:"biphasic_positive_negative",symmetry:"symmetric",clinicianConfirmed:true})}const tw=interpretTWave(t,{stResult:interpretStChanges(createDefaultStInput())});assert.match(tw.wellensPattern,/type_a_candidate/);const result=buildIntegratedInterpretation(integrated({clinical:{chestPainHistory:true,currentlyPainFree:true,troponinNegative:true},ecg:{wellensMorphology:true}}));assert.ok(ids(result).includes("wellens-pattern"));assert.equal(result.urgency,"emergency");assert.match(result.diagnosticCandidates.find(x=>x.id==="wellens-pattern").limitations.join(" "),/トロポニン陰性/)});

test("clinical case 05 LBBB limits ordinary ST interpretation and transparently reports Sgarbossa gap",()=>{prechecks();const c=createDefaultConductionInput();Object.assign(c,{qrsDurationMs:150,v1DeepWideS:true,broadNotchedR_V5V6:true,lateralQWaveAbsent:true,clinicianConfirmed:true});const conduction=interpretConduction(c);assert.equal(conduction.classification,"lbbb_candidate");assert.equal(conduction.stTInterpretationLimited,true);const st=createDefaultStInput();st.qrsContext=conduction.qrsContext;st.clinical.age=70;st.clinical.sex="male";setSt(st,["V2","V3"],"elevation",2);confirmRemainingSt(st);const result=interpretStChanges(st);assert.equal(result.overallClassification,"secondary_repolarization_change");assert.ok(result.warnings.some(x=>x.includes("二次性ST")));assert.ok(conduction.limitations.some(x=>x.includes("Sgarbossa")));assert.ok(conduction.clinicalPearls.some(x=>x.includes("ST評価は困難")))});

test("clinical case 06 severe hyperkalemia pattern is Red Flag and recalculates with physician confirmation",()=>{prechecks();const x=createDefaultElectrolyteInput();Object.assign(x,{peakedT:true,pWaveAbsent:true,qrsProlonged:true,wideQrs:true});const electrolyte=interpretElectrolytes(x);assert.equal(electrolyte.assessments.hyperkalemia.level,"suspicious");assert.equal(electrolyte.urgency,"emergency");assert.match(electrolyte.assessments.hyperkalemia.clinicalPearl,/正常ECGでも/);const result=buildIntegratedInterpretation(integrated({ecg:{peakedT:true,pWaveAbsent:true,qrsProlonged:true,wideQrs:true}}));assert.equal(result.urgency,"emergency");assert.match(result.diagnosticCandidates.find(x=>x.id==="hyperkalemia-pattern").label,/重症高K/);assert.ok(result.todaysPlan.some(x=>x.id==="potassium"))});

test("clinical case 07 hypokalemia pattern with PVC or R-on-T prioritizes monitoring",()=>{prechecks();const x=createDefaultElectrolyteInput();Object.assign(x,{stDepression:true,flattenedT:true,prominentU:true,quProlongation:true,pvc:true,rOnT:true});const electrolyte=interpretElectrolytes(x);assert.equal(electrolyte.assessments.hypokalemia.level,"suspicious");assert.match(electrolyte.assessments.hypokalemia.clinicalPearl,/U波/);const result=buildIntegratedInterpretation(integrated({ecg:{flattenedT:true,prominentU:true,quProlonged:true,pvc:true,rOnT:true,qtProlonged:true}}));assert.ok(ids(result).includes("low-k-mg-pattern"));assert.ok(ids(result).includes("tdp-risk"));assert.ok(result.todaysPlan.some(x=>x.id==="monitor"));assert.equal(result.todaysPlan.filter(x=>x.id==="monitor").length,1)});

test("clinical case 08 atrial fibrillation remains narrow and has appropriate plan",()=>{prechecks();const ai=classifyTachyarrhythmia({...tachyBase,regularity:"irregular",pWave:"unknown"});assert.notEqual(ai.overallClassification,"atrial_fibrillation_candidate");const confirmed=classifyTachyarrhythmia({...tachyBase,regularity:"irregular",pWave:"absent",fibrillatoryWaves:true,clinicianClassification:"atrial_fibrillation_candidate"});assert.equal(confirmed.qrsClass,"narrow");assert.equal(confirmed.overallClassification,"atrial_fibrillation_candidate");assert.match(confirmed.priority,/心房細動/);for(const item of ["継続モニター","症状・血圧・意識・SpO₂を再評価","12誘導心電図を再検","K・Ca・Mgを確認"])assert.ok(confirmed.plan.includes(item));assert.equal(confirmed.redFlags.length,0);assert.ok(confirmed.clinicalPearls.length)});

test("clinical case 09 AVNRT candidate appears after short-RP physician correction",()=>{prechecks();const ai=classifyTachyarrhythmia({...tachyBase,pWave:"unknown"});assert.notEqual(ai.overallClassification,"avnrt_candidate");const confirmed=classifyTachyarrhythmia({...tachyBase,pWave:"retrograde",shortRp:true,abruptOnset:true,clinicianClassification:"avnrt_candidate"});assert.equal(confirmed.classification,"narrow regular");assert.equal(confirmed.overallClassification,"avnrt_candidate");assert.match(confirmed.priority,/AVNRT/);assert.equal(confirmed.redFlags.length,0);assert.ok(confirmed.missing.includes("K"));assert.ok(confirmed.clinicalPearls.length)});

test("clinical case 10 complete AV block with escape rhythm is high urgency after physician correction",()=>{prechecks();const x=createDefaultBradyInput();Object.assign(x,{ventricularRateBpm:32,atrialRateBpm:78,pToQrsRelationship:"av_dissociation",escapeRhythm:"ventricular_escape",qrsWidthMs:160,clinicianClassification:"complete_av_block_candidate"});const brady=interpretBradyarrhythmia(x);assert.equal(brady.classification,"complete_av_block_candidate");assert.equal(brady.urgency,"emergency");assert.ok(brady.redFlags.length);assert.ok(brady.pacingEvaluation.length);assert.ok(brady.clinicalPearls.length);const result=buildIntegratedInterpretation(integrated({clinical:{syncope:true},ecg:{completeBlock:true,avDissociation:true,wideEscape:true,atrialRate:78,ventricularRate:32}}));assert.equal(result.urgency,"emergency");assert.equal(result.diagnosticCandidates[0].id,"advanced-av-block");assert.ok(result.todaysPlan.some(x=>x.id==="acute-brady"))});
