import test from "node:test";
import assert from "node:assert/strict";
import {evaluateConnectedBeatSeries} from "../lib/ecg-features/local/local-poc.js";

const grid={detected:true,xPeriod:10,yPeriod:10};
function candidate(x,clusterId,overrides={}){return {source:"connected_component",componentId:`c${clusterId}`,clusterId,x,y:50,amplitude:30,prominence:30,height:25,width:2,area:40,quality:"adequate",limitations:[],...overrides}}
function connected(xs,overrides={}){const rPeakCandidates=xs.map((x,index)=>candidate(x,index));return {quality:"limited",rPeakCandidates,qrsCandidates:[...rPeakCandidates],qrsClusters:rPeakCandidates.map(item=>({id:item.clusterId})),...overrides}}

test("CC candidates are sorted by x before interval evaluation",()=>{const audit=evaluateConnectedBeatSeries(connected([300,100,200]),grid,{paperSpeedMmPerSecond:25});assert.deepEqual(audit.candidates.map(item=>item.x),[100,200,300])});
test("CC RR pixel intervals are calculated",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25});assert.deepEqual(audit.pixelIntervals,[100,100,100,100])});
test("confirmed 25 mm per second converts the detected 5 mm grid period to milliseconds",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25});assert.equal(audit.millisecondsPerPixel,20);assert.equal(audit.timeCalibration.gridSpacingMm,5);assert.deepEqual(audit.rrIntervalsMs,[2000,2000,2000,2000])});
test("unconfirmed speed never creates millisecond intervals",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid);assert.equal(audit.millisecondsPerPixel,null);assert.deepEqual(audit.rrIntervalsMs,[])});
test("near duplicate beat remains recorded and is rejected",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,205,300,400,500]),grid,{paperSpeedMmPerSecond:25});assert.equal(audit.duplicateCount,1);assert.ok(audit.candidates.some(item=>item.rejectionReason==="duplicate_beat_suspected"))});
test("long interval is retained as missing beat suspicion",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,500,600,700]),grid,{paperSpeedMmPerSecond:25});assert.equal(audit.missingBeatCount,1);assert.ok(audit.candidates.some(item=>item.missingBeatSuspectedAfter))});
test("RR outliers are counted without deleting the interval",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,440,540,640]),grid,{paperSpeedMmPerSecond:25});assert.ok(audit.outlierCount>=1);assert.ok(audit.pixelIntervals.includes(140))});
test("median mean minimum maximum and IQR are auditable",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25});assert.equal(audit.medianRrMs,2000);assert.equal(audit.meanRrMs,2000);assert.equal(audit.minRrMs,2000);assert.equal(audit.maxRrMs,2000);assert.equal(audit.iqrMs,0)});
test("adequate gated series produces a candidate heart rate",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25});assert.equal(audit.quality,"adequate");assert.equal(audit.heartRateBpm,30)});
test("quality failure keeps heart rate null",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid);assert.notEqual(audit.quality,"adequate");assert.equal(audit.heartRateBpm,null)});
test("insufficient R candidates keep regularity indeterminate",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300]),grid,{paperSpeedMmPerSecond:25});assert.equal(audit.regularity,"indeterminate");assert.equal(audit.heartRateBpm,null)});
test("regularity output is only image-level regular irregular or indeterminate",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25});assert.equal(audit.regularity,"regular");assert.ok(!["regularly_irregular","irregularly_irregular"].includes(audit.regularity))});
test("connected component and centerline sources remain distinct",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25,centerlinePeaks:[{x:100},{x:300}]});assert.equal(audit.source,"connected_component");assert.deepEqual(audit.centerlineAgreement,{matched:2,total:5})});
test("centerline disagreement alone does not silently reject CC candidates",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25,centerlinePeaks:[]});assert.equal(audit.acceptedCount,5);assert.ok(audit.limitations.some(item=>item.includes("cross-check")))});
test("overlay audit retains component cluster morphology and limitations",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25});const item=audit.candidates[0];assert.equal(item.componentId,"c0");assert.equal(item.clusterId,0);assert.equal(item.height,25);assert.equal(item.width,2);assert.equal(item.area,40);assert.deepEqual(item.limitations,[])});
test("poor QRS candidate quality prevents HR adoption",()=>{const input=connected([100,200,300,400,500]);input.rPeakCandidates=input.rPeakCandidates.map(item=>({...item,quality:"limited"}));const audit=evaluateConnectedBeatSeries(input,grid,{paperSpeedMmPerSecond:25});assert.equal(audit.heartRateBpm,null);assert.equal(audit.quality,"limited")});
test("missing grid calibration prevents HR adoption",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),{detected:false,xPeriod:10,yPeriod:10},{paperSpeedMmPerSecond:25});assert.equal(audit.timeCalibration.confirmed,false);assert.equal(audit.heartRateBpm,null)});
test("CC beat audit does not contain Rule Context or a diagnosis",()=>{const audit=evaluateConnectedBeatSeries(connected([100,200,300,400,500]),grid,{paperSpeedMmPerSecond:25});assert.equal("context" in audit,false);assert.equal("diagnosis" in audit,false);assert.equal("ruleResult" in audit,false)});
