import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const route=fs.readFileSync("app/api/ecg/analyze/route.ts","utf8");
const workspace=fs.readFileSync("components/ecg/EcgWorkspace.tsx","utf8");
const simplifiedReview=fs.readFileSync("components/ecg/SimplifiedClinicalReview.tsx","utf8");
const cropper=fs.readFileSync("components/ecg/EcgImageCropper.tsx","utf8");
const processing=fs.readFileSync("lib/ecg-image/client-image-processing.ts","utf8");
const localAdapter=fs.readFileSync("lib/ecg-image/local-ecg-image-analysis-adapter.ts","utf8");
const manifest=JSON.parse(fs.readFileSync("public/models/ecg/manifest.json","utf8"));
const css=fs.readFileSync("app/globals.css","utf8");
const packageJson=JSON.parse(fs.readFileSync("package.json","utf8"));

test("normal workflow never constructs API or OpenAI adapter",()=>{assert.doesNotMatch(workspace,/ApiEcgImageAnalysisAdapter|OpenAIEcgImageAnalysisProvider|\/api\/ecg\/analyze/);assert.match(workspace,/OnnxLocalEcgImageAnalysisAdapter/)});
test("retired analysis route is 410 Gone",()=>{assert.match(route,/errorResponse\(410/);assert.doesNotMatch(route,/request\.formData|arrayBuffer|service\.analyze|OpenAI/)});
test("image selection creates browser preview",()=>{assert.match(workspace,/URL\.createObjectURL\(next\)/);assert.match(workspace,/originalPreview/)});
test("crop processing remains in browser",()=>{assert.match(cropper,/createProcessedEcgFile/);assert.doesNotMatch(cropper,/fetch\(/)});
test("90 degree rotation remains available",()=>assert.match(cropper,/右へ90度回転/));
test("missing local model returns explicit error",()=>{assert.match(localAdapter,/LOCAL_MODEL_NOT_AVAILABLE/);assert.match(localAdapter,/if\(!this\.manifest\.modelAvailable/)});
test("missing model still offers physician input",()=>{assert.match(workspace,/医師入力で続ける/);assert.match(workspace,/continueManually/)});
test("manual values start empty",()=>assert.match(workspace,/aiValue:"",clinicianValue:""/));
test("no fixed normal value is inserted",()=>{assert.doesNotMatch(workspace,/aiValue:"(?:正常|洞調律|72 bpm)/);assert.match(workspace,/固定値や疑似所見は使用しません/)});
test("physician values recalculate existing engine",()=>{assert.match(workspace,/confirmedValue/);assert.match(workspace,/buildIntegratedInterpretation/);assert.match(simplifiedReview,/>解析する<\/button>/)});
test("WebGPU is preferred in a secure supported context",()=>assert.match(localAdapter,/"gpu" in navigator&&globalThis\.isSecureContext/));
test("WASM is the local CPU fallback",()=>{assert.match(localAdapter,/typeof WebAssembly!=="undefined"/);assert.match(localAdapter,/return "wasm"/)});
test("OpenAI environment variables are absent from normal path",()=>{assert.doesNotMatch(workspace,/OPENAI_|ECG_IMAGE_ANALYSIS_PROVIDER/);assert.doesNotMatch(localAdapter,/OPENAI_|ECG_IMAGE_ANALYSIS_PROVIDER/)});
test("no image network upload exists in normal path",()=>{assert.doesNotMatch(workspace,/fetch\([^)]*image|FormData|body\.append/);assert.match(localAdapter,/fetch\("\/models\/ecg\/manifest\.json"/)});
test("Blob URLs are released",()=>assert.match(workspace,/URL\.revokeObjectURL/));
test("PIN gate remains outside workspace",()=>{const gate=fs.readFileSync("components/auth/EcgAuthGate.tsx","utf8");assert.match(gate,/if\(authenticated\).*EcgWorkspace/s)});
test("Version 2 workspace appears after PIN authentication",()=>{const gate=fs.readFileSync("components/auth/EcgAuthGate.tsx","utf8");assert.match(gate,/<EcgWorkspace/);assert.match(workspace,/>Version 2</)});
test("existing clinical test suite remains included",()=>assert.equal(packageJson.scripts.test,"node --test tests/*.test.mjs"));
test("manifest does not claim a model exists",()=>{assert.equal(manifest.modelAvailable,false);assert.equal(manifest.validatedForClinicalUse,false);assert.deepEqual(manifest.supportedFindings,[])});
test("ONNX Runtime Web is installed",()=>assert.ok(packageJson.dependencies["onnxruntime-web"]));
test("runtime is dynamically loaded only behind model support",()=>{assert.match(localAdapter,/await import\("onnxruntime-web\/webgpu"\)/);assert.ok(localAdapter.indexOf("if(!support.supported)")<localAdapter.indexOf("await import"))});
test("manual UI contains all requested findings",()=>{for(const label of ["心拍数","リズム","P波","PR","QRS幅","QT / QTc","軸","R波進行","Q波","ST変化","T波","U波","PVC","R on T候補","脚ブロック候補","房室ブロック","ペーシング","電極装着異常"])assert.match(workspace,new RegExp(`label:\"${label.replace("/","\\/")}`))});
test("original and processed image state remain separate",()=>{assert.match(workspace,/originalFile/);assert.match(workspace,/processedFile/);assert.match(workspace,/useOriginalImage/)});
test("image compression stays finite and local",()=>{assert.match(processing,/MAX_COMPRESSION_ATTEMPTS/);assert.doesNotMatch(processing,/fetch\(/)});
test("mobile preview remains single column",()=>assert.match(css,/@media\(max-width:720px\).*\.upload-preview\{grid-template-columns:1fr\}/s));
test("normal UI states that the image is optional reference-only and not persisted",()=>{assert.match(workspace,/画像は任意の参照用/);assert.match(workspace,/画像は永続保存しません/)});
