import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {createReviewState,evaluateReviewNavigator,reviewProgress} from "../logic/review-navigator/evaluate-review.js";

const ids=["quality","rate","pwave","pr","qrs","axis","rwave","qwave","st","twave","uwave","qt","ectopy","summary"];
const state=()=>createReviewState(ids);
const abnormal=(s,id,values={})=>{s.steps[id]={status:"abnormal",completed:true,values};return s};
test("all 14 steps start unreviewed",()=>{const s=state();assert.equal(Object.keys(s.steps).length,14);for(const x of Object.values(s.steps))assert.equal(x.status,"unreviewed")});
test("unreviewed is not treated as normal",()=>assert.ok(evaluateReviewNavigator(state()).exclusions.length>=7));
test("explicit step completion advances progress",()=>{const s=state();s.steps.quality.completed=true;assert.deepEqual(reviewProgress(s),{completed:1,total:14,hasUnreviewed:true})});
test("all completed steps clear incomplete progress",()=>{const s=state();for(const x of Object.values(s.steps))x.completed=true;assert.equal(reviewProgress(s).hasUnreviewed,false)});
test("inferior ST elevation proposes V4R",()=>assert.ok(evaluateReviewNavigator(abnormal(state(),"st",{inferiorElevation:true})).suggestions.some(x=>x.includes("V4R"))));
test("posterior pattern proposes V7-V9",()=>{const s=abnormal(abnormal(state(),"st",{v1v3Depression:true}),"rwave",{tallRv1v3:true});assert.ok(evaluateReviewNavigator(s).suggestions.some(x=>x.includes("V7～V9")))});
test("RBBB and V1-V3 elevation proposes placement and Brugada checks",()=>{const s=abnormal(abnormal(state(),"qrs",{rbbb:true}),"st",{v1v3Elevation:true});const text=evaluateReviewNavigator(s).suggestions.join(" ");assert.match(text,/V1／V2/);assert.match(text,/Brugada/)});
test("QT plus PVC proposes R on T and electrolytes",()=>{const s=abnormal(abnormal(state(),"qt",{prolonged:true,qtcEntered:true}),"ectopy",{pvc:true});const text=evaluateReviewNavigator(s).suggestions.join(" ");assert.match(text,/R on T/);assert.match(text,/低K／低Mg／低Ca/)});
test("absent P and sinus rhythm is contradictory",()=>{const s=abnormal(abnormal(state(),"pwave",{absent:true}),"rate",{sinusRhythm:true});assert.match(evaluateReviewNavigator(s).contradictions[0].message,/P波なし/)});
test("narrow QRS and bundle branch block is contradictory",()=>{const s=abnormal(state(),"qrs",{narrow:true,lbbb:true});assert.match(evaluateReviewNavigator(s).contradictions[0].message,/narrow QRS/)});
test("regular and irregularly irregular is contradictory",()=>{const s=abnormal(state(),"rate",{regular:true,irregularlyIrregular:true});assert.ok(evaluateReviewNavigator(s).contradictions.length)});
test("QT prolongation without QTc is contradictory",()=>{const s=abnormal(state(),"qt",{prolonged:true});assert.match(evaluateReviewNavigator(s).contradictions[0].message,/QTc未入力/)});
test("R on T without PVC is contradictory",()=>{const s=abnormal(state(),"ectopy",{rOnT:true});assert.match(evaluateReviewNavigator(s).contradictions[0].message,/PVC/)});
test("limb reversal and confirmed axis is contradictory",()=>{const s=abnormal(abnormal(state(),"quality",{limbReversal:true}),"axis",{confirmed:true});assert.ok(evaluateReviewNavigator(s).contradictions.length)});
test("emergency finding appears before all steps complete",()=>{const s=abnormal(state(),"pr",{completeBlock:true});assert.ok(evaluateReviewNavigator(s).redFlags.includes("完全房室ブロック候補"));assert.equal(reviewProgress(s).hasUnreviewed,true)});
test("R on T plus QT prolongation raises interim Red Flag",()=>{const s=abnormal(abnormal(state(),"qt",{prolonged:true,qtcEntered:true}),"ectopy",{pvc:true,rOnT:true});assert.ok(evaluateReviewNavigator(s).redFlags.some(x=>x.includes("R on T")))});
test("indeterminate remains in exclusion warnings",()=>{const s=state();s.steps.qt.status="indeterminate";assert.ok(evaluateReviewNavigator(s).exclusions.some(x=>x.includes("QT／QTc")))});
test("urgent mode does not mutate review findings",()=>{const s=state();s.urgentMode=true;assert.equal(evaluateReviewNavigator(s).redFlags.length,0)});
test("navigator contains no network or persistent storage path",()=>{const source=fs.readFileSync("components/ecg/SystematicReviewNavigator.tsx","utf8");assert.doesNotMatch(source,/fetch\(|localStorage|sessionStorage|indexedDB|OpenAI/)});
test("PIN gate and existing twenty-case regression remain present",()=>{assert.match(fs.readFileSync("components/auth/EcgAuthGate.tsx","utf8"),/<EcgWorkspace/);assert.match(fs.readFileSync("tests/rule-engine-v2-cases.test.mjs","utf8"),/v2RegressionCases/)});
