import test from "node:test";import assert from "node:assert/strict";import {createDefaultSgarbossaInput} from "../data/sgarbossa/defaults.js";import {interpretSgarbossa} from "../logic/sgarbossa/interpret-sgarbossa.js";
import {createDefaultIntegratedInput} from "../data/integration/defaults.js";import {buildIntegratedInterpretation} from "../logic/integration/build-integrated-interpretation.js";
function b(){const x=createDefaultSgarbossaInput();Object.assign(x,{context:"lbbb",aiContext:"lbbb",contextClinicianConfirmed:true});x.leadMeasurements.forEach(m=>Object.assign(m,{qrsPolarity:"positive",rAmplitudeMm:10,sDepthMm:0,stDeviationMm:0,stDirection:"none",clinicianConfirmed:true}));return x}function m(x,p){Object.assign(x.leadMeasurements.find(v=>v.lead==="V2"),p);return interpretSgarbossa(x)}
test("A exact original 5 mm boundary",()=>assert.equal(m(b(),{qrsPolarity:"negative",sDepthMm:25,stDirection:"elevation",stDeviationMm:5}).originalCriteria[2].status,"positive"));
test("B modified positive while original criterion 3 negative",()=>{const r=m(b(),{qrsPolarity:"negative",sDepthMm:8,stDirection:"elevation",stDeviationMm:2});assert.equal(r.modifiedPositive,true);assert.equal(r.originalCriteria[2].status,"negative")});
test("C very deep S prevents proportional positivity",()=>assert.equal(m(b(),{qrsPolarity:"negative",sDepthMm:40,stDirection:"elevation",stDeviationMm:5}).modifiedCriteria[2].status,"negative"));
test("D shallow S makes 1 mm proportional",()=>assert.equal(m(b(),{qrsPolarity:"negative",sDepthMm:4,stDirection:"elevation",stDeviationMm:1}).modifiedPositive,true));
test("E missing baseline limits interpretation",()=>{const x=b();x.preconditions.baselineStable=false;assert.equal(interpretSgarbossa(x).originalPositive,null)});
test("F missing gain limits interpretation",()=>{const x=b();x.preconditions.gainKnown=false;assert.ok(interpretSgarbossa(x).missingInformation.includes("ゲイン"))});
test("G unconfirmed J point limits interpretation",()=>{const x=b();x.leadMeasurements[0].jPointConfirmed=false;assert.equal(interpretSgarbossa(x).modifiedPositive,null)});
test("H dynamic change raises possible concern despite negative criteria",()=>{const x=b();x.clinical.dynamicChange=true;assert.equal(interpretSgarbossa(x).clinicalConcern,"possible")});
test("I ratio uses signed convention",()=>assert.equal(m(b(),{qrsPolarity:"negative",sDepthMm:8,stDirection:"elevation",stDeviationMm:2}).leadResults.find(x=>x.lead==="V2").signedStSratio,-.25));
test("J doctor correction recalculates result",()=>{const x=b();assert.equal(interpretSgarbossa(x).modifiedPositive,false);m(x,{qrsPolarity:"negative",sDepthMm:8,stDirection:"elevation",stDeviationMm:2});assert.equal(interpretSgarbossa(x).modifiedPositive,true)});
test("integrated engine raises emergency candidate for modified positive LBBB",()=>{const x=createDefaultIntegratedInput();x.clinical.ischemicChestPain=true;x.sgarbossa={applicable:true,originalPositive:false,modifiedPositive:true,indeterminate:false,context:"lbbb"};const r=buildIntegratedInterpretation(x);assert.equal(r.diagnosticCandidates.find(c=>c.id==="lbbb-paced-occlusion")?.urgency,"emergency")});
test("integrated engine keeps negative criteria from excluding occlusion",()=>{const x=createDefaultIntegratedInput();x.clinical.ischemicChestPain=true;x.sgarbossa={applicable:true,originalPositive:false,modifiedPositive:false,indeterminate:false,context:"lbbb"};const r=buildIntegratedInterpretation(x);assert.ok(r.diagnosticCandidates.some(c=>c.id==="lbbb-paced-occlusion-limited"))});
