"use client";
import type {QtcFormula,QtInterpretation,QtInterpretationInput} from "@/types/qt-interpretation";
export function QtModule({input,result,onChange}:{input:QtInterpretationInput;result:QtInterpretation;onChange:(v:QtInterpretationInput)=>void}){const set=(patch:Partial<QtInterpretationInput>)=>onChange({...input,...patch,clinicianConfirmed:true});return <div className="qt-module">
 <section><h4>QT測定・医師修正</h4><div className="qt-grid"><NumberField label="QT実測値 ms" value={input.qtMs} set={v=>set({qtMs:v})}/><NumberField label="RR間隔 ms" value={input.rrMs} set={v=>set({rrMs:v})}/><NumberField label="心拍数 bpm" value={input.heartRate} set={v=>set({heartRate:v})}/><NumberField label="Q–T apex ms" value={input.tApexMs} set={v=>set({tApexMs:v})}/><label>測定状態<select value={input.measurementStatus} onChange={e=>set({measurementStatus:e.target.value as QtInterpretationInput["measurementStatus"]})}><option value="measurable">測定可能</option><option value="u_wave_overlap">U波との境界不明</option><option value="indeterminate">判定不能</option></select></label><label>QTc補正式<select value={input.formula} onChange={e=>set({formula:e.target.value as QtcFormula})}><option value="bazett">Bazett</option><option value="fridericia">Fridericia</option><option value="framingham">Framingham</option><option value="hodges">Hodges</option></select></label></div><div className="qt-checks"><Check label="Q開始確認" value={input.qStartKnown} set={v=>set({qStartKnown:v})}/><Check label="T終末確認" value={input.tEndKnown} set={v=>set({tEndKnown:v})}/><Check label="U波開始を確認" value={input.uWaveStartKnown} set={v=>set({uWaveStartKnown:v})}/></div></section>
 <section><h4>QTc補正結果</h4><div className="qt-values">{Object.entries(result.allFormulaValues).map(([name,value])=><div className={input.formula===name?"selected":""} key={name}><span>{name}</span><strong>{value??"—"} ms</strong></div>)}</div><p>AI推奨：<strong>{result.recommendedFormula}</strong>　選択値：<strong>{result.qtcMs??"判定不能"} ms</strong>{result.qAtcMs!=null&&<>　Q-aTc：<strong>{result.qAtcMs} ms</strong></>}</p><div className="clinical-pearl"><strong>Clinical Pearl</strong><p>QTは正常の約140%を超えることは稀です。著明延長ではU波を含めていないか確認してください。Bazett式は頻脈で過大評価、徐脈で過小評価し得ます。</p></div></section>
 <section><h4>TdPリスク確認</h4><div className="qt-checks"><Check label="失神" value={input.syncope} set={v=>set({syncope:v})}/><Check label="PVC" value={input.pvc} set={v=>set({pvc:v})}/><Check label="R on T" value={input.rOnT} set={v=>set({rOnT:v})}/><Check label="低K" value={input.lowK} set={v=>set({lowK:v})}/><Check label="低Mg" value={input.lowMg} set={v=>set({lowMg:v})}/><Check label="低Ca" value={input.lowCa} set={v=>set({lowCa:v})}/><Check label="高Ca" value={input.highCa} set={v=>set({highCa:v})}/><Check label="QT延長薬" value={input.qtProlongingDrug} set={v=>set({qtProlongingDrug:v})}/><Check label="徐脈" value={input.bradycardia} set={v=>set({bradycardia:v})}/><Check label="心不全" value={input.heartFailure} set={v=>set({heartFailure:v})}/></div></section>
 <section className={result.redFlags.length?"qt-redflag":"qt-result"}><h4>{result.redFlags.length?"Red Flag／TdPリスク":"QT/QTc判定"}</h4><p><strong>{result.classification}</strong>　TdPリスク：<strong>{result.tdpRiskLevel}</strong></p>{result.redFlags.map(x=><p key={x}>理由：{x}</p>)}{result.warnings.map(x=><p className="muted" key={x}>{x}</p>)}</section>
 </div>}
function NumberField({label,value,set}:{label:string;value:number|null;set:(v:number|null)=>void}){return <label>{label}<input type="number" min="0" value={value??""} onChange={e=>set(e.target.value?Number(e.target.value):null)}/></label>}function Check({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>{label}</label>}
