"use client";
import type {TWaveInterpretation,TWaveInterpretationInput,TWaveMorphology,TWavePolarity,TWaveSymmetry} from "@/types/t-wave-interpretation";
const morphs:Array<[TWaveMorphology,string]>=[["normal","正常"],["inverted","陰性"],["biphasic","二相性"],["hyperacute","hyperacute"],["peaked","peaked"],["giant_negative","巨大陰性"],["alternans","alternans"],["flattened","平低"],["notched","notched"],["indeterminate","判定不能"]];
const polarities:Array<[TWavePolarity,string]>=[["positive","陽性"],["negative","陰性"],["biphasic_positive_negative","二相性 ＋→−"],["biphasic_negative_positive","二相性 −→＋"],["flat","平低"],["indeterminate","判定不能"]];
export function TWaveModule({input,result,onChange}:{input:TWaveInterpretationInput;result:TWaveInterpretation;onChange:(v:TWaveInterpretationInput)=>void}){const lead=(name:string,patch:object)=>onChange({...input,leadMeasurements:input.leadMeasurements.map(m=>m.lead===name?{...m,...patch,clinicianConfirmed:true}:m)});const clinical=(patch:object)=>onChange({...input,clinical:{...input.clinical,...patch}});return <div className="t-wave-module">
 <section><h4>誘導分布・形態（医師確認）</h4><p className="muted">極性・対称性・振幅・二相性方向・動的変化を医師確定値で再計算します。</p><div className="t-wave-lead-grid">{input.leadMeasurements.slice(0,12).map(m=><div className={`t-wave-chip t-${m.morphology}`} key={m.lead}><strong>{m.lead}</strong><select aria-label={`${m.lead} T波形態`} value={m.morphology} onChange={e=>lead(m.lead,{morphology:e.target.value as TWaveMorphology})}>{morphs.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select aria-label={`${m.lead} T波極性`} value={m.polarity} onChange={e=>lead(m.lead,{polarity:e.target.value as TWavePolarity})}>{polarities.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select aria-label={`${m.lead} T波対称性`} value={m.symmetry} onChange={e=>lead(m.lead,{symmetry:e.target.value as TWaveSymmetry})}><option value="asymmetric">非対称</option><option value="symmetric">対称</option><option value="indeterminate">判定不能</option></select><label><span>振幅 mm</span><input type="number" min="0" step="0.1" value={m.amplitudeMm??""} onChange={e=>lead(m.lead,{amplitudeMm:e.target.value?Number(e.target.value):null})}/></label><label className="check"><input type="checkbox" checked={m.dynamicChange===true} onChange={e=>lead(m.lead,{dynamicChange:e.target.checked})}/>動的</label></div>)}</div></section>
 <section><h4>臨床・ST・QT・QRSとの関係</h4><div className="t-wave-context-grid"><label>年齢<input type="number" value={input.clinical.age??""} onChange={e=>clinical({age:e.target.value?Number(e.target.value):null})}/></label><label>性別<select value={input.clinical.sex??""} onChange={e=>clinical({sex:e.target.value||null})}><option value="">未入力</option><option value="male">男性</option><option value="female">女性</option></select></label><label>QT状態<select value={input.associatedQtStatus} onChange={e=>onChange({...input,associatedQtStatus:e.target.value as TWaveInterpretationInput["associatedQtStatus"]})}><option value="not_checked">QT未確認</option><option value="confirmed">QT確認済み</option><option value="difficult">QT測定困難</option><option value="u_wave_overlap">U波との区別困難</option></select></label><label>QRS背景<select value={input.qrsContext} onChange={e=>onChange({...input,qrsContext:e.target.value as TWaveInterpretationInput["qrsContext"]})}>{["narrow","rbbb","lbbb","paced","lvh","rvh","preexcitation","ventricular_rhythm","wide","unknown"].map(v=><option value={v} key={v}>{v}</option>)}</select></label></div><div className="t-wave-checks"><Check label="胸痛歴" value={input.clinical.chestPainHistory} set={v=>clinical({chestPainHistory:v})}/><Check label="現在は無痛" value={input.clinical.currentlyPainFree===true} set={v=>clinical({currentlyPainFree:v})}/><Check label="虚血症状" value={input.clinical.ischemicSymptoms} set={v=>clinical({ischemicSymptoms:v})}/><Check label="循環動態不安定" value={input.clinical.hemodynamicInstability} set={v=>clinical({hemodynamicInstability:v})}/><Check label="失神" value={input.clinical.syncope} set={v=>clinical({syncope:v})}/><Check label="神経症状" value={input.clinical.neurologicSymptoms} set={v=>clinical({neurologicSymptoms:v})}/><Check label="腎不全" value={input.clinical.renalFailure} set={v=>clinical({renalFailure:v})}/><Check label="肉眼的交互変化が持続" value={input.clinical.macroscopicAlternationPersistent} set={v=>clinical({macroscopicAlternationPersistent:v})}/></div></section>
 <section className={result.redFlags.length?"t-wave-redflag":"t-wave-result"}><h4>{result.redFlags.length?"Red Flag／見逃し注意":"T波判定"}</h4><p><strong>{result.overallClassification}</strong></p>{result.wellensPattern.startsWith("type_")&&<p>Wellens pattern：{result.wellensPattern==="type_a_candidate"?"Type A候補（二相性＋→−）":"Type B候補（深い対称性陰性）"}</p>}{result.redFlags.map(x=><p key={x}>理由：{x}</p>)}{result.normalVariantCandidates.map(x=><p key={x}>{x}</p>)}{result.warnings.map(x=><p className="muted" key={x}>{x}</p>)}</section>
 <section><h4>不足情報・追加確認・次の一手</h4>{result.missingInformation.length>0&&<p className="muted">不足：{result.missingInformation.join("、")}</p>}<ul className="list">{result.nextActions.map(x=><li key={x}>{x}</li>)}</ul></section>
 </div>}
function Check({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>{label}</label>}
