import type {IntegratedInput,IntegratedInterpretation} from "@/types/integrated-interpretation";

export type LocalAnalysisStatus="idle"|"validating_image"|"detecting_layout"|"extracting_waveforms"|"measuring"|"evaluating_rules"|"success"|"unsupported"|"failed"|"cancelled";
export type PocQuality="adequate"|"limited"|"inadequate";
export type RhythmRegularity="regular"|"regularly_irregular"|"irregularly_irregular"|"indeterminate";
export type QrsWidthCandidate="narrow"|"wide"|"indeterminate";
export type StDirection="elevation"|"depression"|"isoelectric"|"indeterminate";
export type StandardPocLead="I"|"II"|"III"|"aVR"|"aVL"|"aVF"|"V1"|"V2"|"V3"|"V4"|"V5"|"V6";
export type MeasurementSource="long_ii"|"lead_ii"|"other"|"indeterminate";
export type PeakCandidate={x:number;y:number;prominence:number;amplitude:number;candidateWidthPx:number;precedingRrPx:number|null;followingRrPx:number|null;clusterId:number;accepted:boolean;rejectionReason:string|null;artifactClass:"same_qrs_cluster"|"t_wave_or_noise"|"grid_residual_candidate"|"local_noise_candidate"|null};
export type QrsBeatAudit={peakX:number;onsetX:number|null;offsetX:number|null;durationMs:number|null};
export type RuleContextAuditItem={field:string;value:boolean|number|string|null;source:"local_image_poc"|"physician_corrected"|"indeterminate";quality:PocQuality|"indeterminate"};

export type ComponentCandidateType="waveform_candidate"|"grid_candidate"|"text_candidate"|"calibration_candidate"|"noise_candidate"|"indeterminate";
export type ConnectedComponentAudit={id:number|string;boundingBox:{x:number;y:number;width:number;height:number};pixelCount:number;width:number;height:number;aspectRatio:number;centroid:{x:number;y:number};leftEndpoint:{x:number;y:number};rightEndpoint:{x:number;y:number};top:number;bottom:number;localDarkness:number;gridOverlap:number;candidateType:ComponentCandidateType};
export type WaveformSegmentAudit={componentId:number|string;start:{x:number;y:number};end:{x:number;y:number};length:number;slope:number;verticalRange:number;continuityScore:number;waveformLikelihood:number;points:Array<{x:number;y:number}>};
export type ConnectedBeatCandidate={source:"connected_component";componentId:number|string;clusterId:number;x:number;y:number;amplitude:number;prominence:number;height:number;width:number;area:number;quality:PocQuality;limitations:string[];accepted:boolean;rejectionReason:string|null;duplicateSuspected:boolean;missingBeatSuspectedAfter:boolean;outlier:boolean};
export type ConnectedBeatAudit={source:"connected_component";candidates:ConnectedBeatCandidate[];rawCandidateCount:number;clusterCount:number;rCandidateCount:number;acceptedCount:number;rejectedCount:number;pixelIntervals:number[];rrIntervalsMs:number[];medianRrMs:number|null;meanRrMs:number|null;minRrMs:number|null;maxRrMs:number|null;iqrMs:number|null;cv:number|null;outlierCount:number;duplicateCount:number;missingBeatCount:number;millisecondsPerPixel:number|null;timeCalibration:{confirmed:boolean;paperSpeedMmPerSecond:25|null;gridPeriodPx:number|null;gridSpacingMm:5};heartRateBpm:number|null;regularity:"regular"|"irregular"|"indeterminate";centerlineAgreement:{matched:number;total:number};quality:PocQuality;limitations:string[]};
export type ConnectedTrackingAudit={roi:{x:number;y:number;width:number;height:number};candidatePixels:number;components:ConnectedComponentAudit[];segments:WaveformSegmentAudit[];qrsCandidates:ConnectedComponentAudit[];qrsClusters:Array<{id:number;componentIds:Array<number|string>;boundingBox:{x:number;y:number;width:number;height:number}}>;rPeakCandidates:Array<Omit<ConnectedBeatCandidate,"accepted"|"rejectionReason"|"duplicateSuspected"|"missingBeatSuspectedAfter"|"outlier">>;beatAudit?:ConnectedBeatAudit;coverage:number;gaps:Array<{startX:number;endX:number;length:number}>;quality:PocQuality};
export type CenterlineAudit={sourceWidth:number;sourceHeight:number;roi:{x:number;y:number;width:number;height:number};totalColumns:number;trackedColumns:number;missingColumns:number;ambiguousColumns:number;trackingCoverage:number;missingSegments:Array<{startX:number;endX:number;length:number}>;ambiguousSegments:Array<{startX:number;endX:number;length:number}>;candidatePoints:Array<{x:number;y:number}>;legacyPoints:Array<{x:number;y:number}>;connected?:ConnectedTrackingAudit};
export type DigitizedLeadPoC={lead:StandardPocLead;points:Array<{x:number;y:number}>;quality:PocQuality;limitations:string[];audit?:CenterlineAudit};
export type StDirectionCandidate={lead:StandardPocLead;direction:StDirection;quality:PocQuality;baselineCandidate:{startX:number;endX:number}|null;jPointCandidate:{x:number;y:number}|null;samplePointCandidate:{x:number;y:number}|null;baselineY:number|null;stY:number|null;differencePx:number|null;limitations:string[]};
export type LocalPocMeasurements={heartRateBpm:number|null;heartRateSource:MeasurementSource;rrIntervals:number[];rhythmRegularity:RhythmRegularity;rhythmSource:MeasurementSource;rawPeakCandidateCount:number;peakClusterCount:number;peakCandidates:PeakCandidate[];peakQuality:{refractoryViolationRate:number;prominenceMedian:number|null;rrOutlierRate:number|null};estimatedQrsDurationMs:number|null;qrsWidthCandidate:QrsWidthCandidate;qrsAudit:{measurementLead:string|null;beatCount:number;beats:QrsBeatAudit[];medianDurationMs:number|null;quality:PocQuality;limitations:string[]};stDirections:StDirectionCandidate[];quality:PocQuality;limitations:string[]};
export type LocalPocResult={imageQuality:PocQuality;layout:"three_by_four"|"three_by_four_with_long_ii"|"six_by_two";leads:DigitizedLeadPoC[];longII:DigitizedLeadPoC|null;measurements:LocalPocMeasurements;context:IntegratedInput;contextAudit:RuleContextAuditItem[];ruleResult:IntegratedInterpretation;extractedFields:string[];indeterminateFields:string[];limitations:string[];processingTimeMs:number};
export type LocalPocCorrection={heartRateBpm:number|null;rhythmRegularity:RhythmRegularity;qrsWidthCandidate:QrsWidthCandidate;stDirections:StDirectionCandidate[];source:"local_image_poc"|"physician_corrected"};
