import {qtEvidenceSources,qtSources} from "../../data/qt-interpretation/sources.js";
export function calculateQtc(qtMs,rrMs,heartRate,formula){if(!valid(qtMs)||(!valid(rrMs)&&!valid(heartRate)))return null;const hr=valid(heartRate)?heartRate:60000/rrMs,rr=valid(rrMs)?rrMs/1000:60/hr;const value=formula==="bazett"?qtMs/Math.sqrt(rr):formula==="fridericia"?qtMs/Math.cbrt(rr):formula==="framingham"?qtMs+154*(1-rr):qtMs+1.75*(hr-60);return Math.round(value)}
export function interpretQt(input){const hr=valid(input.heartRate)?input.heartRate:valid(input.rrMs)?60000/input.rrMs:null,rr=valid(input.rrMs)?input.rrMs:valid(hr)?60000/hr:null;const formulas={bazett:calculateQtc(input.qtMs,rr,hr,"bazett"),fridericia:calculateQtc(input.qtMs,rr,hr,"fridericia"),framingham:calculateQtc(input.qtMs,rr,hr,"framingham"),hodges:calculateQtc(input.qtMs,rr,hr,"hodges")};const recommendedFormula=hr!=null&&(hr>100||hr<60)?"fridericia":"bazett";const qtc=formulas[input.formula],qAtc=calculateQtc(input.tApexMs,rr,hr,input.formula);const measurementLimited=!input.preconditionsAdequate||input.measurementStatus!=="measurable"||!input.qStartKnown||!input.tEndKnown;
 let classification="normal";if(measurementLimited||qtc==null)classification="indeterminate";else if(qtc<=330)classification="short";else if(qtc>=500)classification="marked_prolongation";else if(qtc>=480)classification="prolonged";else if(qtc>=440)classification="borderline_prolonged";
 const risks=[];for(const [yes,label] of [[qtc!=null&&qtc>=500,"QTc 500 ms以上"],[input.syncope,"失神"],[input.pvc,"PVC"],[input.rOnT,"R on T"],[input.lowK,"低K"],[input.lowMg,"低Mg"],[input.lowCa,"低Ca"],[input.qtProlongingDrug,"QT延長薬"],[input.bradycardia||hr!=null&&hr<60,"徐脈"],[input.femaleSex||input.sex==="female","女性"],[input.heartFailure,"心不全"]])if(yes)risks.push(label);const highSignals=risks.filter(x=>["QTc 500 ms以上","失神","R on T"].includes(x)).length;const tdpRiskLevel=classification==="indeterminate"?"indeterminate":highSignals>=1&&risks.length>=3||risks.length>=5?"high":risks.length>=2?"increased":"low";
 const redFlags=[];if(classification==="marked_prolongation")redFlags.push("QTc 500 ms以上の著明延長");if(tdpRiskLevel==="high")redFlags.push("複数のTdPリスク因子が重複");if(input.syncope&&["prolonged","marked_prolongation"].includes(classification))redFlags.push("QT延長と失神");if(input.rOnT&&classification.includes("prolong"))redFlags.push("QT延長とR on T");
 const factors=[];if(classification.includes("prolong"))factors.push(factor("long","先天性LQTSまたは二次性QT延長","other",true,["薬剤","低K","低Mg","低Ca","徐脈","心筋虚血","低体温"]));if(classification==="short")factors.push(factor("short","QT短縮候補","other",false,["高Ca","先天性SQTS","ジギタリス"]));if(input.qtProlongingDrug)factors.push(factor("drug","薬剤性QT延長候補","drug",false,["服薬"]));if(input.lowK||input.lowMg||input.lowCa||input.highCa)factors.push(factor("electrolyte","電解質異常候補","electrolyte",false,["K","Mg","Ca"]));
 const missing=[];if(!valid(input.qtMs))missing.push("QT実測値");if(!valid(rr)&&!valid(hr))missing.push("RRまたは心拍数");if(input.measurementStatus==="u_wave_overlap")missing.push("T終末とU波の境界");
 const warnings=[];if(input.measurementStatus==="u_wave_overlap"||!input.tEndKnown)warnings.push("QT測定制限：U波との境界が不明瞭です。");if(qtc!=null&&input.qtMs!=null&&qtc>input.qtMs*1.4)warnings.push("QTcが実測QTの約140%を超えています。U波を含めて測定していないか確認してください。");if(input.formula==="bazett"&&hr!=null&&hr>100)warnings.push("Bazett式は頻脈でQTcを過大評価し得ます。");if(input.formula==="bazett"&&hr!=null&&hr<60)warnings.push("Bazett式は徐脈でQTcを過小評価し得ます。");if(classification==="short")warnings.push("QT短縮では高Caを確認し、Q-aTcも参考にしてください。");
 const checks=["K","Mg","Ca","服薬","連続モニター","再ECG","失神歴"];const actions=[...(redFlags.length?["TdPリスクを直ちに再評価し連続モニター"]:[]),...(["borderline_prolonged","prolonged","marked_prolongation","short"].includes(classification)?["K・Mg・Caと服薬を確認","再ECGでQT/QTcを再測定"]:[])];return {qtMs:valid(input.qtMs)?input.qtMs:null,qtcMs:qtc,qAtcMs:qAtc,allFormulaValues:formulas,recommendedFormula,classification,tdpRiskLevel,tdpRiskFactors:risks,redFlags,possibleFactors:factors,mustNotMiss:redFlags.length?factors.filter(f=>f.isRedFlag):[],missingInformation:missing,additionalChecks:checks,nextActions:[...new Set(actions)],warnings,limitations:["TdP、先天性LQTS/SQTS、遺伝子型を自動診断しません。","補正式間の差と臨床背景を医師が確認してください。","wide QRS時のJT補正詳細は未実装です。"],urgency:redFlags.length?"emergency":classification==="indeterminate"?"uncertain":classification==="normal"?"routine":"same_day",sources:qtEvidenceSources}}
function factor(id,label,category,isRedFlag,requiredInputs){return {id:`qt-${id}`,label,category,priority:"high",supportingInputs:[label],contradictingInputs:[],requiredInputs,isRedFlag,sources:[qtSources.jcs,qtSources.aha]}}function valid(v){return typeof v==="number"&&Number.isFinite(v)&&v>0}
